[preface]
[[preface]]
== Preface

The OGC SensorThings API provides an open, geospatial-enabled and unified way to interconnect the internet of things devices, data, and applications over the web. The OGC SensorThings API is an open standard, and that means it is non-proprietary, platform-independent, and perpetual royalty-free. Although it is a new standard, it builds on a rich set of proven-working and widely-adopted open standards, such as the web protocols and the ogc sensor web enablement (swe) standards, including the iso/ogc observation and measurement data model [ogc 10-004r3 and iso 19156:2011]. That also means the OGC SensorThings API is extensible and can be applied to not only simple but also complex use cases.


At a high level the OGC SensorThings API provides two main functionalities and each function is handled by a part. The two parts are the part i - sensing and the part ii - tasking. The sensing part provides a standard way to manage and retrieve observations and metadata from heterogeneous iot sensor systems. The tasking part provides a standard way for parameterizing - also called tasking - of task-able iot devices, such as sensors or actuators. The tasking part is planned as a future work activity and will be defined in a separate document as the part ii of the sensorthings api.


The sensing part provides functions similar to the ogc sensor observation service (sos) and the tasking part will provide functions similar to the ogc sensor planning service (sps). The main difference between the sensorthings api and the ogc sos and sps is that the sensorthings api is designed specifically for the resource-constrained iot devices and the web developer community. As a result, the sensorthings api follows the rest principles, the use of an efficient json encoding, the use of mqtt protocol, the use of the flexible oasis odata protocol and url conventions.


Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The open geospatial consortium shall not be held responsible for identifying any or all such patent rights.

__recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.__


[preface]
[[changes_v_11]]
== Changes in version 1.1

Version 1.1 of the SensorThings API is an update to version 1.0 that is (mostly) backwards compatible with version 1.0.
Besides the many small clarifications, the main changes are:

* All entities (except for HistoricalLocation) now have a field of the type JSON Object.
  In version 1.0 such a field already existed for the Thing entity (named `+properties+`), and for the Observation entity (named `+parameters+`).
  These fields proved to be extremely useful for storing additional structured meta data used in many domains, that could also be used in filters.
  Now, all entities except for HistoricalLocation have such a very useful property, whereby in the Observation entity it retains the name `+parameters+`.
* The service root page now shows the requirements that the server implements and allows extensions to expose additional settings.
  This allows users to easily see exactly which extensions and optional features a server implements.
  The MQTT extension can now list the MQTT endpoints on the root page, so that a user can discover those endpoints.
* MQTT topics now must start with the version number of the specification.
  There were differences between server implementations, with some requiring the version number prefix and others not.
  This change will fix those incompatibilities from this version on.

The first two changes add extra fields to the JSON returned by the server and should not influence clients made for version 1.0, as most client will ignore any fields they do not know.
The second change may cause some minor issues for some clients that are not using the version prefix in MQTT topics, but those clients would already have issues connecting to any server that does use the version prefix in MQTT topics.



