[[references]]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

* OGC 08-094r1, OGC SWE Common Data Model Encoding Standard.
* OGC 15-078r6, OGC SensorThings API — Part 1: Sensing.
* OGC 17-011r2, JSON Encoding Rules SWE Common / SensorML.
* OASIS MQTT Version 3.1.1
* ISO 8601:2004 Data elements and interchange formats – Information interchange - Representation of dates and times.
* OGC 10-004r3 and ISO 19156:2011(E), OGC Abstract Specification Topic 20: Geographic information — Observations and Measurements
* OASIS OData Version 4.0 Part 1: Protocol Plus Errata 02
* OASIS OData Version 4.0 Part 2: URL Conventions Plus Errata 02
* OASIS OData JSON Format Version 4.0 Plus Errata 02
* OASIS OData ABNF Construction Rules Errata 02
* RFC 2616, Hypertext Transfer Protocol -- HTTP/1.1

