[appendix,obligation="informative"]
== STA-WebSub Hub Implementation Guidance
This appendix provides guidance as to how to implement a STA-WebSub Hub interoperating with a SensorThings API v1.1 service.

[NOTE]
====
This appendix uses the natural language word "`MUST`" to indicate de-facto implementation requirements for a STA-WebSub Hub. The formal identification of requirements using the word "`SHALL`" is not used because the STA-WebSub Hub is not the standardization target!
====

=== Callback Authentication
An implementation MUST accept the `hub.api_key` or `hub.x_api_key` with a subscription request. If both parameters (the `hub.api_key` **and** the `hub.x_api_key`) are used, the implementation MUST deny the subscription and return a HTTP response status code 400.

* If the subscription request includes the `hub.api_key` parameter, the Hub MUST add the HTTP header `Api-Key` to the request send to the Subscriber's callback
* If the subscription request includes the `hub.x_api_key` parameter, the Hub MUST add the HTTP header `X-Api-Key` to the request send to the Subscriber's callback

The `hub.api_key` and `hub.x_api_key` parameters MUST be used exclusively and SHOULD only be specified with static callback URLs. The parameter value MUST be less than 200 bytes in length.

=== X-Api-Key and X-Hub-Signature
One fundamental runtime functionality for a Hub is its ability to deliver notification content to all Subscribers. The W3C WebSub offers the use of HMAC (Hash-based Message Authentication Code), allowing Subscribers to validate the authenticity of the received content and ensure it comes from the expected Hub. By leveraging HMAC, Subscribers can also verify content integrity, which is crucial when using non-secure communication, such as HTTP instead of HTTPS. The W3C WebSub supports the transmission of the HMAC through the HTTP header `X-Hub-Signature`.

However, the use of HMAC signatures imposes a burden on the CPU and memory of both the Hub and the Subscribers when calculating the HMAC value. This burden also necessitates caching (temporary storage) of large content at both the Hub and Subscriber implementations. As a result, the use of HMAC prevents Subscribers from streaming the received content directly into connected workflow processing. On the Hub side, caching does not introduce a significant resource burden, as an implementation would likely cache the content before distributing it to all Subscribers.

Validating the HMAC requires that a Subscriber receives the entire content, which creates a potential denial-of-service vulnerability. If an attacker sends large fraudulent content at high frequency using numerous parallel requests, the Subscriber must process the entire content to determine its authenticity, which may ultimately lead to denial of processing.

The W3C WebSub recommends using a random callback URL that is refreshed by the Subscriber whenever a subscription is updated. This practice offers equivalent protection for the callback endpoint compared to using an API key. When a callback endpoint is associated with a single Hub and operates over HTTPS, the use of HMAC becomes unnecessary.

In cases where refreshing callback URLs is not feasible or too complex, STA-WebSub Hub supports API key authentication as an alternative. The use of an API key compensates for the lack of random callback URLs. Furthermore, an API key, combined with HTTPS callback URLs, provides the same level of authenticity and integrity as HMAC, but without the need to calculate HMAC on the Hub side and validate it on the Subscriber side. This approach reduces the resource burden on both the Hub and Subscriber, which is particularly important for Hub deployments on the edge.

Similar to how `hub.secret` shares the secret for HMAC generation between a Subscriber and a Hub, a STA-WebSub subscription may include the parameters `hub.api_key` or `hub.x_api_key` to activate API key usage at the Hub. These parameters prompt the Hub to add the HTTP headers `Api-Key` or `X-Api-Key` when distributing content to the Subscriber.

=== Subscription
The STA-WebSub Hub, which is linked to a SensorThings API service, supports the W3C subscribe/unsubscribe protocol and converts a subscription topic URL (`hub.topic`) into an MQTT topic. A compliant implementation must be capable of transforming the absolute HTTP(S) request URL into the corresponding MQTT topic for the associated SensorThings API service.

The Hub utilizes the MQTT protocol to handle subscriptions and unsubscriptions with the MQTT broker that corresponds to the SensorThings API service.

An implementation of the STA-WebSub Hub must convert the HTTP discovery URL into an MQTT topic by omitting the SensorThings API `baseUrl`. For instance, in a deployment where `baseUrl=http://localhost:8080/mysta`, the discovery URL `http://localhost:8080/mysta/v1.1/Observations` would result in the MQTT topic `v1.1/Observations`.

[[WebSubSubscription]] 
.Subscription Handling in the STA-WebSub Hub
[plantuml]
....
@startuml

participant Subscriber
participant "STA Service - HTTP interface\n(Publisher)"

Subscriber -> Hub: HTTP POST\nhub.mode=subscribe\nhub.callback=http://mywebhook\nhub.topic=http://localhost/sta/v1.1/Observations?\n$select=result
Hub -> Subscriber: HTTP 202 - Accepted

Hub -> "SensorThings API service": HTTP HEAD\nhttp://localhost/sta/v1.1/Observations?\n$select=result
"SensorThings API service" -> Hub: Link: <http://localhost/sta/v1.1/Observations?\n$select=result>; rel="self"\nLink: <http://hub/>; rel="hub"

opt Link 'self' is present
Hub -> "SensorThings API service": MQTT subscribe\ntopic=v1.1/Observations?$select=result
Hub -> Hub : Store topic - callback
end

@enduml
....

As defined in the W3C WebSub, a Subscriber sends a subscription request to the Hub using the URL from the `<Link/> rel="hub"`. The subscription topic (`hub.topic`) is identical to the URL returned with the `<Link/> rel="self"`. 

Upon receiving the subscription request, it is highly recommended that the Hub validates the Subscriber's intent as defined in the W3C WebSub specification. For a STA-WebSub Hub, it is also advisable to check the subscription's validity with the publisher using the discovery protocol. If successful (indicated by the inclusion of `Link rel="self"` in the discovery response), the Hub should then subscribe to the SensorThings API service via MQTT, transforming the request URL into an MQTT topic.

It is recommended to use the HTTP HEAD method for discovery requests, as this approach helps avoid unnecessary data transfer.

For new subscriptions or when renewing an existing one (when the Hub receives a subscribe request for an already active subscription), the implementation must set or update the API key and use this value for subsequent content distribution to the Subscriber.

=== Notification
The STA-WebSub Hub must support receiving MQTT notifications from the MQTT broker associated with the SensorThings API service.

The implementation must listen for notifications from the MQTT broker of the SensorThings API service.

Once a notification is received, the implementation must distribute the content of the notification to all subscribers using HTTP(S), as defined by the W3C WebSub Recommendation.

[[WebSubNotification]] 
.MQTT notification delivery by the STA-WebSub Hub
[plantuml]
....
@startuml

participant Subscriber
participant Hub
participant "STA Service - MQTT interface"

"STA Service - MQTT interface" -> Hub: notification\nMQTT topic\nJSON encoded content

loop for each Subscriber
    Hub -> Subscriber : HTTP POST content
end

@enduml
....

If the subscription was initiated using the `hub.api_key` or `hub.x_api_key`, the implementation must include the `Api-Key` or `X-Api-Key` in the HTTP request sent to the Subscriber's callback URL (Webhook).

Similarly, the implementation must add the `X-Hub-Signature` header if the subscription was created using the `hub.secret` parameter.

=== Implementations
Prototype implementations that illustrate a STA-WebSub system are available as open source: 

* The STA-WebSub Hub is available as open source from Github: https://github.com/securedimensions/STA-WebSub-Hub
* The W3C discovery protocol extension for the SensorThings API service is implemented as a plugin to FROST-Server:
    ** STA-WebSub plugin: https://github.com/securedimensions/FROST-Server-WebSub
    ** The FROST-Server: https://github.com/FraunhoferIOSB/FROST-Server
* A simple and generic WebSub Subscriber is available as open source from Github: https://github.com/securedimensions/STA-WebSub-Subscriber
* A simple and generic client for testing the STA-WebSub discovery protocol is available as open source: https://github.com/securedimensions/STA-WebSub-Discovery

[NOTE]
====
The key work for crafting this OGC Standard was undertaken in the Enhancing Citizen Observatories for healthy, sustainable, resilient and inclusive cities (CitiObs) project, which received funding from the European Union’s Horizon Europe research and innovation program.

These implementations are provided for education and **must not** be used in production! Improvements via pull-requests are welcome.
====