[obligation="normative"]
== SensorThings API - WebSub Extension (Normative)
As outlined in chapter <<introduction>>, a system leveraging the SensorThings APIWebSub Extension (STA-WebSub) is a specialization of the asynchronous messaging system described in the <<W3CWebSub>>. As a W3C WebSub system, the STA-WebSub system is comprised of three parts (Subscriber, Hub, Publisher). In the context of this OGC SensorThings API Extension: WebSub Asynchronous Messaging Standard, the Publisher is the SensorThings API service which can be split into two sub-components: the HTTP interface and the MQTT broker. 

[NOTE]
====
Appendix B provides guidance for implementing a STA-WebSub Hub.
====

The STA-WebSub extension defines the following requirements class: 

* Discovery Requirements Class (mandatory)

=== Discovery Requirements Class (mandatory)
The `Discovery` requirements class is implemented at the SensorThings API service - HTTP interface to support the W3C WebSub discovery protocol. 

include::../requirements/requirements_class_discovery.adoc[]

==== Requirement HTTP Methods
According to <<W3CWebSub>>, discovery can be achieved via HTTP GET and HEAD methods.

include::../requirements/requirement001.adoc[]

==== Requirement Link Header 'hub'
According to <<W3CWebSub>>, discovery always returns `<Link/>; rel="hub"`.

include::../requirements/requirement002.adoc[]

==== Requirement Link Header 'self'
According to <<W3CWebSub>>, discovery returns `<Link/>; rel="self"` for a URL that is suitable for subscription.

include::../requirements/requirement003.adoc[]

==== Requirement Link Header 'help'
Returning the `<Link/>; rel="help"` header (specific to STA-WebSub) indicates the cause why the requested URL is not suitable for subscription.

include::../requirements/requirement004.adoc[]

==== Requirement ODATA query options support

include::../requirements/requirement100.adoc[]

==== Requirement ODATA support advertisement

include::../requirements/requirement101.adoc[]

==== Requirement ODATA Blacklisting
A STA URL may contain query parameters (after the `?`) presenting ODATA options. An implementation may deny discovery (and thereby later subscription) for certain ODATA options like `$expand` or `$filter`. 

include::../requirements/requirement102.adoc[]

[EXAMPLE]
====
Example blacklisting structure for ODATA options
[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "odata_denied": <JSON Array of denied ODATA options>
        }
    }
}
----
====

[EXAMPLE]
====
For example, the following root page snippet indicates restrictions for `$expand`, `$skip`, `$top` and `$filter`

[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "odata_denied": ["$expand", "$skip", "$top", "$filter"]
        }
    }
}
----
====

[EXAMPLE]
====
The following root page snippet indicates **no** restrictions for ODATA options

[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "odata_denied": []
        }
    }
}
----
====

==== Requirement Topics Blacklisting
The support for STA-WebSub can be determined from the root page as the relevant conformance classes are listed.

include::../requirements/requirement200.adoc[]

[EXAMPLE]
====
Example blacklisting structure for topics
[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": <JSON Array of denied topics>
        }
    }
}
----
====

include::../requirements/requirement201.adoc[]

[EXAMPLE]
====
The following root page snippet indicates deny for the topics `v1.1/Observations` and `v1.1/Datastreams('very chatty')/Observations`

[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": ["v1.1/Observations", "v1.1/Datastreams('very chatty')/Observations"]
        }
    }
}
----
====

[EXAMPLE]
====
The following root page snippet indicates **no** deny for topics:

[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": []
        }
    }
}
----
====


