== Conformance

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

=== Introduction

The STAplus 1.0 standard defines an extension to the OGC Standards <<OGC15-078r6>> (SensorThings API v1.0) and <<OGC18-088>> (SensorThings API v1.1) by adding additional entity types to the data model. Access to the STAplus entities via HTTP is defined in the Read, Create, Update, and Delete Requirements Classes. The use of MQTT for STAplus entities is defined in the MQTT Requirements Class. A default del:[default-]CRS is defined via the Default-CRS Requirements Class and additional geometry encodings are defined in the Geometry del:[] add:[-]FG and Geometry del:[] add:[-]WKT Requirements Class add:[es]. The Authentication Requirements Class supports the unique identification of acting users. The Business Logic Requirements Class supports the textual description of the implemented business logicadd:[, including a GDPR compliance note for `Location` and `HistoricalLocation` of a `Thing` owned by an individual `Party`, and a License attribution note for creator identification when `License/definition` identifies an attribution license]. An example of such a Business Logic is described in the <<OGC21-068>>.

=== STAplus 1.0 Conformance Classes

This OGC Standard defines one mandatory and several optional conformance classes.

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC Standard, a software implementation shall choose to implement:

* The del:[one] mandatory conformance class `Core`;
* Any one of the optional conformance classes; and
* Pass all applicable tests as defined in Annex A.

This is the list of STAplus Conformance Classes.

* *Core* (mandatory): This Conformance Class incorporates the capabilities to support the Read of STAplus entities via HTTP. It also includes the Default-CRS Requirements Class to ensure interoperability with geometry encodings in the `feature` and `location` properties.

* *Create* (optional): This Conformance Class supports del:[to create] add:[creating] STAplus entities via HTTP.

* *Update* (optional): This Conformance Class supports del:[to update] add:[updating] STAplus entities via HTTP.

* *Delete* (optional): This Conformance Class supports del:[to delete] add:[deleting] STAplus entities via HTTP.

* *Authentication* (optional): This Conformance Class supports user authentication and their unique identification.

* *Geometry-FG* (optional): This Conformance Class supports the alternative geometry encoding for the `feature` and `location` properties based on Features and del:[their Geometries] add:[Geometries JSON as defined in <<OGC21-045r1>>].

* *Geometry-WKT* (optional): This Conformance Class supports the alternative geometry encoding for the `feature` and `location` properties based on Well del:[] add:[-]Known Text (WKT) as defined in <<ISO19125-1>>.

* *MQTT Subscribe STA v1.0* (optional): This Conformance Class supports a client to receive STAplus entity changes via MQTT as defined in <<OGC15-078r6>>.

* *MQTT Subscribe STA v1.1* (optional): This Conformance Class supports a client to receive STAplus entity changes via MQTT as defined in <<OGC18-088>>.

* *Business Logic* (optional): This Conformance Class del:[supports] add:[requires] that the implementation's business logic is described in English text to help developers understand the details of CRUD access. add:[It includes the GDPR compliance note that `Location` and `HistoricalLocation` of a `Thing` owned by a `Party` whose `role` is equal to `individual` are personal data and are restricted to that party. It also includes the License attribution note that system `License` entities are templates, that a non-attribution license uses the template as-is, that each use of an attribution license is a party-specific instance with `attributionText` filled, that creator identification is always that `attributionText`, that `Party/displayName` and `Party/authId` are not used as creator identification, and that a personal name in `attributionText` of an individual party is personal data.]

[[service-root-advertisement]]
==== Advertisement on the service root URI

add:[This subsection is informative. It collects the advertisements that existing requirements of this Standard already place on the SensorThings service root URI. It does not define a Landing Page Requirements Class or Conformance Class.]

add:[The service root URI is the SensorThings landing page. SensorThings API 1.1 advertises claimed conformance class URIs in the `conformance` array of the `serverSettings` object. An implementation that claims STAplus conformance classes on a SensorThings API 1.1 endpoint includes the identifiers of those classes in that array. SensorThings API 1.0 does not define `serverSettings`; this Standard nevertheless uses that object for the Geometry-WKT and Business Logic advertisements.]

add:[The following table lists, for each STAplus Conformance Class, the additional information that class requires on the service root URI when the class is claimed. The accepted geometry `encodingType` ValueCodes follow from the claimed geometry classes (`application/geo+json` for Core and Geometry-FG, `application/wkt` for Geometry-WKT). This Standard does not require those ValueCodes to be listed as a separate array on the service root URI.]

[[tab-service-root-advertisement]]
.Advertisements on the service root URI by claimed Conformance Class
[cols="3a,4a",options="header,unnumbered"]
|===
|Conformance class |Advertisement on the service root URI

|Core +
`{identifier}/conf/core`
|The STAplus entity sets (`Parties`, `Licenses`, `ObservationGroups`, `Relations`, `Campaigns`) in the SensorThings `value` array. Default-CRS `{CRS84}` and `encodingType` `application/geo+json` follow from the Default-CRS Requirements Class.

|Create +
`{identifier}/conf/create`
|None beyond claiming the class.

|Update +
`{identifier}/conf/update`
|None beyond claiming the class.

|Delete +
`{identifier}/conf/delete`
|None beyond claiming the class.

|Authentication +
`{identifier}/conf/authentication`
|None beyond claiming the class.

|Geometry-FG +
`{identifier}/conf/geometry-fg`
|The default-CRS and the list of supported CRS, advertised on the conformance page (the service root URI).

|Geometry-WKT +
`{identifier}/conf/geometry-wkt`
|A JSON object in `serverSettings` with the name `{identifier}/conf/geometry-wkt`, containing `default-crs` and `supported-crs`.

|MQTT Subscribe STA v1.0 +
`{identifier}/conf/mqtt-subscribe-sta-10`
|None beyond claiming the class.

|MQTT Subscribe STA v1.1 +
`{identifier}/conf/mqtt-subscribe-sta-11`
|None beyond claiming the class.

|Business Logic +
`{identifier-corrigendum}/conf/business-logic`
|A JSON object in `serverSettings` with the name `{identifier-corrigendum}/conf/business-logic`, containing `href` whose value is the URL of the HTML page that describes the business logic, including the GDPR compliance note and the License attribution note.
|===

[%unnumbered]
.Example `serverSettings` on the service root URI
====
[source,json,options="unnumbered"]
----
{
  "conformance": [
    "http://www.opengis.net/spec/sensorthings-staplus/1.0/conf/core",
    "http://www.opengis.net/spec/sensorthings-staplus/1.0/conf/geometry-wkt",
    "http://www.opengis.net/spec/sensorthings-staplus/1.0.1/conf/business-logic"
  ],
  "http://www.opengis.net/spec/sensorthings-staplus/1.0/conf/geometry-wkt": {
    "default-crs": "urn:ogc:def:crs:OGC::CRS84",
    "supported-crs": [
      "urn:ogc:def:crs:OGC::CRS84"
    ]
  },
  "http://www.opengis.net/spec/sensorthings-staplus/1.0.1/conf/business-logic": {
    "href": "https://example.org/staplus/business-logic.html"
  }
}
----
====

[[conformance_class_core]]
==== Conformance Class *Core*

The `Core` Conformance Class is defined as follows:
[conformance_class]
.Core
====
[%metadata]
identifier:: {identifier}/conf/core
target:: {identifier}/req-class/entity-control-information
target:: {identifier}/req-class/party
target:: {identifier}/req-class/license
target:: {identifier}/req-class/group
target:: {identifier}/req-class/relation
target:: {identifier}/req-class/campaign
target:: {identifier}/req-class/read
target:: {identifier}/req-class/default-crs

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/core/common-control-information
conformance-test:: {identifier}/conf/core/entities
conformance-test:: {identifier}/conf/core/read
conformance-test:: {identifier}/conf/core/default-crs/crs-definition
conformance-test:: {identifier}/conf/core/default-crs/axis-order
conformance-test:: {identifier}/conf/core/default-crs/media-type
conformance-test:: {identifier}/conf/core/default-crs/processing
====

==== Conformance Class *Create*

The `Create` Conformance Class is defined as follows:
[conformance_class]
.Create
====
[%metadata]
identifier:: {identifier}/conf/create
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/create

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/create/http
====

==== Conformance Class *Update*

The `Update` Conformance Class is defined as follows:
[conformance_class]
.Update
====
[%metadata]
identifier:: {identifier}/conf/update
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/update

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/update/put
conformance-test:: {identifier}/conf/update/patch
====

==== Conformance Class *Delete*

The `Delete` Conformance Class is defined as follows:
[conformance_class]
.Delete
====
[%metadata]
identifier:: {identifier}/conf/delete
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/delete

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/delete/entity
====

==== Conformance Class *Authentication*

The `Authentication` Conformance Class is defined as follows:
[conformance_class]
.Authentication
====
[%metadata]
identifier:: {identifier}/conf/authentication
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/authentication

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/authentication/id
conformance-test:: {identifier}/conf/authentication/id-create
conformance-test:: {identifier}/conf/authentication/id-read
conformance-test:: {identifier}/conf/authentication/id-update
conformance-test:: {identifier}/conf/authentication/id-delete
====

==== Conformance Class *Geometry-FG*

The `Geometry-FG` Conformance Class is defined as follows:
[conformance_class]
.Geometry-FG
====
[%metadata]
identifier:: {identifier}/conf/geometry-fg
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/geometry-fg

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/geometry-fg/media-type
conformance-test:: {identifier}/conf/geometry-fg/default-crs
conformance-test:: {identifier}/conf/geometry-fg/supported-crs
conformance-test:: {identifier}/conf/geometry-fg/crs-error
conformance-test:: {identifier}/conf/geometry-fg/processing
conformance-test:: {identifier}/conf/geometry-fg/out
====

==== Conformance Class *Geometry-WKT*

The `Geometry-WKT` Conformance Class is defined as follows:
[conformance_class]
.Geometry-WKT
====
[%metadata]
identifier:: {identifier}/conf/geometry-wkt
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/geometry-wkt

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/geometry-wkt/media-type
conformance-test:: {identifier}/conf/geometry-wkt/crs-definition
conformance-test:: {identifier}/conf/geometry-wkt/default-crs
conformance-test:: {identifier}/conf/geometry-wkt/supported-crs
conformance-test:: {identifier}/conf/geometry-wkt/crs-error
conformance-test:: {identifier}/conf/geometry-wkt/value
conformance-test:: {identifier}/conf/geometry-wkt/processing
conformance-test:: {identifier}/conf/geometry-wkt/out
====

==== Conformance Class *MQTT Subscribe* STA v1.0

The `MQTT Subscribe` STA v1.0 Conformance Class is defined as follows:
[conformance_class]
.MQTT Subscribe STA v1.0
====
[%metadata]
identifier:: {identifier}/conf/mqtt-subscribe-sta-10
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/mqtt-subscribe-sta-10

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/mqtt-subscribe-sta-10/definition
====

==== Conformance Class *MQTT Subscribe* STA v1.1

The `MQTT Subscribe` STA v1.1 Conformance Class is defined as follows:
[conformance_class]
.MQTT Subscribe STA v1.1
====
[%metadata]
identifier:: {identifier}/conf/mqtt-subscribe-sta-11
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/mqtt-subscribe-sta-11

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/mqtt-subscribe-sta-11/definition
====

==== Conformance Class *Business Logic*

The `Business Logic` Conformance Class is defined as follows:
[conformance_class]
.Business Logic
====
[%metadata]
identifier:: {identifier-corrigendum}/conf/business-logic
inherit:: {identifier}/conf/core
target:: {identifier-corrigendum}/req-class/business-logic

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/business-logic/definition
conformance-test:: {identifier}/conf/business-logic/location
conformance-test:: {identifier-corrigendum}/conf/business-logic/gdpr-note
conformance-test:: {identifier-corrigendum}/conf/business-logic/attribution
====