[[terms-and-definitions]]
== Terms, definitions and abbreviated terms

=== Terms and definitions

The terms and definitions of <<OGC22-022r2>> apply. The following terms are added by this Standard.

==== PartyLocation

The position of a `Party` at a given time. A `PartyLocation` is distinct from the SensorThings `Location` of a `Thing` and from the `FeatureOfInterest`.

==== PartyActivity

An activity performed by a `Party` at a given time, which may be associated with observations made while that activity took place.

==== Share

A grant from a `Party` (the grantor) to one or more other parties (the recipients) of a permission on exactly one `PartyLocation` or `PartyActivity`.

[abbreviations]
=== Abbreviated terms

API:: Application Programming Interface
CC:: Creative Commons
CRUD:: Create Read Update Delete
DID:: Decentralized Identifier
GDPR:: European General Data Protection Regulation
MQTT:: Message Queuing Telemetry Transport
O&M:: Observations and Measurements
STA:: SensorThings API
STAplus:: SensorThings API PLUS extension
