[obligation=informative]
== Introduction

The STAplus 1.0 Standard defines an extension to the OGC SensorThings API. This STAplus extension originally started with motivations and requirements from the Citizen Science community. However, the STAplus extension has wider applicability than just Citizen Science.

STAplus is a 100% backwards compatible extension to the STA data model of version 1.0 and 1.1 and as such can be added to existing STA deployments.

In addition to the data model extension, this Standard defines different concepts that support operating an implementation in a multi-user CRUD deployment.


===	Concept of Ownership
In Citizen Science, users participate in campaigns or projects, offered by different Citizen Science portals. These portals, typically operated by different organizations, have one feature in common: Contributions, uploaded by users are associated with the user and the ownership does not change. There is an explicit relationship between the observation (resource) and the user. Expressed as ownership, users can undertake certain actions on their resources.

With the SensorThings API (STA), observations are linked to a data stream that is linked to a sensor which belongs to a thing. The data model does not provide a class that supports explicitly linking a user (party) to an observation. This limits the use of the STA data model (and API) to a simple use case: One operator can create data objects and all other users have read-only access. This limits the options for applications to interact with the API.

Even though the STA v1.1 data model offers the generic use of `properties`, expressing ownership (user association) buried in properties is not wise. Storing personal data in those `properties` makes compliance with the European General Data Protection Regulation (GDPR) difficult. This is because it is unclear if properties store personal data and therefore fall under GDPR. Also, this  decreases interoperability tremendously as an application developer would need to know which attribute can be used to express ownership. Also, querying observations based on unstructured properties is extremely complex and difficult.

Therefore, the STAplus extension defines the class Party for expressing the association from a `Datastream` or `MultiDatastream` to a user. All uploaded observations, associated to a `Datastream` instance belong to the party associated to the `Datastream`.

===	Improving F A I R
In general, there are many aspects when it comes to ensure reusability of (existing) data. Not only in the context of Citizen Science, one fundamental aspect is the licensing aspect. Very many users contribute to Citizen Science with the motivation to do meaningful things for the common good. At the same time, users like to be credited when it comes to re-use of their contribution(s). Therefore, most contributions in Citizen Science are freely accessible (open access) but the re-use is “open” but restrictions may apply. In order to get credited, users might associate a license like CC-BY (Creative Commons Attribution License). Even though the data is still freely accessible, there is a condition that must be followed as expressed in the license.

=== Licensing
Applying licensing is a difficult task. In particular in a deployment like Citizen Science, where users may decide which license gets applied to their contributions. Too many different and perhaps incompatible licenses exist which may risk a proper re-use. STAplus supports licensing in a flexible way by only demanding that a license has unique URI based identifier (`definition` property). Even though STAplus does not constraint which license types to use, an implementation should constraint the proliferation of licenses via the Business Logic. As illustrated in the <<OGC21-068>>, an implementation may create all `License` entities and disallow that users create own licenses. For the Creative Commons licensing framework, this leads to the existence of seven recommended licenses. This ensures a proper re-use as license compatibility can easily be computed. 

When it comes to attribution licenses, the re-use requires to provide a citation to name the original author. For the Creative Commons licensing framework, best practices exist that do not need any additional consideration in the STAplus data model. However, a user may want to be able to express an individual attribution to be used with the license. Such information - the actual attribution text - could be stored in the properties of the `License` entity. But this would require that the business logic allows creation of `License` entities. To make sure that still only a particular licensing framework can be used, the Business Logic could allow a user to create a `License` entity and store the individual citation into a property like `attributionText` but constrain the `definition` property to those URIs that include the attribution license building block. 

===	Creating Observation Groups
When contributing to Citizen Science, the relevant information is often a set or bag of individual observations that belong together - i.e. may belong to the same observation event. For example, a camera trap event consists of a picture, a textual observation expanding the likelihood of species prediction and sensor readings for environmental context (temperature, humidity, luminance, air pressure, GPS location). All of these (individual) observations could be grouped when created at the same time/location.

Another use case for applying grouping to existing observations is to create a package of observations for the purpose of building the fundamentals for research or to be used in workflows. For researching and later evaluation of a particular phenomenon, the same group of observations can be exchanged via the grouping concept.

Also, over time a user community might link other observations and even provide cross links to other databases. These can be semantically tagged with the `Relation` entity which is described later in this document.

The STAplus extension defines a flexible grouping concept by adding the `ObservationGroup` entity to the STA data model.

===	Expressing Relations 
For Citizen Science expressing relations between observations explicitly to support search based on these relations is important. While the STA `ObservedProperty` entity supports links to external resources, the `Observation` entity does not. The STAplus `Relation` entity adds external linking support to observations.

Therefore, the STAplus extension introduces the `Relation` entity that supports creating generic “– to” relation from an `Observation` entity. The “to” can point to another observation or to an external object. This allows the generic expression of meaning, leveraging existing semantic concepts that exist elsewhere, for example Dublin or Darwin Core. This helps to reason how observations are related even if they were not observed in a same observation event, but instead were linked later to a particular community process (as linking to other databases).

The use of Relations as defined in STAplus can be applied to already existing SensorThings deployments to enrich the data towards semantics. 
 
=== Data Model Extension
The STAplus data model extension allows expressing the following additional characteristics:

- **P**eople: The `Party` entity supports linking a user to a `Datastream`, `MultiDatastream`, `Campaign` or `ObservationGroup`
- **L**icense: The `License` entity supports expressing reuse conditions by linking a `License` to a `Datastream` and / or to a `ObservationGroup`. A `License` on a `Datastream` has the result that all `Observation` entities of that `Datastream` (as well as entities of the `Thing`, `Sensor` and `ObservedProperty`) have the associated license. A `License` on a `ObservationGroup` gives the bag or set of `Observations` (represented by the `ObservationGroup`) a license for reuse. Note that still the license for each `Observation` must still be followed.
- **U**nion: The `ObservationGroup` entity supports packaging individual `Observations` as a bag or set either as deep copy or via linking
- **S**emantics: The `Relation` entity supports expressing relationships between `Observation` entities using the “from-to” type. It is also possible to create relations between `Observation` entities and external objects using the URI scheme. This allows in particular to express a relation to any entity of the database (via their external URI). `Relation` entities can exist on its own or be included into a ObservationGroup to enrich a bag or set of `Observation` entities.
- Campaign: The `Campaign` entity is a container of `Datastream` and `MultiDatastream` entities that supports organizing a campaign or project and to provide metadata as well as legal information such as terms of use and a privacy statement, in case it is relevant.