[[staplus-foi-location]]
== STAplus Feature, Location and PartyLocation Geometry Encoding Requirements


=== Overview

The Default-CRS, Geometry-FG, and Geometry-WKT Requirements Classes of <<OGC22-022r2>> apply to the `feature` property of `FeatureOfInterest` and to the `location` property of `Location`. This Standard extends those Requirements Classes so that they also apply to the `position` property of `PartyLocation`. The supported `encodingType` ValueCodes are advertised as specified in <<encoding-type>>.

[[CRS]]
=== Default-CRS Requirements Class

This Requirements Class extends the Default-CRS Requirements Class of <<OGC22-022r2>> to `PartyLocation/position`.

[requirements_class]
.Default-CRS

====
[%metadata]
identifier:: {identifier}/req-class/default-crs
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier-101}/req-class/default-crs
inherit:: <<GeoJSON>>
requirement:: {identifier}/req/default-crs/crs-definition
requirement:: {identifier}/req/default-crs/axis-order
requirement:: {identifier}/req/default-crs/media-type
requirement:: {identifier}/req/default-crs/processing
====


[requirement]
====
[%metadata]
identifier:: {identifier}/req/default-crs/crs-definition

The STAplus implementation SHALL use the <<GeoJSON>> CRS `{CRS84}` as the default-CRS.
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/default-crs/axis-order

The STAplus implementation SHALL use the <<GeoJSON>> axis-order with the default-CRS.
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/default-crs/media-type

The STAplus implementation SHALL accept the media-type `application/geo+json` value for the `encodingType` property to indicate that the structuring of the `PartyLocation` entity geometry encoding is compliant with the RFC <<GeoJSON>>.
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/default-crs/processing

The STAplus implementation SHALL enforce the `default-CRS` to any geometry data contained in the `PartyLocation` entity. The STAplus implementation SHALL reject any geometry **not** encoded in the `default-CRS` without further processing.
====

[[GeometryFG]]
=== Geometry-FG Requirements Class

This Requirements Class extends the Geometry-FG Requirements Class of <<OGC22-022r2>> to `PartyLocation/position`.

[requirements_class]
.Geometry-FG

====
[%metadata]
identifier:: {identifier}/req-class/geometry-fg
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier-101}/req-class/geometry-fg
inherit:: <<OGC21-045r1>>
requirement:: {identifier}/req/geometry-fg/media-type
requirement:: {identifier}/req/geometry-fg/processing
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/geometry-fg/media-type

The STAplus implementation SHALL accept the media-type `application/vnd.ogc.fg+json` as value to the `encodingType` property of the `PartyLocation` entity to indicate that the structuring of the geometry is compliant with <<OGC21-045r1>>.
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/geometry-fg/processing

The Geometry-FG processing, CRS, and output requirements of <<OGC22-022r2>> SHALL also apply to the `position` property of a `PartyLocation` entity.
====

[[GeometryWKT]]
=== Geometry-WKT Requirements Class

This Requirements Class extends the Geometry-WKT Requirements Class of <<OGC22-022r2>> to `PartyLocation/position`.

[requirements_class]
.Geometry-WKT

====
[%metadata]
identifier:: {identifier}/req-class/geometry-wkt
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier-101}/req-class/geometry-wkt
inherit:: <<ISO19125-1>>
requirement:: {identifier}/req/geometry-wkt/media-type
requirement:: {identifier}/req/geometry-wkt/processing
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/geometry-wkt/media-type

The STAplus implementation SHALL accept the media-type `application/wkt` as value to the `encodingType` property of the `PartyLocation` entity to indicate that the structuring of the geometry is compliant with <<ISO19125-1>>.
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/geometry-wkt/processing

The Geometry-WKT processing, CRS, and output requirements of <<OGC22-022r2>> SHALL also apply to the `position` property of a `PartyLocation` entity.
====
