[[staplus-mqtt]]
== STAplus MQTT Requirements

The MQTT capability defined in this Standard del:[allows a client to receive changes to STAplus 1.1 entities via MQTT.] add:[allows a client to receive changes to `PartyLocation` and `PartyActivity` entities via MQTT.]

NOTE: The ability for the creation of observations via MQTT is inherited from the SensorThings API Part 1: Sensing and Sensing v1.1 Standard.

=== Overview

In the context of MQTT, del:[the STAplus 1.1 entities `PartyLocation` and `PartyActivity` are equivalent] add:[the entities `PartyLocation` and `PartyActivity` are equivalent] to the STA entities.del:[ If the implementation conforms to Conformance Class *Sharing Party Context*, the `Share` entity is also equivalent to the STA entities.] Therefore, the implementation of MQTT capabilities must be compliant with the SensorThings API Part 1: Sensing and Sensing v1.1 Standard.

[[mqtt-subscribe-10]]
=== Requirements Class *MQTT Subscribe* STA v1.0

[requirements_class]
.MQTT Subscribe STA v1.0

====
[%metadata]
identifier:: {identifier}/req-class/mqtt-subscribe-sta-10
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {staplus-10}/req-class/mqtt-subscribe-sta-10
inherit:: http://www.opengis.net/spec/iot_sensing/1.0/req/receive-updates-via-mqtt
requirement:: {identifier}/req/mqtt-subscribe-sta-10
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/mqtt-subscribe-sta-10

del:[For the entities defined in STAplus 1.1,] add:[For the entities defined in this Standard,] a STAplus implementation SHALL support receiving entity updates with MQTT Subscribe as defined in http://www.opengis.net/spec/iot_sensing/1.0/req/receive-updates-via-mqtt.
====

[[mqtt-subscribe-11]]
=== Requirements Class *MQTT Subscribe* STA v1.1

[requirements_class]
.MQTT Subscribe STA v1.1

====
[%metadata]
identifier:: {identifier}/req-class/mqtt-subscribe-sta-11
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {staplus-10}/req-class/mqtt-subscribe-sta-11
inherit:: http://www.opengis.net/spec/iot_sensing/1.1/req/receive-updates-via-mqtt
requirement:: {identifier}/req/mqtt-subscribe-sta-11
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/mqtt-subscribe-sta-11

del:[For the entities defined in STAplus 1.1,] add:[For the entities defined in this Standard,] a STAplus implementation SHALL support receiving entity updates with MQTT Subscribe as defined in http://www.opengis.net/spec/iot_sensing/1.1/req/receive-updates-via-mqtt.
====
