[[http-interface-binding]]
== HTTP Interface Bindings

[[http_binding_introduction]]
=== Introduction

The HTTP Bindings specify how the abstract REST-API specified in the OGC SensorThings API is implemented over the HTTP protocol.


[requirements_class]
.HTTP Interface Bindings
====
[%metadata]
identifier:: {identifier}/req-class/binding/http
obligation:: requirement
subject:: Interface Binding
requirement:: {identifier}/req/binding/http/advertisement
requirement:: {identifier}/req/binding/http/request_response
====


[[http_binding_advertisement]]
=== HTTP Binding Advertisement

To help a client find the HTTP endpoints of a STA service, the endpoints of the service are documented in the `+serverSettings+` object of the service documents of all request-response bindings, as described in <<read_service_document>>.
If the service supports the HTTP interface binding, then the `+serverSettings+` object SHALL contain an attribute of type Object, with the name

`{identifier}/req/binding/http`

This Object SHALL contain an attribute named `+endpoints+` of type Array. The JSON Array `+endpoints+` SHALL hold a list of URL Schemes that can be used to connect to the HTTP service


[requirement]
.Binding Advertisement
====
[%metadata]
identifier:: {identifier}/req/binding/http/advertisement

If a service implements any HTTP bindings, then the HTTP endpoints of the service SHALL be advertised in the service documents of all implemented request-response bindings, as described in <<http_binding_advertisement>>.
====



[[http_request_response]]
=== Request / Response


The actions that can be executed on resources, as defined in the <<abstract_api>> are mapped to HTTP Methods as defined in table <<http-method-mapping>>.

[#http-method-mapping,reftext='{table-caption} {counter:table-num}']
.Mapping of abstract request types to HTTP Methods.
[width="80%",cols="<,<",options="header"]
|====
| *Request type*
| *HTTP Method*

| Read
| GET

| Create
| POST

| Update
| PATCH

| Replace
| PUT

| Delete
| DELETE

| Execute
| POST
|====

Content for Create, Update, Replace or Execute requests is passed in the body of the HTTP request.

Request parameters (such as `prefer`, `content-type` and `location`)  are passed as Headers.

HTTP HEAD and OPTIONS requests are treated as normal GET requests, but don't return data.
If a GET request with the same URL and headers would return an error, the HEAD or OPTION requests also returns this error.


[requirement]
.Request / Response
====
[%metadata]
identifier:: {identifier}/req/binding/http/request_response
inherit:: {identifier}/req-class/api/abstract

If a service advertises this requirement in the service document then the service SHALL map the request types as defined in the abstract STA API to HTTP methods as described in  <<http_request_response>>.
====



[[http_topic_discovery]]
=== WebSub Topic Discovery
This section defines the requirements for a STA HTTP interface supporting topic discovery as an extension to <<W3CWebSub>>. With supporting WebSub Topic Discovery, asynchronous messaging over HTTP(S) can be established that allow any client to receive notification data from a STA endpoint based on self-defined topics including ODATA query parameters. The use of self-defined notification topics is a great improvement over PubSub, where topics are static and published by providers. With support for WebSub Topic Discovery, any client can determine if a particular topic - expressed as a STA HTTP URL - can be used for subscribing to future notifications.

NOTE: As defined in <<W3CWebSub>>, building an Asynchronous Messaging System requires a WebSub Hub implementation that accepts subscriptions for self-discovered topics, subscribe to the STA MQTT broker and distribute the actual notifications to subscribed clients.


The `Discovery` requirements class is implemented at the STA service - HTTP interface to support the W3C WebSub discovery protocol. 

[[http_topic_discovery_req_class]]
[requirements_class]
.Discovery
====
[%metadata]
identifier:: {identifier}/req-class/binding/http/websub
subject:: Web API
inherit:: {identifier}/req/binding/http/request_response
requirement:: {identifier}/req/binding/http/websub/link-hub
requirement:: {identifier}/req/binding/http/websub/link-self
requirement:: {identifier}/req/binding/http/websub/link-help
requirement:: {identifier}/req/binding/http/websub/odata-support
requirement:: {identifier}/req/binding/http/websub/odata-discovery
requirement:: {identifier}/req/binding/http/websub/odata-blacklisting
requirement:: {identifier}/req/binding/http/websub/topics-discovery
requirement:: {identifier}/req/binding/http/websub/topics-blacklisting
====


[[http_link_header_hub]]
==== Link Header 'hub'
According to <<W3CWebSub>>, discovery always returns `<Link>; rel="hub"` in response to HTTP GET and HEAD requests.

[[http_link_header_hub_req]]
[requirement]
====
[%metadata]
identifier:: {identifier}/req/binding/http/websub/link-hub
part:: An implementation SHALL return the `<Link>; rel="hub"` HTTP header in response to HTTP GET and HEAD requests to indicate support for WebSub.
====



[[http_link_header_self]]
==== Link Header 'self'
According to <<W3CWebSub>>, discovery returns `<Link>; rel="self"` for a URL that is suitable for subscription.


[[http_link_header_req]]
[requirement]
====
[%metadata]
identifier:: {identifier}/req/binding/http/websub/link-self
part:: An implementation SHALL return the `<Link>; rel="self"` HTTP header in response to HTTP GET and HEAD requests to indicate the URL can be used for subscription.
part:: An implementation SHALL not return the `<Link>; rel="self"` HTTP header in response to HTTP GET and HEAD requests if the request URL either contains a denied topic or at least one denied ODATA option. In this case, the implementation SHALL return the `<Link>; rel="help"`.
part:: An implementation SHALL determine if a request URL is allowed for subscription by first converting the URL into an MQTT topic and test whether the topic is included in the `topics_denied`. If so, the implementation SHALL not return the `<Link>; rel="self"` but the `<Link>; rel="help"` HTTP header  in response to a GET or HEAD request.
part:: An implementation SHALL isolate the query string from the request URL and check if any of the ODATA options is listed in the `odata_denied`. If so, the implementation SHALL not return the `<Link>; rel="self"` but the `<Link>; rel="help"` HTTP header in response to a GET or HEAD request.
====



[[http_link_header_help]]
==== Link Header 'help'
Returning the `<Link>; rel="help"` header (specific to STA-WebSub) indicates the cause why the requested URL is not suitable for subscription.


[[http_link_header_help_req]]
[requirement]
====
[%metadata]
identifier:: {identifier}/req/binding/http/websub/link-help
part:: An implementation SHALL provide a URL for obtaining help (why the request URL cannot be used for subscription) when returning the `<Link>; rel="help"` header.
part:: An implementation SHALL use the `<Link>; rel="self"` and `<Link>; rel="help"` HTTP header mutually exclusive.
====



[[http_websub_odata_queries]]
==== ODATA query options support


[[http_websub_odata_queries_req]]
[requirement]
====
[%metadata]
identifier:: {identifier}/req/binding/http/websub/odata-support
part:: An implementation SHALL allow the discovery such that the associated MQTT topic is compliant to OGC SensorThings API v2.0 requirement regarding updates via MQTT with the following extensions:

* URI patterns that addresses an entity set (<<pattern_entityset>>, <<pattern_entityset_related>>) can be extended with a `?` followed by any valid combination of ODATA options that the server support, as defined in <<mqtt_pubsub_select>>, <<mqtt_pubsub_expand>> and <<mqtt_pubsub_filter>>.

* URI patterns that addresses an entity (<<pattern_entity>>, <<pattern_entity_related>>) can be extended with a `?` followed by any valid combination of ODATA options that the server support, as defined in <<mqtt_pubsub_select>>, <<mqtt_pubsub_expand>>.

* URI pattern that addresses a single entity attribute (<<pattern_entity_attribute>>).
====



[[http_websub_odata_advertisement]]
==== ODATA support advertisement


[[http_websub_odata_advertisement_req]]
[requirement]
====
[%metadata]
identifier:: {identifier}/req/binding/http/websub/odata-discovery
part:: An implementation SHALL advertise the support for ODATA query parameter by publishing the string `{identifier}/req/binding/http/websub` in the `serverSettings` section of the root page.

====



[[http_websub_odata_blacklisting]]
==== ODATA Blacklisting
A request URL may contain query parameters (after the `?`) presenting ODATA options. An implementation may deny discovery (and thereby later subscription) for certain ODATA options like `$expand` or `$filter`. 


[[http_websub_odata_blacklisting_req]]
[requirement]
====
[%metadata]
identifier:: {identifier}/req/binding/http/websub/odata-blacklisting
part:: An implementation SHALL advertise the existence of denied ODATA options by adding the following key to the root page: `{identifier}/req/binding/http/websub` that includes the key `odata_denied`. This key SHALL contain a JSON array for all denied ODATA options.
part:: In case no ODATA options are denied,an implementation SHALL advertise the non-existence of denied ODATA options by adding the following key to the root page: `{identifier}/req/binding/http/websub` that includes the key `odata_denied`. This key SHALL contain an empty JSON array.
====


.Example blacklisting structure for ODATA options.
[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings/2.0/req/binding/http/websub": {
            "odata_denied": <JSON Array of denied ODATA options>
        }
    }
}
----


.Example of a root page snippet indicating restrictions for `$expand`, `$skip`, `$top` and `$filter`
[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings/2.0/req/binding/http/websub": {
            "odata_denied": ["$expand", "$skip", "$top", "$filter"]
        }
    }
}
----


.Example of a root page snippet indicating **no** restrictions for ODATA options
[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings/2.0/req/binding/http/websub": {
            "odata_denied": []
        }
    }
}
----


[[http_websub_topic_blacklisting]]
==== Topics Blacklisting
The support for STA-WebSub can be determined from the root page as part of the `Discovery` conformance class.


[[http_websub_topic_blacklisting_req1]]
[requirement]
====
[%metadata]
identifier:: {identifier}/req/binding/http/websub/topics-discovery
part:: An implementation SHALL advertise the support for topics blacklisting by publishing the string `{identifier}/req/binding/http/websub` in the `serverSettings` section of the root page that includes the key `topics_denied`.
====


.Example blacklisting structure for topics
[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings/2.0/req/binding/http/websub": {
            "topics_denied": <JSON Array of denied topics>
        }
    }
}
----



[[http_websub_topics_blacklisting_req2]]
[requirement]
====
[%metadata]
identifier:: {identifier}/req/binding/http/websub/topics-blacklisting
part:: A STA topic starts with an URI patterns that addresses an entity set (<<pattern_entityset>>, <<pattern_entityset_related>>).
part:: An implementation SHALL advertise the existence of denied topics by adding the following key to the root page: `{identifier}/req/binding/http/websub` that includes the key `topics_denied`. This key SHALL contain a JSON array listing all denied topics.
part:: In case no topics are denied, an implementation SHALL advertise the non-existence of denied topics by adding the following key to the root page: `{identifier}/req/binding/http/websub` that includes the key `topics_denied`. This key SHALL contain an empty JSON array.
====


.Example of a root page snippet indicating deny for the topics `v2.0/Observations` and `v2.0/Datastreams('very chatty')/Observations`

[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings/2.0/req/binding/http/websub": {
            "topics_denied": ["v2.0/Observations", "v2.0/Datastreams('very chatty')/Observations"]
        }
    }
}
----


.Example of a root page snippet indicating **no** deny for topics

[source,json]
----
{
    "serverSettings": {
        "http://www.opengis.net/spec/sensorthings/2.0/req/binding/http/websub": {
            "topics_denied": []
        }
    }
}
----

