== Terms and definitions

This document uses the terms defined in Sub-clause 5.3 of <<OGC06-121r9>>, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== Party

The entity in the data model that represents a user. A party can be associated to other entities of the data model to express ownership.

=== License

The entity in the data model that represents a well-defined license. Associating a license with a `Multi/Datastream` entity expresses re-use conditions for all observations associated with that `Multi/Datastream` entity.

=== Group

The entity in the data model that allows creation a collection of observations for a particular purpose.

=== Relation

The entity in the data model that allows expressing relationships between two observations or an observation and an external object.

=== Project

The entity in the data model that allows merging `Multi/Datastream` entities together that are required to achieve the objective represented by the project.

=== Ownership

The `Party` entity in the data model allows expressing the right of possession over entity instances. This is the requirement to operate STAplus with multi-user CRUD access. 