[[staplus-entities]]
== STAplus Entity Type Requirements

`PartyLocation` and `PartyActivity` are the STAplus 1.1 entity types of the <<conformance_class_party_context>> Conformance Class. `Party`, `License`, `ObservationGroup`, `Relation`, and `Campaign` remain as defined in <<OGC22-022r2>>. The optional `Share` entity is defined in the <<conformance_class_sharing_party_context>> Conformance Class.

This clause also defines the additional direct relations from `Observation` and `Party` that STAplus 1.1 adds. If the implementation conforms to <<conformance_class_sharing_party_context>>, a `Party` also has `Shares` and `ReceivedShares`, and a `PartyLocation` and a `PartyActivity` also have `Shares`. Those relations are defined in Requirement Class <<share>>.

NOTE: Please be aware that all of the Requirements Classes in this section are part of the Conformance Class <<conformance_class_party_context>>.

[[common-control-information]]
=== Requirements Class *Entity Control Information*

NOTE: For more information, please see https://docs.ogc.org/is/18-088/18-088.html#common-control-information[<<OGC18-088, OGC SensorThings API Part 1: Sensing Version 1.1, §8.1>>].

[requirements_class]
.Entity Control Information

====
[%metadata]
identifier:: {identifier}/req-class/entity-control-information
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier-101}/req-class/entity-control-information
inherit:: <<OGC15-078r6>> or <<OGC18-088>>
requirement:: {identifier}/req/common-control-information
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/common-control-information

Each STAplus 1.1 entity SHALL have the common control information defined in <<OGC22-022r2>>.
====

[[party-location]]
=== Requirements Class *PartyLocation*

The `PartyLocation` entity records the position of a `Party`. It is used to associate observations with the observer's position. That position is not the SensorThings `Location` of a `Thing` and is not the `FeatureOfInterest`. The `time` property is the time instant or time period when the party was at that position.

The `position` property uses the same encoding rules as `Location/location` and `FeatureOfInterest/feature` in <<OGC22-022r2>>. The `encodingType` property indicates the encoding. The optional `retentionTime` is the time until which the entity is retained. The optional `restricted` property, when true, limits access to the linked `Party` as specified in the Personal Data Lifecycle Requirements Class.

[requirements_class]
.PartyLocation

====
[%metadata]
identifier:: {identifier}/req-class/party-location
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier}/req-class/entity-control-information
requirement:: {identifier}/req/party-location/properties
requirement:: {identifier}/req/party-location/relations
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/party-location/properties

Each `PartyLocation` entity SHALL have the mandatory properties and MAY have the optional properties listed in <<tab-properties-party-location>>.
====

[[tab-properties-party-location]]
.Properties of a `PartyLocation` entity
[cols="20a,45a,20a,15a"]
|===
|Name |Definition |Data type |Cardinality and use

|position
|The geographic position of the party
|Any
|One (mandatory)

|encodingType
|The encoding type of the `position` property. The value is one of the media types listed in <<media-types>>. The implementation advertises the supported values as specified in <<OGC22-022r2>> and <<encoding-type>>
|CharacterString (ValueCode)
|One (mandatory)

|environment
|A code that classifies the observing environment. This Standard does not constrain the code list. An implementation can constrain values through its Business Logic. The implementation advertises the accepted values as specified in <<environment>>
|CharacterString (EnvCode)
|One (mandatory)

|positionalUncertainty
|The uncertainty of the `position` value, in metres
|float
|Zero or One (optional)

|elevation
|The elevation of the party, in metres
|float
|Zero or One (optional)

|elevationUncertainty
|The uncertainty of the `elevation` value, in metres
|float
|Zero or One (optional)

|time
|The time instant or time period when the party was at the `position`
|TM_Object
|One (mandatory)

|retentionTime
|The time until which the entity is retained. If this property is absent, the entity remains until it is deleted. If the current time is not before `retentionTime`, the GDPR Conformance Class requires the entity to be deleted.
|TM Instant
|Zero or One (optional)

|restricted
|When true, only the linked `Party` may access the entity, and a `Share` of the entity is not valid. If this property is absent, the implementation treats it as false.
|Boolean
|Zero or One (optional)

|===

[requirement]
====
[%metadata]
identifier:: {identifier}/req/party-location/relations

An implementation SHALL allow each `PartyLocation` to have direct associations to other entity types listed in <<tab-relations-from-party-location>> and <<tab-relations-to-party-location>>.
====

[[tab-relations-from-party-location]]
.Direct relation from a `PartyLocation` entity to other entity types
[cols="25a,25a,20a,30a"]
|===
|Relation name| Entity type |Cardinality |Description

|Party
|Party
|One
|A `PartyLocation` has one `Party`.

|Observations
|Observation
|Zero to Many
|A `PartyLocation` has zero-to-many `Observations`.

|PartyActivities
|PartyActivity
|Zero to Many
|A `PartyLocation` has zero-to-many `PartyActivities`.
|===

[[tab-relations-to-party-location]]
.Direct relation from a SensorThings or STAplus entity type to `PartyLocation`
[cols="25a,25a,20a,30a"]
|===
|Relation name| Source Entity type |Cardinality |Description

|PartyLocation
|Observation
|Zero or One
|An `Observation` has zero-to-one `PartyLocation`.

|PartyLocations
|Party
|Zero to Many
|A `Party` has zero-to-many `PartyLocations`.

|PartyLocations
|PartyActivity
|Zero to Many
|A `PartyActivity` has zero-to-many `PartyLocations`.
|===

[[party-activity]]
=== Requirements Class *PartyActivity*

The `PartyActivity` entity records an activity performed by a `Party`. It is used to associate observations with what the party was doing. The `definition` property is a URI that identifies the activity type. The `time` property is a time instant or a time period. The optional `retentionTime` is the time until which the entity is retained. The optional `restricted` property, when true, limits access to the linked `Party` as specified in the Personal Data Lifecycle Requirements Class.

[requirements_class]
.PartyActivity

====
[%metadata]
identifier:: {identifier}/req-class/party-activity
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier}/req-class/entity-control-information
requirement:: {identifier}/req/party-activity/properties
requirement:: {identifier}/req/party-activity/relations
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/party-activity/properties

Each `PartyActivity` entity SHALL have the mandatory properties and MAY have the optional properties listed in <<tab-properties-party-activity>>.
====

[[tab-properties-party-activity]]
.Properties of a `PartyActivity` entity
[cols="20a,45a,20a,15a"]
|===
|Name |Definition |Data type |Cardinality and use

|definition
|A URI that identifies the type of activity
|URI
|One (mandatory)

|time
|The time instant or time period of the activity
|TM_Object
|One (mandatory)

|name
|A name for the activity
|CharacterString
|One (mandatory)

|description
|A short description of the activity
|CharacterString
|Zero or One (optional)

|retentionTime
|The time until which the entity is retained. If this property is absent, the entity remains until it is deleted. If the current time is not before `retentionTime`, the GDPR Conformance Class requires the entity to be deleted.
|TM Instant
|Zero or One (optional)

|restricted
|When true, only the linked `Party` may access the entity, and a `Share` of the entity is not valid. If this property is absent, the implementation treats it as false.
|Boolean
|Zero or One (optional)

|===

[requirement]
====
[%metadata]
identifier:: {identifier}/req/party-activity/relations

An implementation SHALL allow each `PartyActivity` to have direct associations to other entity types listed in <<tab-relations-from-party-activity>> and <<tab-relations-to-party-activity>>.
====

[[tab-relations-from-party-activity]]
.Direct relation from a `PartyActivity` entity to other entity types
[cols="25a,25a,20a,30a"]
|===
|Relation name| Entity type |Cardinality |Description

|Party
|Party
|One
|A `PartyActivity` has one `Party`.

|Observations
|Observation
|Zero to Many
|A `PartyActivity` has zero-to-many `Observations`.

|PartyLocations
|PartyLocation
|Zero to Many
|A `PartyActivity` has zero-to-many `PartyLocations`.
|===

[[tab-relations-to-party-activity]]
.Direct relation from a SensorThings or STAplus entity type to `PartyActivity`
[cols="25a,25a,20a,30a"]
|===
|Relation name| Source Entity type |Cardinality |Description

|PartyActivity
|Observation
|Zero or One
|An `Observation` has zero-to-one `PartyActivity`.

|PartyActivities
|Party
|Zero to Many
|A `Party` has zero-to-many `PartyActivities`.

|PartyActivities
|PartyLocation
|Zero to Many
|A `PartyLocation` has zero-to-many `PartyActivities`.
|===

[[observation-relations]]
=== Requirements Class *Observation and Party relations*

STAplus 1.1 extends the SensorThings `Observation` entity and the STAplus `Party` entity with the navigation properties defined in <<tab-relations-observation-11>> and <<tab-relations-party-11>>. The `Party` relations defined in <<OGC22-022r2>> remain in force.

[requirements_class]
.Observation and Party relations

====
[%metadata]
identifier:: {identifier}/req-class/observation-relations
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier}/req-class/party-location
inherit:: {identifier}/req-class/party-activity
requirement:: {identifier}/req/observation/relations
requirement:: {identifier}/req/party/relations
requirement:: {identifier}/req/party-context/individual-gdpr
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/observation/relations

An implementation SHALL allow each `Observation` to have the direct associations listed in <<tab-relations-observation-11>>.
====

[[tab-relations-observation-11]]
.Direct relation from an `Observation` entity to STAplus 1.1 entity types
[cols="25a,25a,20a,30a"]
|===
|Relation name| Entity type |Cardinality |Description

|PartyLocation
|PartyLocation
|Zero or One
|An `Observation` has zero-to-one `PartyLocation`.

|PartyActivity
|PartyActivity
|Zero or One
|An `Observation` has zero-to-one `PartyActivity`.
|===

[requirement]
====
[%metadata]
identifier:: {identifier}/req/party/relations

In addition to the `Party` relations defined in <<OGC22-022r2>>, an implementation SHALL allow each `Party` to have the direct associations listed in <<tab-relations-party-11>>.
====

[[tab-relations-party-11]]
.Additional direct relation from a `Party` entity to STAplus 1.1 entity types
[cols="25a,25a,20a,30a"]
|===
|Relation name| Entity type |Cardinality |Description

|PartyLocations
|PartyLocation
|Zero to Many
|A `Party` has zero-to-many `PartyLocations`.

|PartyActivities
|PartyActivity
|Zero to Many
|A `Party` has zero-to-many `PartyActivities`.
|===

[requirement]
====
[%metadata]
identifier:: {identifier}/req/party-context/individual-gdpr

If the implementation accepts a `Party` entity whose `role` is equal to `individual`, the implementation SHALL conform to <<conformance_class_gdpr>>.
====
