[bibliography]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

[NOTE]
====
References are to follow the Springer LNCS style, with the exception that optional information may be appended to references: DOIs are added after the date and web resource references may include an access date at the end of the reference in parentheses. See examples from Springer and OGC below.
====


* [[[STAv1.1, OGC 18-088]]]

* [[[OgcOMS, OGC 20-082r4]]]

* [[[IsoOMS, ISO 19156:2023]]]

* [[[ITU-T-Y.2060, ITU-T Y.2060]]]

* [[[ogc08-094,OGC 08-094r1]]]

* [[[ogc17-011,OGC 17-011r2]]]

* [[[SweCommon,OGC 24-014]]]

* [[[RFC6902,IETF RFC 6902]]]

* [[[ODATAP1,OASIS OData-Part1]]]

* [[[ODATAP2,OASIS OData-Part2]]]

* [[[ODATACSDL,OASIS OData-CSDL-JSON-v4.01]]]

* [[[MQTT50,OASIS mqtt-v5.0]]]

EDITOR: Check which of these are normative and which should go to the bibliography at the end.

* [[[Smith81,Identification of Common Molecular Subsequences]]],
_Identification of Common Molecular Subsequences_.
Smith, T.F., Waterman, M.S., J. Mol. Biol. 147, 195–197 (1981)

* [[[May06,ZIB Structure Prediction Pipeline]]],
_ZIB Structure Prediction Pipeline: Composing a Complex Biological Workflow through Web Services_.
May, P., Ehrlich, H.C., Steinke, T. In: Nagel, W.E., Walter,
W.V., Lehner, W. (eds.) Euro-Par 2006. LNCS, vol. 4128, pp. 1148–1158. Springer,
Heidelberg (2006)

* [[[Grid,The Grid]]], _The Grid: Blueprint for a New Computing Infrastructure._,
Foster, I., Kesselman, C.. Morgan Kaufmann, San Francisco (1999).

* [[[Czajkowski01,Grid Information Services for Distributed Resource Sharing]]],
_Grid Information Services for Distributed Resource Sharing._
Czajkowski, K., Fitzgerald, S., Foster, I., Kesselman, C. In: 10th IEEE International Symposium on High
Performance Distributed Computing, pp. 181–184. IEEE Press, New York (2001)

* [[[Foster02,The Physiology of the Grid]]],
_The Physiology of the Grid: an Open Grid Services Architecture for Distributed Systems Integration._
Foster, I., Kesselman, C., Nick, J., Tuecke, S. Technical report, Global Grid Forum (2002)
