[[http-interface-binding]]
== HTTP Interface Bindings

=== Introduction

The HTTP Bindings specify how access the SensorThings API using the HTTP protocol.


[requirements_class]
.HTTP Interface Bindings
====
[%metadata]
identifier:: {identifier}/req-class/binding/http
obligation:: requirement
subject:: Interface Binding
inherit:: {identifier}/req-class/datamodel/core
requirement:: {identifier}/req/binding/http/advertisement
requirement:: {identifier}/req/binding/http/request_response
====


[[http_binding_advertisement]]
=== HTTP Binding Advertisement

To help a client find the HTTP endpoints of a SensorThings service, the endpoints of the service are documented in the `+serverSettings+` object of the service documents of all request-response bindings, as described in <<read_service_document>>.
If the service supports the HTTP interface binding, then the `+serverSettings+` object SHALL contain a attribute of type Object, with the name

`{identifier}/req/binding/http`

This Object SHALL contain a attribute named `+endpoints+` of type Array. The JSON Array `+endpoints+` SHALL hold a list of URL Schemes that can be used to connect to the HTTP service


[requirement]
.Binding Advertisement
====
[%metadata]
identifier:: {identifier}/req/binding/http/advertisement

If a service implements any HTTP bindings, then the HTTP endpoints of the service SHALL be advertised in the service documents of all implemented request-response bindings, as described in <<http_binding_advertisement>>.
====



[[http_request_response]]
=== Request / Response


The actions that can be executed on resources, as defined in the <<abstract_api>> are mapped to HTTP Methods as defined in table <<http-method-mapping>>.

[#http-method-mapping,reftext='{table-caption} {counter:table-num}']
.Mapping of abstract request types to HTTP Methods.
[width="80%",cols="<,<",options="header"]
|====
| *Request type*
| *HTTP Method*

| Read
| GET

| Create
| POST

| Update
| PATCH

| Replace
| PUT

| Delete
| DELETE

| Execute
| POST
|====

Content for Create, Update, Replace or Execute requests is passed in the body of the HTTP request.

Request parameters (such as `prefer`, `content-type` and `location`)  are passed as Headers.

HTTP HEAD and OPTIONS requests are treated as normal GET requests, but don't return data.
If a GET request with the same URL and headers would return an error, the HEAD or OPTION requests also returns this error.


[requirement]
.Request / Response
====
[%metadata]
identifier:: {identifier}/req/binding/http/request_response
inherit:: {identifier}/req-class/api/abstract

If a service advertises this requirement in the service document then the service SHALL map the request types as defined in the abstract API to HTTP methods as described in  <<http_request_response>>.
====



=== Cross Origin Resource Sharing

=== Authentication & Authorization

