[preface]
== Preface

STAplus - OGC SensorThings API Extension: STAplus 1.0 - defines a SensorThings data model extension to improve FAIR principles when exchanging sensor data including licensing and ownership information. 

The STAplus extension is fully backwards compatible with the existing OGC SensorThings API Part 1: Sensing as well as Sensing Version 1.1 and thereby offers existing deployments an easy upgrade to STAplus.

This Standard is a corrigendum for STAplus 1.0. It is written as a replacement for STAplus 1.0 (OGC #22-022r1). All changes relative to STAplus 1.0 are summarized in Annex C.

[abstract]
== Abstract

This document is a corrigendum for STAplus 1.0. It replaces STAplus 1.0 (OGC #22-022r1).

The OGC SensorThings API Extension: STAplus 1.0 Standard specifies a backwards-compatible extension to the OGC Standard SensorThings API Part 1: Sensing and Sensing 1.1 data model.

The motivation for specifying this STAplus extension is based on requirements from the Citizen Science community.

The dominant use for the OGC SensorThings API data model and API can be coined with the use case “single authority provides sensor readings to consumers.” However, in Citizen Science there are many contributors (citizens) who – together – create the big picture with their observations.

The STAplus extension is designed to support a model in which observations are owned by different users. This results in requirements for the ownership concept. In addition to the ownership, users may express a license for ensuring proper reuse of their observations. The STAplus extension also supports expressing explicit relations between observations as well as between observations and external resources. Relations can enrich observations to enable future extensions supporting Linked Data, RDF and SPARQL. Observation group(s) allow the grouping of observations that belong together.

STAplus is an important contribution to the FAIR principles. It strengthens Interoperability through a common data model and API, and Reusability by enabling standards-based queries that can take licensing conditions into account when reusing other users’ observations. 

The STAplus Data Model and Business Logic also enriches existing deployments as the extension can be seamlessly added and thereby offers new capabilities to create and manage the “big picture” with multi-user capabilities.

The key work for crafting this OGC Standard (STAplus) was undertaken in the _Co-designed Citizen Observatories Services for the EOS-Cloud_ (Cos4Cloud) project, which received funding from the European Union’s Horizon 2020 research and innovation program and the _Enhancing Citizen Observatories for healthy, sustainable, resilient and inclusive cities_ (CitiObs) project, which received funding from the European Union’s Horizon Europe research and innovation program. Testing of this extension was done with data from the Framework biodiversity project, which received funding from the European Union’s Horizon 2020 research and innovation program.

The key work for crafting this OGC Standard corrigendum was undertaken in the European Union’s Horizon 2020 research and innovation program and the _Enhancing Citizen Observatories for healthy, sustainable, resilient and inclusive cities_ (CitiObs) project, which received funding from the European Union’s Horizon Europe research and innovation program. Testing of this corrigendum was done with data from the CitiObs project.

[[submitters]]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

.Submitters
[%autowidth,cols="3*"]
|===
|Name |Representing |OGC Member

|Andreas Matheus
|Secure Dimensions GmbH
|Yes

|Joan Maso
|Centre de Recerca Ecològica i Aplicacions Forestals (CREAF)
|Yes

|Hylke van der Schaaf
|Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.
|Yes

|===

[[contributors]]
== Contributors

.Contributors
[%autowidth,cols="3*"]
|===
|Name |Representing |OGC Member

|Katharina Schleidt
|DataCove e.U.
|Yes

|Kateryna Konieva
|Individual
|Yes

|Núria Julià Selvas
|CREAF
|Yes

|===
