== MQTT Interface Bindings

The MQTT Bindings specify how to access the SensorThings API using the MQTT 5.0 protocol (<<MQTT50>>).

=== Request / Response

MQTT 5.0 formalises a request-response pattern over the MQTT protocol (<<MQTT50,section="4.10">>) that allows the use of the REST API over the MQTT protocol.
See <<mqtt5-req-res>> for a basic overview of the request-response pattern in MQTT 5.0.

MQTT 5.0 also defines User Properties (<<MQTT50,section="3.3.2.3.7">>) that can be used to pass application-defined key-value pairs with a published message.

[[mqtt5-req-res]]
[plantuml, title='MQTT 5 request-response pattern', reftext='{figure-caption} {counter:figure-num}']
....
@startuml
  skinparam responseMessageBelowArrow true
  participant Client as client
  participant "MQTT5 Broker" as broker
  participant RequestHandler as rh

  == Setup RequestHandler ==
  rh -> broker: CONNECT
  rh <-- broker: CONNACK

  rh -> broker: SUBSCRIBE v2.0/requests
  rh <-- broker: ok

  == Setup Client ==

  client -> broker: CONNECT\nrequestResponseInformation=true
  client <-- broker: CONNACK\nResponseInformation:responses/userXyz

  client -> broker: SUBSCRIBE responses/userXyz
  client <-- broker: ok

  ...

  == Request-Response ==
  client -> broker: PUBLISH v2.0/request\ncorrelationData=123xyz\nresponseTopic=responses/userXyz
  client <-- broker: ok

  broker -> rh: PUBLISH v2.0/request\ncorrelationData=123xyz\nresponseTopic=responses/userXyz
  broker <-- rh: ok

  rh -> rh: handle request

  rh -> broker: PUBLISH responses/userXyz\ncorrelationData=123xyz\nrequest response
  rh <-- broker: ok

  broker -> client: PUBLISH responses/userXyz\ncorrelationData=123xyz\nrequest response
  broker <-- client: ok
@enduml
....

Using the basic request-response pattern, and the User Properties of MQTT 5.0, the abstract API defined in <<abstract_api>> can be implemented over the MQTT protocol.

- Requests are sent to the topic `v2.0/$request`.
- The URL, including query parameters, for the request is passed in the User Property named `url` (case-insensitive). The URL does not need to be URL-Encoded.
- The request type (<<request_types>>) is passed in the User Property named `type`.
- Headers (such as `content-type` and `location`) are passes as User Properties.
- Content is sent as the payload of the message.
- The request must contain a response topic that follows the `Response Information` passed by the broker.
- The request may contain correlation data to help the client associate the response to the request.
- all URLs pointing to the API start with the version of the API and contain no scheme, host or port.

To minimise the size of the returned payload, by default the json format is used with `metadata=none` (<<format_json>>).

EDITOR: Check if there really is no need to URL-Encode the url.

.Message requesting the service document
[source,text]
----
Topic: v2.0/$request
ResponseTopic: responses/userxyz
CorrelationData: 42
User Properties:
  url: v2.0
  type: read
  accept: */*
Payload: <empty>
----

.Response message to the previous read request
[source,text]
----
topic: responses/userxyz
CorrelationData: 42
User Properties:
  content-type: application/json;charset=UTF-8
Payload: <the service document>
----


.Message requesting the first thing, ordered by id
[source,text]
----
Topic: v2.0/$request
ResponseTopic: responses/userxyz
CorrelationData: 43
User Properties:
  url: v2.0/Things?$top=1&$orderby=id
  type: read
  accept: */*
Payload: <empty>
----

.Response message to the previous read request
[source,text]
----
topic: responses/userxyz
CorrelationData: 43
User Properties:
  content-type: application/json;charset=UTF-8
Payload:
{
  "value": [
    {
      "id": 1,
      "name": "Oven",
      "description": "This thing is an oven.",
      "properties": {
        "owner": "Ulrike Schmidt",
        "color": "Black"
      }
    }
  ],
  "@nextLink": "v2.0/Things?$top=1&$skip=1&$orderby=id"
}
----



.Message creating a new thing
[source,text]
----
Topic: v2.0/$request
ResponseTopic: responses/userxyz
User Properties:
  url: v2.0/Things
  type: create
  content-type: application/json
  accept: */*
Payload:
{
  "id": 1,
  "name": "Oven",
  "description": "This thing is an oven.",
  "properties": {
    "owner": "Ulrike Schmidt",
    "color": "Black"
  }
}
----

.Response message to the previous create request
[source,text]
----
topic: responses/userxyz
User Properties:
  content-type: application/json;charset=UTF-8
  location: v2.0/Things(1)
Payload: <empty>
----




=== Publish / Subscribe

MQTT subscriptions are allowed on EntitySets (<<pattern_entityset>>, <<pattern_entityset_related>>), individual entities (<<pattern_entity>>, <<pattern_entity_related>>), and individual entity attributes (<<pattern_entity_property>>).

To get all updates for an EntitySet or Entity, clients can subscribe to the topic that matches the plain URL pattern, without service root, and without a preceding slash (`/`).

When an entity or attribute is created, updated/replaced or deleted, that is relevant for the subscription, the service returns a complete JSON representation of the affected entity in the payload of the message.

The action that caused the notification is specified in the user property named `type`, with a value of `create`, `update` or `delete`.
Replace actions are published with the type `update`.


.Topic to use for receiving all updates for the Observations of a specific Datastream, and a typical message notifying about the creation of a new Observation
[source,text]
----
v2.0/Datastreams(4)/Observations

User Properties:
  type: create
payload:
{
  "id": 123,
  "result": 45,
  "phenonmenonTime": "2015-02-05T17:00:00Z"
}
----


To only get updates for certain actions on an EntitySet or Entity, clients can subscribe to the topic that matches the plain URL pattern, without service root, and without a preceding slash (`/`), followed by a slash (`/`) and one of the actions `create`, `update`, `delete`.

.Topic to use for receiving notifications for the creation of new Observations in a specific Datastream
[source,text]
----
v2.0/Datastreams(4)/Observations/create
----




Since OData URLs are recursive, MQTT wildcards (`#` and `+`) are not allowed in subscriptions in the SensorThings topic tree.

Like HTTP URLs, MQTT topic in the SensorThings API can be extended with query options.
Query options are separated from the topic with a question mark character (`?`) and separated using an ampersant (`&`).
Query options are listed below.


==== $select

The $select query option (<<select>>) can be added to topics to reduce the amount of data that is sent.

.Topic to use for receiving all updates for the Observations of a specific Datastream, limited to only the phenomenonTime and result attributes
[source,text]
----
v2.0/Datastreams(4)/Observations?$select=phenomenonTime,result
----


==== $expand (optional)

The $expand query option (<<expand>>) can be added to topics to indicate that certain entities related to the created or updated entity should be sent.
This can, for instance, be useful when dealing with moving sensors, to receive new Observations together with their ProximateFeatureOfInterest.

.Topic to use for receiving all updates for the Observations of a specific Datastream
[source,text]
----
v2.0/Datastreams(4)/Observations?$expand=ProximateFeatureOfInterest
----


==== $filter (optional)

The $filter query option (<<filter>>) can be used to only receive notification of certain changes.



EDITOR: Do we need subscriptions on relations? On raw properties?

=== Authentication & Authorization
