[[staplus-mqtt]]
== STAplus MQTT Extension Requirements

The MQTT capabilities allows that a client to receive changes to STAplus entities via MQTT. 

=== Overview

NOTE: In the context of MQTT, all STAplus entities as defined in this Standard are equivalent to the STA entities. Therefore, the implementation of MQTT capabilities must be compliant with the SensorThings API Part 1: Sensing v1.0 and v1.1 Standard.

[[mqtt-subscribe-10]]
=== Requirements Class *MQTT Subscribe* STA v1.0

[requirements_class]
.MQTT Subscribe STA v1.0


====
[%metadata]
identifier:: {identifier}/req-class/mqtt-subscribe-sta-10
obligation:: requirement
subject:: Target Type: Web Service
inherit:: http://www.opengis.net/spec/iot_sensing/1.0/req/receive-updates-via-mqtt
requirement:: {identifier}/req/mqtt-subscribe-sta-10
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/mqtt-subscribe-sta-10

A STAplus implementation SHALL support the receiving of STAplus entity updates with MQTT Subscribe as defined in  http://www.opengis.net/spec/iot_sensing/1.0/req/receive-updates-via-mqtt.
====

[[mqtt-subscribe-11]]
=== Requirements Class *MQTT Subscribe* STA v1.1

[requirements_class]
.MQTT Subscribe STA v1.1

====
[%metadata]
identifier:: {identifier}/req-class/mqtt-subscribe-sta-11
obligation:: requirement
subject:: Target Type: Web Service
inherit:: http://www.opengis.net/spec/iot_sensing/1.1/req/receive-updates-via-mqtt
requirement:: {identifier}/req/mqtt-subscribe-sta-11
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/mqtt-subscribe-sta-11

A STAplus implementation SHALL support the receiving of STAplus entity updates with MQTT Subscribe as defined in http://www.opengis.net/spec/iot_sensing/1.1/req/receive-updates-via-mqtt.
====
