[[url-patterns]]
=== URL Patterns

==== Introduction

URL Patterns as defined in the SensorThings API Standard consist of four parts: the Service Root, the STA API version number, the resource path and query options.

The service root URL:: the free to chose base path of the service.
The API version number:: encoded as: `"v" + majorversionnumber + "." + minorversionnumber`.
The resource path:: consists of zero to many parts separated by the slash (`/`) character.
Resource paths are case sensitive.
The query options:: start with a question mark (`?`) character.
At the top level, query options are separated with the ampersant (`&`) character.

.Complete URL example using HTTP bindings
[source,text]
----
http://example.org/v2.0/Datastreams(5)/Observations?$orderby=ID&$top=10
__________________/____/__________________________/___________________/
         |          |                |                      |
   service root   version      resource path           query options
----

.Complete URL example using MQTT bindings
[source,text]
----
base/topic/v2.0/Datastreams(5)/Observations?$orderby=ID&$top=10
__________/____/__________________________/___________________/
    |     version            |                      |
root Topic             resource path           query options
----


[[pattern_service_document]]
==== Service Document

URL Pattern: `<Service Root>/v2.0`

The URL pattern consisting of just the version number, optionally followed by a slash (`/`), addresses the service document.
The service document content is described in <<read_service_document>>.


[[pattern_service_metadata_document]]
==== Service Metadata Document

URL Pattern: `<Service Root>/v2.0/$metadata`

The URL pattern consisting of the STA API version number followed by `/$metadata` addresses the service metadata document that describes the data model that the service exposes.
The service metadata document is described in <<OData-CSDL>>.


[[pattern_entityset]]
==== Entity Set

URL Pattern: `<Service Root>/v2.0/EntityTypeName`

The URL pattern consisting of the STA API version number followed by `/` and the name of an entity type addresses the set of all entities of the requested type.

.Resource pattern for the Datastreams Entity Set
[source,text]
----
<Service Root>/v2.0/Datastreams
----


[[pattern_entity]]
==== Entity

URL Pattern: `<Service Root>/v2.0/EntityTypeName(<primaryKey>)`

The URL pattern consisting of the name of an EntitySet URL, followed by, in brackets, a primary key value, addresses the single Entity from the set, that has the given primary key.


.Resource pattern for a specific Datastream, for a service that uses Integers for the id field of Datastreams
[source,text]
----
<Service Root>/v2.0/Datastreams(4)
----

.Resource pattern for a specific Datastream, for a service that uses Strings for the id field of Datastreams
[source,text]
----
<Service Root>/v2.0/Datastreams('xz42df')
----


[[pattern_entity_attribute]]
==== Entity Attribute

URL Pattern: `<Service Root>/v2.0/EntityTypeName(<primaryKey>)/entityAttribute`

The URL pattern consisting of a URL that addresses an Entity (the base entity), followed by an Entity Attribute, addresses the value of this Entity Attribute of the base Entity.
The used URL for the base entity may itself be a related entity URL.

.Resource pattern for the name of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/name
----

.Resource pattern for the name of the Thing of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Thing/name
----


[[pattern_entity_attribute_raw]]
==== Entity Attribute raw value ($value)

URL Pattern: `<Service Root>/v2.0/EntityTypeName(<primaryKey>)/entityAttribute/$value`

The URL pattern consisting of a URL that addresses an Entity (the base entity), followed by an Entity Attribute, followed by `/$value`, addresses the raw value of this Entity Attribute of the base Entity.
The URL used for the base entity may itself be a related entity URL.

.Resource pattern for the raw name of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/name/$value
----

.Resource pattern for the raw name of the Thing of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Thing/name/$value
----


[[pattern_entity_related]]
==== Related Entity

URL Pattern: `<Service Root>/v2.0/EntityTypeName(<primaryKey>)/EntityNavigationAttribute`

The URL pattern consisting of a URL that returns an Entity (the base entity), followed by a navigation attribute with a cardinality of one, addresses the related entity of the base entity.
The URL used for the base entity may itself be a related entity URL.


.Resource pattern for the Thing of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Thing
----

.Resource pattern for the Thing of the Datastream of a specific Observation
[source,text]
----
<Service Root>/v2.0/Observations(42)/Datastream/Thing
----


[[pattern_entityset_related]]
==== Related EntitySet

URL Pattern: `<Service Root>/v2.0/EntityTypeName(<primaryKey>)/EntitySetNavigationAttribute`

The URL pattern consisting of a URL that addresses an Entity (the base entity), followed by a navigation attribute with a cardinality of many, addresses the related EntitySet of the base entity.
The URL used for the base entity may itself be a related entity URL.

.Resource pattern for the Observations of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Observations
----

.Resource pattern for the Locations of the Thing of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Thing/Locations
----


[[pattern_relation]]
==== Association link ($ref)

URL Pattern: `<Service Root>/v2.0/EntityTypeName(<primaryKey>)/NavigationAttribute/$ref`

The URL pattern consisting of a URL that addresses an Entity (the base entity), followed by a navigation attribute, followed by `/$ref`, addresses the entity-id(s) of the related entity or entities of the given navigation attribute.

.Resource pattern for the association link of the Thing of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Thing/$ref
----

.Resource pattern for the association link to the Observations related to a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Observations/$ref
----

For navigation attributes with a cardinality of many, the navigation attribute may be followed by a primary-key in brackets, to address the specific association between the base entity and the related entity.

.Resource pattern for the association link between a specific Datastream and a specific Observation
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Observations(1)/$ref
----


==== Nested paths

URL Pattern: `<Service Root>/v2.0/EntityTypeName(<primaryKey>)/EntitySetNavigationAttribute(<primaryKey>)`

The pattern <<pattern_entityset_related>> and <<pattern_entity>> can be combined to address a specific entity from a related set.
This will return a `Not Found` error when the requested entity is not actually in the related set.

.Resource pattern for a specific Observation of a specific Datastream
[source,text]
----
<Service Root>/v2.0/Datastreams(4)/Observations(5321)
----

The above example addresses the same entity as `<Service Root>/v2.0/Observations(5321)`, except when Observation `5321` is not actually contained in Datastream `4`, since in that case any action on the resource would return a `Not Found` error.


[[request_types]]
=== Request Types

To the resources paths above the following request types can be sent:

Read:: Read data from the resource path.

Create:: Create a new Entity, or new Entities, at the resource path.

Update:: Change the Entity or Entities at the resource path.
Only the attributes present in the request are updated.

Replace:: Replace all the data of the resource with different data.

Delete:: Remove the resource.

Execute:: Execute an function on a resource.

NOTE: The `Execute` request type is not used in the core SensorThings API Standard but may be used in extensions.


[[additional_request_parameters]]
=== Additional request parameters

Besides the query options, there are a few other request parameters that are used to convey information between client and server.

Content-Type:: Used to indicate the type of content that is being transferred.

Prefer:: Analogous to <<RFC7240>>, used by a client to indicate how the server should respond to modification requests.

Location:: Used by the server to convey the self-link of a newly created entity.


