== Terms and definitions


=== WebSub

[quote, https://en.wikipedia.org/wiki/WebSub]
WebSub (formerly PubSubHubbub) is an open protocol for distributed publish–subscribe communication on the Internet.[1] Initially designed to extend the Atom (and RSS) protocols for data feeds, the protocol can be applied to any data type (e.g. HTML, text, pictures, audio, video) as long as it is accessible via HTTP. Its main purpose is to provide real-time notifications of changes, which improves upon the typical situation where a client periodically polls the feed server at some arbitrary interval. In this way, WebSub provides pushed HTTP notifications without requiring clients to spend resources on polling for change.


[NOTE]
====
In October 2017, PubSubHubbub was renamed to WebSub for simplicity and clarity. As of January 2018, the WebSub protocol has been adopted by the W3C as a Recommendation.
====

[.source]
https://en.wikipedia.org/wiki/WebSub

=== WebSub Publisher
[quote, https://www.w3.org/TR/websub/#x3-2-1-publisher]
an implementation that advertises a topic and hub URL on one or more resource URLs.

[.source]
https://www.w3.org/TR/websub/#x3-2-1-publisher

=== WebSub Subscriber
[quote, https://www.w3.org/TR/websub/#x3-2-2-subscriber]
an implementation that discovers the hub and topic URL given a resource URL, subscribes to updates at the hub, and accepts content distribution requests from the hub.

[.source]
https://www.w3.org/TR/websub/#x3-2-2-subscriber

=== WebSub Hub
[quote, https://www.w3.org/TR/websub/#x3-2-3-hub]
an implementation that handles subscription requests and distributes the content to subscribers when the corresponding topic URL has been updated.

[.source]
https://www.w3.org/TR/websub/#x3-2-3-hub

=== Topic URL
a URL used by a Subscriber when subscribing to a Hub. The SensorThings API service returns the topic URL in the HTTP Link header `<Link "topic URL">; rel="self"` for a request URL that is allowed for subscription.

=== MQTT Topic
a string used to subscribe to the MQTT broker for receiving update events. The MQTT topic is determined from the request URL.
