[bibliography]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

[NOTE]
====
References are to follow the Springer LNCS style, with the exception that optional information may be appended to references: DOIs are added after the date and web resource references may include an access date at the end of the reference in parentheses. See examples from Springer and OGC below.
====


* [[[STAv1.1, OGC 18-088]]]

* [[[OgcOMS, OGC 20-082r4]]]

* [[[IsoOMS, ISO 19156:2023]]]

* [[[ogc08-094,OGC 08-094r1]]]

* [[[ogc17-011,OGC 17-011r2]]]

* [[[ogc19-072,OGC 19-072]]]

* [[[SweCommon,OGC 24-014]]], SWE-Common, new version. Not yet publised, but expected soon.

* [[[RFC6902,IETF RFC 6902]]]

* [[[RFC7240,IETF RFC 7240]]]

* [[[RFC2818,IETF RFC 2818]]]

* [[[ODATAP1,OASIS OData-Part1]]]

* [[[ODATAP2,OASIS OData-Part2]]]

* [[[ODATACSDL,OASIS OData-CSDL-JSON-v4.01]]]

* [[[MQTT50,OASIS mqtt-v5.0]]]

* [[[OGC06-121r9, OGC 06-121r9]]]

* [[[ITU-T-Y.2060, ITU-T-Y.2060]]], ITU-T Y.2060: _Overview of the Internet of Things_, 2012. Available Online: https://www.itu.int/rec/t-rec-y.2060-201206-i

* [[[openapi,OpenAPI Specification]]], Open API Initiative: OpenAPI Specification. Available from https://spec.openapis.org/oas/.
