== STA-WebSub Requirements (normative)
The normative section of this OGC Standard is concerned with the discovery aspect as the standardization target is the SensorThings API service (HTTP interface). 

[NOTE]
====
Appendix B provides guidance for implementing a STA-WebSub Hub.
====

The STA-WebSub extension defines the following requirements classes: 

* Discovery Requirements Class (mandatory)
* Landing Page Requirements Class (mandatory)
* ODATA Requirements Class (optional)

=== Discovery Requirements Class (mandatory)
The `Discovery` requirements class (mandatory) is implemented at the SensorThings API service - HTTP interface to support the W3C WebSub discovery protocol. 

include::../requirements/requirements_class_discovery.adoc[]

==== Requirement HTTP Methods
An implementation shall support discovery via HTTP GET and HEAD methods.

include::../requirements/requirement001.adoc[]

==== Requirement Link Header 'hub'
An implementation shall return the `<Link/>; rel="hub"` HTTP header to indicate support for WebSub.

include::../requirements/requirement002.adoc[]

==== Requirement Link Header 'self'
An implementation shall return the `<Link/>; rel="self"` HTTP header to indicate the ability for subscription.

include::../requirements/requirement003.adoc[]

==== Requirement Link Header 'help'
An implementation shall omit the `<Link/>; rel="self"` HTTP header and instead return the `<Link/>; rel="help"` header to indicate the cause why the requested URL is not suitable for subscription.

include::../requirements/requirement004.adoc[]

=== ODATA Requirements Class (optional)
The `ODATA` requirements class is implemented at the SensorThings API service - HTTP interface and supports the W3C WebSub discovery protocol. 

include::../requirements/requirements_class_odata.adoc[]

==== Requirement ODATA query parameter
An implementation shall allow the discovery such that the associated MQTT topic is compliant to OGC SensorThings API v1.1 requirement regarding updates via MQTT [<<OGC18088>>, section 14.2 (https://docs.ogc.org/is/18-088/18-088.html#req-receive-updates-via-mqtt-receive-updates)] with the following extensions:

* `SERVICE_VERSION/RESOURCE_PATH/COLLECTION_NAME` as defined in https://docs.ogc.org/is/18-088/18-088.html#mqtt-subscribe-entity-set[ยง14.2.1] can be extended with a `?` followed by any valid combination of ODATA commands - e.g. `v1.1/Datastreams(1)/Observations?$filter=result gt 30`
* `SERVICE_VERSION/RESOURCE_PATH_TO_AN_ENTITY` as defined in https://docs.ogc.org/is/18-088/18-088.html#mqtt-entity-updates[ยง14.2.2] can be extended with a `?` followed by any valid combination of ODATA commands - e.g. `v1.1/Observations?$select=result`
* `SERVICE_VERSION/RESOURCE_PATH_TO_AN_ENTITY/PROPERTY_NAME` as defined in https://docs.ogc.org/is/18-088/18-088.html#mqtt-subscribe-entity-property[ยง14.2.3]

include::../requirements/requirement100.adoc[]

An implementation shall advertise the support for ODATA query parameters by publishing the string `http://www.opengis.net/spec/sensorthings-websub/1.0/conf/odata` in the conformance section of the Landing Page.

```
"conformance": {
    "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/odata"
}
```
include::../requirements/requirement101.adoc[]

==== Requirement Blacklisting ODATA Commands
A STA URL may contain query parameters (after the `?`) presenting ODATA commands. An implementation may deny discovery (and thereby later subscription) for certain ODATA commands like `$expand` or `$filter`. 

An implementation shall advertise the existence of denied ODATA commands by adding the following key to the Landing Page: `http://www.opengis.net/spec/sensorthings-websub/1.0/conf/odata` that includes the key `odata_denied`. This key shall contain a JSON array for all denied ODATA commands. 

include::../requirements/requirement102.adoc[]

```
"http://www.opengis.net/spec/sensorthings-websub/1.0/conf/odata": {
    "odata_denied": <JSON Array of denied ODATA commands>
}
```

In case no ODATA commands are denied, the implementation shall declare that with an empty JSON array.

For example, the following Landing Page snippet indicates **no** discovery restrictions for ODATA commands:

```
"http://www.opengis.net/spec/sensorthings-websub/1.0/conf/odata": {
    "odata_denied": []
}
```

For example, the following Landing Page snippet indicates discovery restrictions for `$expand`, `$skip`, `$top` and `$filter`:

```
"http://www.opengis.net/spec/sensorthings-websub/1.0/conf/odata": {
    "odata_denied": ["$expand", "$skip", "$top", "$filter"]
}
```

=== LandingPage Requirements Class (mandatory)

include::../requirements/requirements_class_landingpage.adoc[]

==== Requirement Declare Conformance for STA-WebSub
An implementation shall list the conformance class `Discovery` on the landing page.

include::../requirements/requirement200.adoc[]

For example, the following snippet indicates support for STA-WebSub:

```
"conformance": {
    "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
}
```

==== Requirement Blacklisting root topics

A STA root topic starts with `SERVICE_VERSION/RESOURCE_PATH_TO_AN_ENTITY` as defined in https://docs.ogc.org/is/18-088/18-088.html#mqtt-entity-updates[14.2.2]. An implementation shall advertise the existence of denied root topics by adding the following key to the Landing Page: `http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery` that includes the key `topics_denied`. This key shall contain a JSON array for all denied root topics. 

An implementation may deny discovery (and thereby later subscription) for certain root entities (i.e. v1.1/Observation). An implementation shall advertise the blacklisting of root entities for which a discovery is denied on the landing page.

include::../requirements/requirement201.adoc[]

The following snippet illustrates the construct:

```
"http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
    "topics_denied": <JSON Array of denied root topics>
}
```

In case no root topics are denied, the implementation shall declare that with an empty JSON array.

include::../requirements/requirement202.adoc[]

For example, the following Landing Page snippet indicates **no** deny for root topics:

```
"http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
    "topics_denied": []
}
```

For example, the following Landing Page snippet indicates deny for the root topics `v1.1/Observations` and `v1.1/Datastream('very chatty')/Observations`:

```
"http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
    "topics_denied": ["v1.1/Observations", "v1.1/Datastream('very chatty')/Observations"]
}
```

