.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

STA-WebSub - SensorThings API extension WebSub - defines an additional SensorThings API capability which allows the distribution of updates via HTTP(S) using Webhook as defined in the W3C WebSub Recommendation. 

A subscriber can fetch base data from a SensorThings API service and then use the same identical URL to subscribe for updates. This allows any subscriber to prevent polling a SensorThings API service, as any updates - according to the URL used - get submitted to the subscriber's Webhook when the update event is triggered. The use of this WebSub extension is also easy to integrate into existing systems, as producers only need to setup a W3C WebSub compliant Hub that listens to subscription updates via MQTT. Consumers only need to setup a WebSub Subscriber to receive updates via WebHook. The SensorThings API MQTT protocol does not need to be exposed to the subscriber; it can remain internal between the SensorThings API service and the associated STA-WebSub Hub(s). Any SensorThings API service that extends the MQTT topic pattern to include filter and expand capabilities via ODATA query parameters, allows to subscribe for updates by defining actual triggering conditions using `$filter`. Using the ODATA query parameter `$select` and `$expand` also supports the subscriber to get exactly the data and structure as it is fit for purpose. 

The use of STA-WebSub improves the flexible use a SensorThings API service for building asynchronous workflows. The ability to define trigger conditions and to specify the event data structure that is pushed over HTTP(S) POST enables a fit-for-purpose processing of events using workflows. Access control can be implemented in the discovery functionality which controls the subscription based on business or access control policies.

== Security considerations
Any event processing system is susceptible to denial of service attacks when too many clients subscribe to topics with high frequency update (`chatty topics`) or too many updates are received. For example, subscription to the MQTT topic `v1.1/Observations` brings the danger that the SensorThings API service cannot deliver all events to all subscribed clients when the update frequency gets too high. Or, the subscriber may get flooded with event data sent by the hub. 

Any implementation that supports the use of ODATA query parameters is particularly susceptible to denial of service due to the complexity of an ODATA query. An attacker could achieve a denial of service attack by subscribing with a very complex topic URL including an ODATA query. To mitigate such an attack, an implementation should carefully analyze the query parameters of a topic URL before accepting the subscription request.

Any SensorThings API service should deny MQTT update subscriptions that do not origin from an associated Hub. This guarantees that an attacker cannot simply bypass the Hub and swamp the SensorThings API service directly with bogus update subscriptions.

The proper network separation of SensorThings API service and Hub - e.g. in a fast private network - allows to establish a clever load distribution between a SensorThings API service and as many hubs as needed. This self-adaptivity to scaling mitigates the likelihood for denial of service attacks even with many subscribed clients and complex topics.

In any case, the Hub must validate a subscription with the STA-WebSub Service. This can be achieved via the regular discovery request (HTTP Head request with the topic URL).

To prevent bogus subscriptions, a Hub may require authentication for the subscribe / unsubscribe API.

The W3C WebSub recommends that the subscriber's callback URL is 'not easily guessable' and that the callback URL is refreshed whenever a subscription is renewed. Following this recommendation makes the use of other authentication mechanisms, i.e. the use of api-key unnecessary. But, for computing environments were is it is not possible or too difficult to follow this recommendation, the use of `API-Key` or `X-API-Key` can protect a static callback endpoint URL. Likewise refreshing the callback URL, it is strongly recommended that a subscriber updates the api-key value with a strong random value each time a subscription is renewed. 

Leveraging an api-key over HTTPS callback URLs may be preferred over the use of `X-Hub-Signature` when the notification data size is large. The clear advantage is that neither the Hub nor the Subscriber must calculate a hash over the notification data. Also, the use of api-key over HTTPS is equivalent to HMAC. Different api-keys for subscriptions identifies the hub, so it proofs authenticity. And the use of HTTPS ensures content integrity.

== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[%autowidth,cols="3*"]
|===
|Name |Representing |OGC Member

|Andreas Matheus
|Secure Dimensions GmbH
|Yes

|Joan Maso
|Centre de Recerca Ecològica i Aplicacions Forestals (CREAF)
|Yes

|Hylke van der Schaaf
|Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.
|Yes

|===