
=== URI Patterns

URI Patterns in the SensorThings API consist of three parts: the URI-Root, the resource path and query options.
The URI-Root always ends with the version number of the standard, encoded as: `"v"majorversionnumber + "." + minorversionnumber`.
The query options start with a question mark (`?`)

.Example {counter:examples}: Complete URI example using HTTP bindings
[source%unnumbered,text]
----
http://example.org/v2.0/Observations?$orderby=ID&$top=10
_______________________/___________/___________________/
          |                 |               |
  service root URI     resource path   query options
----

.Example {counter:examples}: Complete URI example using MQTT bindings
[source%unnumbered,text]
----
base/topic/v2.0/Observations?$orderby=ID&$top=10
_______________/___________/___________________/
      |              |               |
   root URI    resource path   query options
----


==== Service Document

URI Pattern: `v2.0`

Requesting the path ending with just the version number, optionally followed by a slash (`/`) returns the service document.

The Service document is a JSON object with a property named value and a property named serverSettings.
The content of the property named value SHALL be a JSON Array containing one element for each entity set of the SensorThings Service.
The content of the property named serverSettings SHALL be a JSON Object describing the features the server supports that can not easily be detected by querying the service.

Each element of the value array SHALL be a JSON object with at least two name/value pairs, one with name name containing the name of the entity set (e.g., Things, Locations, Datastreams, Observations, ObservedProperties and Sensors) and one with name url containing the URL of the entity set, which may be an absolute or a relative URL.
(Adapted from OData 4.01-JSON-Format section 5)

The serverSettings object SHALL contain the property conformance of the type Array, containing the URIs of all requirements from this specification and any extensions that the service implements.
If a service implements all requirements from a requirements class, it only needs to list the requirements class id.

Security extensions can modify the list of requirements to only show those requirements that the user is allowed to use.
For example, if a user is not allowed to delete entities, the security extension can hide the create-update-delete/delete-entity requirement.
In the most extreme case, a security extension would hide all requirements for a user that is not authenticated, except its own requirement and the instructions on how to authenticate.

Extensions that need to expose additional server settings may do so in a property of the serverSettings object that is named after the conformance class URI of the requirement that defines this setting.

.A service document using absolute HTTPS-URLs
[source,json]
----
{
  "value": [
    {
      "name": "Things",
      "url": "https://example.org/v2.0/Things"
    },
    {
      "name": "Locations",
      "url": "https://example.org/v2.0/Locations"
    },
    {
      "name": "Datastreams",
      "url": "https://example.org/v2.0/Datastreams"
    },
    {
      "name": "Sensors",
      "url": "https://example.org/v2.0/Sensors"
    },
    {
      "name": "Observations",
      "url": "https://example.org/v2.0/Observations"
    },
    {
      "name": "ObservedProperties",
      "url": "https://example.org/v2.0/ObservedProperties"
    },
    {
      "name": "Features",
      "url": "https://example.org/v2.0/Features"
    },
    {
      "name": "FeatureTypes",
      "url": "https://example.org/v2.0/FeatureTypes"
    }
  ],
  "serverSettings": {
    "conformance": [
        "http://www.opengis.net/spec/sensorthings/2.0/req/datamodel",
        "http://www.opengis.net/spec/sensorthings/2.0/req/resource-path/resource-path-to-entities",
        "http://www.opengis.net/spec/sensorthings/2.0/req/request-data",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/create-entity",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/link-to-existing-entities",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/deep-insert",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/deep-insert-status-code",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/update-entity",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/delete-entity",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/historical-location-auto-creation",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-observations-via-mqtt/observations-creation",
        "http://www.opengis.net/spec/sensorthings/2.0/req/receive-updates-via-mqtt/receive-updates"
    ],
    "http://www.opengis.net/spec/sensorthings/2.0/req/receive-updates-via-mqtt/receive-updates": {
      "endpoints": [
        "mqtt://server.example.com:1833",
        "ws://server.example.com/sensorThings",
      ]
    },
    "http://www.opengis.net/spec/sensorthings/2.0/req/create-observations-via-mqtt/observations-creation": {
      "endpoints": [
        "mqtts://server.example.com:8883",
        "wss://server.example.com:443/sensorThings"
      ]
    }
  }
}
----



==== Service Metadata Document

URI Pattern: `v2.0/$metadata`


==== Entity Set

URI Pattern: `v2.0/EntityTypeName`

.Example {counter:examples}: Resource pattern for the Datastreams Entity Set
[source%unnumbered,text]
----
v2.0/Datastreams
----


==== Entity

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)`

.Example {counter:examples}: Resource pattern for a specific Datastream, for a service that uses Integers for the id field of Datastreams
[source%unnumbered,text]
----
v2.0/Datastreams(4)
----

.Example {counter:examples}: Resource pattern for a specific Datastream, for a service that uses Strings for the id field of Datastreams
[source%unnumbered,text]
----
v2.0/Datastreams('xz42df')
----


==== Related Entity

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)/EntityNavigationProperty`

.Example {counter:examples}: Resource pattern for the Thing of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Thing
----

`v2.0/EntityTypeName(<primaryKey>)/EntitySetNavigationProperty(<primaryKey>)`

.Example {counter:examples}: Resource pattern for a specific Observation of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Observations(5321)
----

The above example returns the same content as `v2.0/Observations(5321)`, except when Observation `5321` is not actually contained in Datastream 4, since in that case the example would return a `Not Found` error.



==== Related EntitySet

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)/EntitySetNavigationProperty`

.Example {counter:examples}: Resource pattern for the Observations of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Observations
----



=== Request Options

=== Response Formatting

intro text for the requirement class.

Use the following table for Requirements Classes.


==== Requirement 1

intro text for the requirement.

Use the following table for Requirements, number sequentially.


==== Requirement 2

intro text for the requirement.

Use the following table for Requirements, number sequentially.

