=== Modifying Data

This section describes how to create, update and delete Entities.
Deltails on how to send create, update and delete requests and how responses are received are described in the protocol bindings sections.


==== Creating Entities (EntitySet)

Entities can be created with a create request to an URI pattern that addresses an entity set (<<pattern_entityset>> or <<pattern_entityset_related>>).
The content of the create request is the JSON encoded representation of the entity to be created.

If the inline representation contains a value for a computed property (i.e., `id`), the service ignores that value when creating the entity.

When the URI pattern is of the related entity set type (<<pattern_entityset_related>>), the created entity is automatically linked to the parent entity of the entity set the create request is sent to.

Relations to existing entities can be created by providing the entity-id (selfLink) of the existing entities.
If a conflicting value for a relation exists in the URI and the content of the request, the value from the URI takes priority.


.Sending a create request to `v2.0/Things(5)/Datastreams` with the given content will create a Datastream, linked to Thing 5, Sensor 2 and the ObservedProperty that matches the definition in the resultType.
[source,json]
----
{
  "name": "Oven temperature",
  "description": "This is a datastream measuring the air temperature in an oven.",
  "resultType": {
    "type": "Quantity",
    "label": "Oven temperature",
    "definition": "http://mmisw.org/ont/cf/parameter/air_temperature",
    "uom": { "code": "Cel", "label": "degree Celsius", "symbol": "°C" }
  },
  "Sensor": {"@id": "Sensors(2)"}
}
----


==== Deep Insert

A create request can have related entities embedded in-line, to be created alongside the main entity.
Such a create request is referred to as a "deep insert".

On success, the service creates all entities and relates them.
On failure, the service does not create any of the entities.

.Sending a create request to `v2.0/Things` with the given content will create a Thing with its Location and a Datastream with an associated Sensor. The Datastream will automatically be linked to the ObservedProperty that matches the definition in the resultType. 
[source,json]
----
{
  "description": "This an oven with a temperature datastream.",
  "name": "oven",
  "Locations": [
    {
      "name": "CCIT",
      "description": "Calgary Centre for Innovative Technologies",
      "encodingType": "application/geo+json",
      "location": {
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [10,10]
        }
      }
    }
  ],
  "Datastreams": [
    {
      "name": "oven temperature",
      "description": "This is a datastream for an oven’s internal temperature.",
      "resultType": {
        "type": "Quantity",
        "label": "Oven temperature",
        "definition": "http://mmisw.org/ont/cf/parameter/air_temperature",
        "uom": { "code": "Cel", "label": "degree Celsius", "symbol": "°C" }
      },
      "Sensor": {
        "name": "DS18B20",
        "description": "DS18B20 is an air temperature sensor…",
        "encodingType": "application/pdf",
        "metadata": "http://datasheets.maxim-ic.com/en/ds/DS18B20.pdf"
      }
    }
  ]
}
----



==== Updating Entities (Single Entity)

Entities can be updated with a patch or replace request to an URI pattern that addresses an entity set (<<pattern_entity>> or <<pattern_entity_related>>).
Services MUST support patch requests and MAY support replace requests.

A patch request must contain as content only those updatable attributes of the entity that are to be changed.
Attributes that are not present in the patch request are not changed, though server-generated attributes may be updated by the server as a result of the change request.

A replace request must contain as content the complete entity to be replaced.
Attributes that are not present in the replace request are removed from the entity.

For even finer grained update control, or updates that are safe from concurrent modification by other user, see <<json-patch>>.


==== Deep Update

EDITOR: Do we want delta payloads? https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_UpdateRelatedEntitiesWhenUpdatinganE

[[json-patch]]
==== JSON-Patch

https://datatracker.ietf.org/doc/html/rfc6902/



[[return-value]]
==== Return Value

The returned value for a, entity modification request depends on the `prefer` option, with the possible values `return=minimal` (default) and `return=representation`.

If the `prefer` option is not present, or does not contain a value for `return`, or has `return=minimal` then, for create requests, the entity-id (selfLink) of the created entity is returned as a header, and no content is returned.
For update requests no content is returned.

If the `prefer` option has `return=representation`, then the created resource is returned, optionally taking `$expand`, `$select` and `$format` query options into account.


==== Modifying Relations


=== Authentication & Authorization
