== HTTP Interface Bindings

The HTTP Bindings specify how access the SensorThings API using the HTTP protocol.

The actions that can be executed on resources, as defined in the <<abstract_api>> are mapped to HTTP Methods as defined in table <<http-method-mapping>>.

[#http-method-mapping,reftext='{table-caption} {counter:table-num}']
.Mapping of abstract request types to HTTP Methods.
[width="80%",cols="<,<",options="header"]
|====
| *Request type*
| *HTTP Method*

| Read
| GET

| Create
| POST

| Update
| PATCH

| Replace
| PUT

| Delete
| DELETE

| Execute
| POST
|====

Content for Create, Update, Replace or Execute requests is passed in the body of the HTTP request.

HTTP HEAD and OPTIONS requests are treated as normal GET requests, but don't return data.
If a GET request with the same URL and headers would return an error, the HEAD or OPTION requests also returns this error.

[[return-value]]
=== Return Value

The returned value for a entity modification request depends on the `prefer` header, with the possible values `return=minimal` (default) and `return=representation`.

If the `prefer` header is not present, or does not contain a value for `return`, or has `return=minimal` then, for create requests, the entity-id (selfLink) of the created entity is returned as a header, and no content is returned.
For update requests no content is returned.

If the `prefer` header has `return=representation`, then the created resource is returned, optionally taking `$expand`, `$select` and `$format` query options into account.

EDITOR: point to W3 standards


=== Cross Origin Resource Sharing

=== Authentication & Authorization

