[obligation=informative]
== STA-WebSub Extension
The STA-WebSub - SensorThings API WebSub - Extension as defined in this OGC Standard is based on the W3C WebSub Recommendation. 

=== Introduction to W3C WebSub

[NOTE]
====
It is recommended to first read the link:https://www.w3.org/TR/websub[W3C WebSub Recommendation].
====

WebSub is a W3C Recommendation that addresses how to implement asynchronous processing over the Web. First, the discovery protocol allows a Subscriber to check with a Publisher if self-defined topics can be used for subscription. Second, the subscription protocol defines how a Subscriber can interact with a hub to register a topic for receiving notifications afterwards. 

The following figure illustrates the basic functioning of the W3C WebSub Recommendation.

[[WebSubOverview]] 
.W3C WebSub Flow Diagram

[plantuml]
....
@startuml

participant Subscriber
participant Publisher
participant Hub

Subscriber -> Publisher: Subscriber discovers the hub advertised\nby publisher's topic
Subscriber -> Hub: Subscriber makes a POST to the hub\nto subscribe to updates about topic
Hub --> Subscriber: Hub verifies the subscription attempt with a GET
Publisher -> Hub: Publisher notifies the hub\nof new content
Hub -> Subscriber: Hub delivers the contents of topic to each subscriber with a POST

@enduml
....

The notification protocol is deliberately left unspecified (see WebSub ยง6 and __"Publisher notifies the hub of new content"__ as illustrated above) so that basically any protocol can be used between a publisher and a hub. This OGC STA-WebSub Standard leverages this openness to couple the publisher and the hub using MQTT.

=== STA-WebSub Overview
A SensorThings API implementation supports two protocols: The HTTP interface and the MQTT interface. STA-WebSub leverages the W3C WebSub openness (see ยง6 W3C WebSub for details) for specifying the protocol between the Hub and the Publisher using MQTT. In addition it specifies that the SensorThings API HTTP interface implementation supports the W3C WebSub discovery requirements.

A system for STA-WebSub consists of two parts:

* SensorThings HTTP interface: 
    ** The W3C discovery protocol must be implemented. 
    ** The STA-WebSub error handling must be implemented.
* Hub: 
    ** The subscription functionality must be extended to transform a W3C topic URL into a SensorThings MQTT topic and the Hub must use the MQTT protocol to subscribe/unsubscribe for topics. 
    ** The notification of distribution events takes place via MQTT. A STA-WebSub Hub must therefore listen to MQTT events received from the associated MQTT broker and distribute the event content to all subscribers using HTTP(S) POST. 

An implementation of a STA-WebSub system is available as open source: 

* The STA-WebSub Hub is available as open source from Github: https://github.com/securedimensions/WebSub-Hub
* The W3C discovery protocol extension for the SensorThings API service is implemented as a plugin to FROST-Server:
    ** STA-WebSub plugin: https://github.com/securedimensions/FROST-Server-WebSub
    ** The FROST-Server: https://github.com/FraunhoferIOSB/FROST-Server

The STA-WebSub - SensorThings API extension WebSub - defines additional capabilities in the context of SensorThings API that allow the propagation of updates via HTTP(S) using callback URLs as defined in W3C WebSub Recommendation. The notification event and content is based on MQTT as defined in the SensorThings API Standard. 

To make STA-WebSub work, the subscriber, publisher and hub need to implement certain functionalities. In order to understand the requirements better, the following high-level flow diagram illustrates the additions for STA-WebSub:

[[STA-WebSubOverview]] 
.STA-WebSub Flow Diagram

[plantuml]
....
@startuml

title STA-WebSub Flow Diagram

participant "STA-WebSub Subscriber"
participant "STA-WebSub Publisher\n(STA Service - HTTP interface)" #lightYellow
participant "STA Service - MQTT interface"
participant "STA-WebSub Hub"

"STA-WebSub Subscriber" -> "STA-WebSub Publisher\n(STA Service - HTTP interface)": Subscriber discovers the hub\nadvertised by publisher's topic
"STA-WebSub Subscriber" -> "STA-WebSub Hub": Subscriber makes a POST to the hub to subscribe to updates about topic

"STA-WebSub Hub" --> "STA-WebSub Subscriber": Hub verifies the subscription attempt with HTTP GET
"STA-WebSub Hub" --> "STA-WebSub Publisher\n(STA Service - HTTP interface)": Hub verifies subscription with HTTP HEAD

"STA-WebSub Hub" -> "STA Service - MQTT interface": Subscribe to topic with MQTT

"STA Service - MQTT interface" -> "STA-WebSub Hub": Publisher notifies the hub of\nnew content for MQTT topic
"STA-WebSub Hub" -> "STA-WebSub Subscriber": Hub delivers the contents for MQTT topic to each subscriber with HTTP POST

@enduml
....

[NOTE]
====
As illustrated in the STA-WebSub flow diagram above, this Standard has implications to the subscriber, the implementations of the publisher and the hub. But only the part of the publisher is considered normative here, as the SensorThings API service is the standardization target. To ensure a working solution, the Appendix B provides guidance for the implementation specific aspects to adapt a W3C Hub for STA-WebSub.
====

The use of W3C WebSub does not predefine topics. Instead, the subscriber can discover if a topic (URL) can be used for subscription. This flexibility is important for STA-Web to support the subscriber for defining (i) the actual trigger for a change event and (ii) the data structure for the received content. Any implementation of the WebSub extension must support a MQTT topic pattern as defined in SensorThings API v1.0 or v1.1 extended by an ODATA query. A SensorThings API service implementation that supports ODATA commands with MQTT topics offers the subscriber to use `$filter` for specifying the event trigger and `$select` and `$expand` to specify the content data structure. The ability to craft notification conditions in combination to compose exactly the data structure needed for a notification is a powerful ability to trigger fit for purpose workflow executions connected to a subscriber's Webhook.

[NOTE]
====
The support for `$select` is mandatory for a SensorThings API service implementation. However, the support for `$filter` and `$expand` is optional. 
====

=== Introduction to Discovery, Subscription and Notification
For extending the W3C WebSub protocol to support STA-WebSub, certain functional requirements are to be defined regarding discovery, subscription and notification.

==== Discovery
A STA-WebSub compliant SensorThings API HTTP interface (aka publisher) supports the W3C WebSub discovery by adding the `Link` headers `rel="hub"` and `rel="self"` to the HTTP response. W3C WebSub further requires that the `Link` headers are returned either as HTTP response headers or inline to a XHTML encoded response. As the typical response encoding for SensorThings API is not XHTML - it usually is either JSON or GeoJSON - the STA-WebSub extension requires that the `Link` headers are returned as HTTP response headers. The W3C WebSub foresees further that these discovery links will be returned on a HTTP GET or HEAD request. To meet the HTTP method requirement for discovery, the STA-WebSub extension requires that a publisher implementation supports the HTTP HEAD method in addition to the already supported HTTP GET method. 

==== Discovery Error Handling
A STA-WebSub hub may receive a subscription request via the `hub.topic` that transforms to a MQTT topic which may not be accepted by the SensorThings API MQTT broker. Which topic URLs are accepted is deployment specific. For example, the subscription to `/Observations` may produce a too high load or the use of not supported / not allowed ODATA commands like `$expand` or `$filter` may cause that no `Link rel="self"` is returned. The missing `Link rel="self"` header implies that subscription for such a topic URL is not possible. This behavior is perfectly compliant with the WebSub Recommendation. But any subscriber (user or service/process) may wonder why the discovery response does not include the `Link rel="self"` header. 

Technically, the fact that no `Link rel="self"` is returned is not an error. Therefore, the use of HTTP 4xx status codes is not appropriate. Also, the W3C WebSub does not specify any error handling. But to support a subscriber, there should be guidance why the link header `rel="self"` is missing.

This STA-WebSub Standard introduces the use of the `Link rel="help"` header. The URL for this relationship must point to a (static) help page that explains why a subscription to the topic URL is not possible.

==== Subscriptions
A STA-WebSub Hub is capable to transform the W3C WebSub `hub.topic` expressed as a HTTP(S) URL into a MQTT topic pattern accepted by the MQTT broker associated with the SensorThings API service. As the SensorThings API service and the Hub are working in close relation, this transformation should not be too difficult.

To prevent that a subscription to an unsupported MQTT is possible, the Hub must use the discovery protocol and deny the request if the discovery response does not include the `Link rel="self"` header.

In case the Hub receives an unsubscribe request from the subscriber, the Hub must verify the intent with the subscriber and unsubscribe from the  MQTT topic with the associated SensorThings API service.

==== Notifications
Once the Hub has subscribed to a MQTT topic, it awaits MQTT notifications from the MQTT broker of the SensorThings API service. In case of a notification event (topic + content), the Hub delivers the content to the subscribed callback URLs (the subscribers' Webhooks).

=== X-Api-Key and X-Hub-Signature
One fundamental (runtime) functionality for a WebSub Hub is the ability to deliver a notification content to all subscribers. 

The W3C WebSub offers the use of HMAC so that subscribers can validate the authenticity of received content; basically check that the content was received from the expected hub. Leveraging HMAC also enables the subscriber to validate content integrity which is important when using non secure communication - so HTTP instead of HTTP**S**. The W3C WebSub supports the transmission of the HMAC using the HTTP header `X-Hub-Signature`.

The use of HMAC signatures however introduces a burden to the hub's and subscriber's CPU when calculating the HMAC value. It also requires caching of the content at the hub and the subscriber. This prevents that the subscriber can stream the received content directly into connected workflow processing. But, on the hub side, the caching does not introduce a resource burden as an implementation would probably cache the content anyway before distributing it to all subscribers.

Because the validation of the HMAC requires that a subscriber receives the entire content, this introduces a denial-of-service vulnerability. Assuming that an attacker would send large fraudulent content with high frequency (many content processing in parallel), the subscriber must process the entire content to determine authenticity. 

The W3C WebSub recommends that a callback URL is random and gets refreshed by the subscriber when a subscription is updated. This procedure gains equivalent protection of the callback endpoint to the use of api-key. The use of HMAC is not necessary, assuming that a callback endpoint is associated with one hub only and the callback operates over HTTPS. 

However, when the generation or refreshing of callback URLs is not possible or too difficult, STA-WebSub offers the use of api-key authentication. The use of api-key compensates the use of random callback URLs. And, api-key in combination with HTTP**S** callback URLs is equivalent to the use of HMAC in terms of authenticity and integrity but it is not necessary to calculate HMAC on the hub side and validate on the subscriber side. This reduces the burden on resources at the hub and subscriber side. This is important for hub deployments on the edge.

Like the use of `hub.secret` to share the secret for HMAC generation, a STA-WebSub subscription may include the parameter `hub.api_key` or `hub.x_api_key` to trigger api-key management at the hub. These parameters trigger that the hub adds the HTTP header `Api-Key` or `X-Api-Key` when distributing the content to the subscriber.

=== Benefits of STA-WebSub
According to the https://docs.ogc.org/is/18-088/18-088.html[SensorThings API v1.1 Standard], any notification will origin the MQTT broker of the SensorThings API service. The STA-WebSub extension as defined in this OGC Standard supports the distribution of the MQTT events via the HTTP(S). Therefore, it is not the MQTT broker that sends the events 1->n, it is the Hub that does that. This separation of duty brings important improvements regarding use, security and scalability:

* The use of the STA-WebSub extension makes the MQTT protocol internal between the MQTT broker of the SensorThings API service and the associated Hub(s). This allows to restrict MQTT subscriptions origin the associated STA-WebSub Hub. Also, the use of discovery policies allow to implement flexible and fine grained access control regarding the subscriptions done by the Hub. 
* The fact that the MQTT protocol is internal between the Hub and the SensorThings Service simplifies the use for subscribers to well-known infrastructure patterns like Webhook, essentially using a W3C WebSub compliant HTTP(S) endpoint listening for GET and POST requests.
* The separation of duty for sending update 'content' to subscribers between the SensorThings API and the Hub improves scalability. The SensorThings API service only delivers the topic updates to associated Hub(s) using MQTT. The Hub(s) then optionally processes the MQTT message and distributes the content to subscribers using well understood cloud-scaling code stacks.
* The ability that subscribers can determine the notification conditions (i.e. using `$filter`) and the data structure of the notification (i.e. using `$select` and `$expand`) improves the usability over predefined MQTTP topics. How flexible a subscriber can get is controlled by the discovery functionality.