[[staplus-read-create-update-delete]]
== STAplus Read, Create, Update and Delete Requirements


=== Overview

As many IoT devices are resource-constrained, the SensorThings API adopts the efficient REST web service style. That means the Read, Create, Update, Delete actions can be performed on a STAplus entity type. 

[[read-entity]]
=== Requirements Class *Read*

[requirements_class]
.Read

====
[%metadata]
identifier:: {identifier}/req-class/read
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier}/req-class/entity-control-information
requirement:: {identifier}/req/read/entity
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/read/entity

To read a STAplus entity or a collection of STAplus entities, the client SHALL send a HTTP GET request to that entity or the collection's URL. 

If the target URL for the collection is a navigationLink, the entity is automatically linked to the entity or entities represented by the navigationLink.

Upon successful completion, the response SHALL contain the representation of the entity or entities.
====

[[create-entity]]
=== Requirements Class *Create*

[requirements_class]
.Create

====
[%metadata]
identifier:: {identifier}/req-class/create
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier}/req-class/entity-control-information
requirement:: {identifier}/req/create/entity
requirement:: {identifier}/req/create/link-to-existing-entities
requirement:: {identifier}/req/create/deep-insert
requirement:: {identifier}/req/create/deep-insert-status-code
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/create/entity

To create a STAplus entity in a collection, the client SHALL send a HTTP POST request to that collection's URL. The POST body SHALL contain a single valid entity representation.

If the target URL for the collection is a navigationLink, the new entity is automatically linked to the entity containing the navigationLink.

Upon successful completion, the response SHALL contain a HTTP location header that contains the selfLink of the created entity.

Upon successful completion the service SHALL respond with either 201 Created, or 204 No Content.

Adapted from <<ODATA, OData Version 4.01. Part 1: Protocol, ยง11.4.2 Create an Entity>>
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/create/link-to-existing-entities

A STAplus implementation that supports entity creation SHALL support linking new STAplus entities to existing entities upon creation. To create a new entity with links to existing entities in a single request, the client SHALL include the unique identifiers of the related entities associated with the corresponding navigation properties in the request body.
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/create/deep-insert

A request to create a STAplus entity that includes related entities, represented using the appropriate inline representation, is referred to as a "deep insert". A STAplus implementation that supports entity creation SHALL support deep insert.

If the inline representation contains a value for a computed property (__i.e.__, id), the service SHALL ignore that value when creating the related entity.

On success, the service SHALL create all entities and relate them. On failure, the service SHALL NOT create any of the entities.

Adapted from <<ODATA, OData Version 4.01. Part 1: Protocol, ยง11.4.2.2 Create Related Entities When Creating an Entity>>

====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/create/deep-insert-status-code

Upon successfully creating a STAplus entity, the service response SHALL contain a Location header that contains the URL of the created entity. Upon successful completion the service SHALL respond with 201 Created.
====

[[staplus-update]]
=== Requirements Class *Update*

[requirements_class]
.Update

====
[%metadata]
identifier:: {identifier}/req-class/update
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier}/req-class/entity-control-information
inherit:: https://docs.ogc.org/is/18-088/18-088.html#req-create-update-delete-update-entity
inherit:: https://docs.ogc.org/is/18-088/18-088.html#req-create-update-delete-update-entity-put
inherit:: https://docs.ogc.org/is/18-088/18-088.html#req-create-update-delete-update-entity-jsonpatch
requirement:: {identifier}/req/update/entity
requirement:: {identifier}/req/update/entity-put
requirement:: {identifier}/req/update/entity-jsonpatch
====


[requirement]
====
[%metadata]
identifier:: {identifier}/req/update/entity

To update a STAplus entity in a collection a STAplus implementation SHALL follow the requirements as defined in https://docs.ogc.org/is/18-088/18-088.html#req-create-update-delete-update-entity.
====


[requirement]
====
[%metadata]
identifier:: {identifier}/req/update/entity-put

A STAplus implementation that supports updates with PUT SHALL follow the requirements as defined in https://docs.ogc.org/is/18-088/18-088.html#req-create-update-delete-update-entity.
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/update/entity-jsonpatch

A STAplus implementation that supports updates with the JSON PATCH format SHALL follow the requirements as defined in https://docs.ogc.org/is/18-088/18-088.html#req-create-update-delete-update-entity-jsonpatch
====

[[staplus-delete]]
=== Requirements Class *Delete*

[requirements_class]
.Delete

====
[%metadata]
identifier:: {identifier}/req-class/delete
obligation:: requirement
subject:: Target Type: Implementation
inherit:: {identifier}/req-class/entity-control-information
inherit:: https://docs.ogc.org/is/18-088/18-088.html#req-create-update-delete-delete-entity
requirement:: {identifier}/req/delete/entity
====

[requirement]
====
[%metadata]
identifier:: {identifier}/req/delete/entity

To delete a STAplus entity in a collection a STAplus implementation SHALL follow the requirements as defined in https://docs.ogc.org/is/18-088/18-088.html#req-create-update-delete-delete-entity.
====


