=== Requesting Data

This section describes how to read data from a SensorThings API compatible service.
Details on how to send requests and how to receive responses are described in the protocol bindings sections.
For example, when using the HTTP bindings, GET is used for read requests.

Adapted from:

- https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html
- https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html

[[context_url]]
==== Context URL

Most responses to read requests contain a context URL that describes the content of the payload.
The context URL consists of the URL of the service metadata document (See <<pattern_service_metadata_document>>, <<OData-CSDL>>) followed by a fragment that identifies the relevant portion of the document.

EDITOR: Explain the `@context` url. Do we want to go the full complexity? https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ContextURL

A read (GET) Requests to the Service Document URL pattern (<<pattern_service_metadata_document>>) returns the service metadata document as described in <<OData-CSDL>>.


[[read_service_document]]
==== Service Document

A read (GET) Requests to the Service Document URL pattern (<<pattern_service_document>>) returns the service document.

The Service document is a JSON object with a property named value and a property named serverSettings.
The content of the property named value SHALL be a JSON Array containing one element for each entity set of the SensorThings Service.
The content of the property named serverSettings SHALL be a JSON Object describing the features the server supports that can not easily be detected by querying the service.

Each element of the value array SHALL be a JSON object with at least two name/value pairs, one with name name containing the name of the entity set (e.g., Things, Locations, Datastreams, Observations, ObservedProperties and Sensors) and one with name url containing the URL of the entity set, which may be an absolute or a relative URL.
(Adapted from OData 4.01-JSON-Format section 5)

The serverSettings object SHALL contain the property conformance of the type Array, containing the URIs of all requirements from this specification and any extensions that the service implements.
If a service implements all requirements from a requirements class, it only needs to list the requirements class id.

Security extensions can modify the list of requirements to only show those requirements that the user is allowed to use.
For example, if a user is not allowed to delete entities, the security extension can hide the create-update-delete/delete-entity requirement.
In the most extreme case, a security extension would hide all requirements for a user that is not authenticated, except its own requirement and the instructions on how to authenticate.

Extensions that need to expose additional server settings may do so in a property of the serverSettings object that is named after the conformance class URI of the requirement that defines this setting.

.An example service document.
[source,json]
----
{
  "@context": "<Service Root>/v2.0/$metadata",
  "value": [
    {
      "name": "Things",
      "url": "<Service Root>/v2.0/Things"
    },
    {
      "name": "Locations",
      "url": "<Service Root>/v2.0/Locations"
    },
    {
      "name": "Datastreams",
      "url": "<Service Root>/v2.0/Datastreams"
    },
    {
      "name": "Sensors",
      "url": "<Service Root>/v2.0/Sensors"
    },
    {
      "name": "Observations",
      "url": "<Service Root>/v2.0/Observations"
    },
    {
      "name": "ObservedProperties",
      "url": "<Service Root>/v2.0/ObservedProperties"
    },
    {
      "name": "Features",
      "url": "<Service Root>/v2.0/Features"
    },
    {
      "name": "FeatureTypes",
      "url": "<Service Root>/v2.0/FeatureTypes"
    }
  ],
  "serverSettings": {
    "conformance": [
        "http://www.opengis.net/spec/sensorthings/2.0/req/datamodel",
        "http://www.opengis.net/spec/sensorthings/2.0/req/resource-path/resource-path-to-entities",
        "http://www.opengis.net/spec/sensorthings/2.0/req/request-data",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/create-entity",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/link-to-existing-entities",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/deep-insert",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/deep-insert-status-code",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/update-entity",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/delete-entity",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-update-delete/historical-location-auto-creation",
        "http://www.opengis.net/spec/sensorthings/2.0/req/create-observations-via-mqtt/observations-creation",
        "http://www.opengis.net/spec/sensorthings/2.0/req/receive-updates-via-mqtt/receive-updates"
    ],
    "http://www.opengis.net/spec/sensorthings/2.0/req/receive-updates-via-mqtt/receive-updates": {
      "endpoints": [
        "mqtt://server.example.com:1833",
        "ws://server.example.com/sensorThings",
      ]
    },
    "http://www.opengis.net/spec/sensorthings/2.0/req/create-observations-via-mqtt/observations-creation": {
      "endpoints": [
        "mqtts://server.example.com:8883",
        "wss://server.example.com:443/sensorThings"
      ]
    }
  }
}
----

EDITOR: Add section on listing implemented features, like filter functions.


==== EntitySet

When a Read (GET) request is made to a URI pattern that addresses an entity set (<<pattern_entityset>>, <<pattern_entityset_related>>), the service returns a JSON object with the properties `@context` and `value` and optionally `@count` and `@nextLink`.
The `@context` annotation SHALL be a context URI as described in <<context_url>>.
The value of the `value` property SHALL be an array containing entities in the specified entity set, or an empty array if there are no entities in the addressed set.
The `@count` annotation SHALL, if returned by default, or requested explicitly, contain the total number of items in the set that match the request, as described in <<top>>.
If service-driven pagination is in effect, the `@nextLink` annotation SHALL contain a link to the next set of entities, as described in <<server_driven_pagination>>.

Read requests to an entity set can use all query options: `$filter`, `$count`, `$orderby`, `$skip`, `$top`, `$expand`, `$select` and `$format`.


.Possible result from a read request to an Entity Set resource returning ObservedProperties, with $top=5 and $count=true
[source,json]
----
{
  "@context": "<Service Root>/v2.0/$metadata#ObservedProperties",
  "@count": 36,
  "value": [
    {
      "@id": "<Service Root>/v2.0/ObservedProperties(1)",
      "id": 1,
      "name": "SO2",
      "definition": "http://dd.eionet.europa.eu/vocabulary/aq/pollutant/1",
      "description": "SO2",
      "properties": {
        "eionetId": 1,
        "owner": "http://dd.eionet.europa.eu",
        "recommendedUnit": "µg/m3"
      },
      "Datastreams@navigationLink": "<Service Root>/v2.0/ObservedProperties(1)/Datastreams"
    },
    {
      "@id": "<Service Root>/v2.0/ObservedProperties(2)",
      "id": 2,
      "name": "PM2.5",
      "definition": "http://dd.eionet.europa.eu/vocabulary/aq/pollutant/6001",
      "description": "PM2.5",
      "properties": {
        "eionetId": 6001,
        "owner": "http://dd.eionet.europa.eu",
        "recommendedUnit": "µg/m3"
      },
      "Datastreams@navigationLink": "<Service Root>/v2.0/ObservedProperties(2)/Datastreams"
    }, { … }, { … }, { … }
  ],
  "@nextLink": "<Service Root>/v2.0/ObservedProperties?$top=5&$skip=5"

}
----


==== Single Entity

When a Read (GET) request is made to a URI pattern that addresses a single entity (<<pattern_entity>>, <<pattern_entity_related>>), the service returns a JSON object representing the entity, with the added properties `@context`. The `@context` annotation SHALL be a context URI as described in <<context_url>>.

Read requests to a URI pattern that returns a single entity can use the `$expand`, `$select` and `$format` query options.

.Possible result from a request to an Entity resource returning a Thing
[source,json]
----
{
  "@context": "<Service Root>/v2.0/$metadata#Things/$entity",
  "@id": "<Service Root>/v2.0/Things(1)",
  "id": 1,
  "name": "Oven",
  "description": "This thing is an oven.",
  "properties": {
    "owner": "Noah Liang",
    "color": "Black"
  },
  "HistoricalLocations@navigationLink": "<Service Root>/v2.0/Things(1)/HistoricalLocations",
  "Locations@navigationLink": "<Service Root>/v2.0/Things(1)/Locations",
  "Datastreams@navigationLink": "<Service Root>/v2.0/Things(1)/Datastreams"
}
----



==== Single Entity Property

When a Read (GET) request is made to a URI pattern that addresses a single entity property (<<pattern_entity_property>>), the service returns the JSON representation of this entity property.

.Possible result from a request to an Entity resource returning the name of a Thing
[source,json]
----
{
  "@context": "<Service Root>/v2.0/$metadata#Edm.String",
  "value": "Oven"
}
----


==== Raw Value of a Single Entity Property

When a Read (GET) request is made to a URI pattern that addresses the raw value of a single entity property (<<pattern_entity_property_raw>>), the service returns the entity property.

.Possible result from a request to an Entity resource returning the raw value of the name of a Thing
[source,json]
----
Oven
----


==== Relation Reference

When a Read (GET) request is made to a URI pattern that addresses a relation reference (<<pattern_relation>>), the service responds with the  entity-id(s) of the target Entity(s).

.Response to a read request for <Service Root>/v2.0/Datastream(10643)/Thing
[source,json]
----
{
  "@context": "<Service Root>/v2.0/$metadata#$ref",
  "@id": "<Service Root>/v2.0/Things(42)"
}
----


.Response to a read request for <Service Root>/v2.0/Things(42)/Datastreams
[source,json]
----
{
  "@context": "http://host/service/$metadata#Collection($ref)",
  "value": [
    { "@id": "<Service Root>/v2.0/Datastreams(10643)" },
    { "@id": "<Service Root>/v2.0/Datastreams(10759)" }
  ]
}
----

.Response to a read request for <Service Root>/v2.0/Things(1)/Locations(1)
[source,json]
----
{
  "@context": "<Service Root>/v2.0/$metadata#$ref",
  "@id": "<Service Root>/v2.0/Locations(1)"
}
----


=== Request Query Options

Read requests can be modified using various query options.

==== Evaluation Order

The OGC SensorThings API adapts many of OData's system query options and their usage.
These query options allow refining the request.
The result of the service request is as if the system query options were evaluated in the following order.

Prior to applying any server-driven pagination:

- `$filter`
- `$count`
- `$orderby`
- `$skip`
- `$top`

After applying any server-driven pagination:

- `$expand`
- `$select`
- `$format`


[[select]]
==== $select

The $select system query option requests the service to return only the properties explicitly requested by the client.
The value of a $select query option SHALL be a comma-separated list of selection clauses.
Each selection clause SHALL be a property name (including navigation property names).
For navigation properties, `$select` controls the inclusion of the navigationLink in the response.

In the response, the service SHALL return the specified content, if available.
Expanded navigation properties do not need to be added to the `$select` list, they SHALL always be included in the response.
The `$select` option can be applied to any request that returns an Entity or an EntitySet.

Note: Adapted from OData 4.01-Protocol 11.2.5.1

.Resource pattern returning only the `id` and `name` of the Entities in the Things EntitySet.
[source,text]
----
v2.0/Things?$select=id,name
----


[[select_distinct]]
==== $select distinct

It is quite useful to give Entities common properties, like a “type”.
But when filtering on such a common property the client needs to know what the used values are.
Distinct select allows a client to request all distinct values for a field or a set of fields.

Distinct select can be used in expands, and can be ordered.
When combining $orderby with a distinct select, it is only possible to order by the exact fields that are selected.

Note that selecting distinct values for the primary key field (`id`) makes no sense, since this field is unique for each entity.

To request the distinct values for a set of selected fields, add the `distinct:` keyword at the start of the `$select` parameter.

The returned data is formatted just like a non-distinct request of the same type would be.


.request returning all distinct values of the properties/type field of all Things
[source,text]
----
v2.0/Things?$select=distinct:properties/type
----

.possible response to the above request
[source,json]
----
{
    "value": [
        { "properties": { "type": "waterBody" } },
        { "properties": { "type": "station" } },
        { "properties": { "type": "aquifer" } }
    ]
}
----


[[expand]]
==== $expand

The `$expand` system query option indicates the related entities to be represented inline.
The value of the `$expand` query option SHALL be a comma separated list of navigation property names.
Query options can be applied to the expanded navigation property by appending a semicolon-separated list of query options, enclosed in parentheses, to the navigation property name.
Allowed system query options are `$filter`, `$select`, `$orderby`, `$skip`, `$top`, `$count`, and `$expand`.

The `$expand` option can be applied to any request that returns an Entity or an EntitySet.

Note: Adapted from OData 4.01-Protocol 11.2.5.2

.Resource pattern returning Things, with their Datastreams, and the ObservedProperty for each Datastream.
[source,text]
----
v2.0/Things?$expand=Datastreams($expand=ObservedProperty)
----

.Resource pattern returning Datastream as well as the result and phenomenonTime of the last Observation (as ordered by phenomenonTime) and the ObservedProperty associated with this Datastream.
[source,text]
----
v2.0/Datastreams?$expand=Observations($select=result,phenomenonTime;$orderby=phenomenonTime desc;$top=1),ObservedProperty
----


[[top]]
==== $top

The `$top` system query option specifies the limit on the number of items returned from an EntitySet.
The value of the `$top` system query option SHALL be a non-negative integer.
The service SHALL return the number of available items up to but not greater than the specified value.

If no unique ordering is imposed through an $orderby query option, the service SHALL impose a stable ordering across requests that include `$top`.

In addition, if the `$top` value exceeds the service-driven pagination limitation (i.e., the largest number of entities the service can return in a single response), the `$top` query option SHALL be discarded and the server-side pagination limitation SHALL be imposed.

Note: Adapted from OData 4.01-Protocol 11.2.6.3

.Resource pattern returning only the first five entities in the Things EntitySet.
[source,text]
----
v2.0/Things?$top=5
----

.Resource pattern returning the first five Observation entries after sorting by the phenomenonTime property in descending order.
[source,text]
----
v2.0/Observations?$top=5&$orderby=phenomenonTime%20desc
----


[[skip]]
==== $skip

The `$skip` system query option specifies the number for the items of the queried EntitySet that SHALL be excluded from the result.
The value of `$skip` system query option SHALL be a non-negative integer n.
The service SHALL return items starting at position n+1.

Where $top and `$skip` are used together, `$skip` SHALL be applied before `$top`, regardless of the order in which they appear in the request.

If no unique ordering is imposed through an `$orderby` query option, the service SHALL impose a stable ordering across requests that include `$skip`.

Note: Adapted from OData 4.01-Protocol 11.2.6.4

.Resource pattern returning Thing entities starting with the sixth Thing entity in the Things EntitySet.
[source,text]
----
v2.0/Things?$skip=5
----

.Resource pattern returning the third and fourth Observation entities from the collection of all Observation entities when the collection is sorted by the resultTime property in ascending order.
[source,text]
----
v2.0/Observations?$skip=2&$top=2&$orderby=resultTime
----


[[count]]
==== $count

The `$count` system query option with a value of `true` specifies that the total count of items within an EntitySet matching the request SHALL be returned along with the result.
A `$count` query option with a value of `false` specifies that the service SHALL not return a count.

The service SHALL return an HTTP Status code of 400 Bad Request if a value other than `true` or `false` is specified.

The `$count` system query option SHALL ignore any `$top`, `$skip`, or `$expand` query options, and SHALL return the total count of results across all pages including only those results matching any specified `$filter`.

Clients should be aware that the count returned inline may not exactly equal the actual number of items returned, due to latency between calculating the count and enumerating the last value or due to inexact calculations on the service.

For requests to an EntitySet, the count is returned in the `@count` property of the returned object.
When a count is requested on an expanded EntitySet, the count is returned in the `<navigationlink name>@count` property of the containing Entity.

Note: Adapted from OData 4.01-Protocol 11.2.6.5


[[orderby]]
==== $orderby

The `$orderby` system query option specifies the order in which items are returned from the service.
The value of the `$orderby` system query option SHALL contain a comma-separated list of expressions whose primitive result values are used to sort the items.
A special case of such an expression is a property path terminating on a primitive property.

The expression MAY include the suffix `asc` for ascending or `desc` for descending, separated from the property name by one or more spaces.
If asc or desc is not specified, the service SHALL order by the specified property in ascending order.

Null values SHALL come before non-null values when sorting in ascending order and after non-null values when sorting in descending order.

Items SHALL be sorted by the result values of the first expression, and then items with the same value for the first expression SHALL be sorted by the result value of the second expression, and so on.

Note: Adapted from OData 4.01-Protocol 11.2.6.2

.Resource pattern returning all Observations ordered by the result property in ascending order.
[source,text]
----
v2.0/Observations?$orderby=result
----

.Resource pattern returning all Observations ordered by the id property of the linked Datastream entry in descending order, then by the phenomenonTime property of Observations in ascending order.
[source,text]
----
v2.0/Observations?$orderby=Datastreams/id desc, phenomenonTime
----


[[filter]]
==== $filter

The `$filter` option can be used to filter the entities returned by a request to any EntitySet.
The expression specified with $filter is evaluated for each entity in the collection, and only items where the expression evaluates to true SHALL be included in the response.
Entities for which the expression evaluates to false or to null, or which reference properties that are unavailable due to permissions, SHALL be omitted from the response.

[Adapted from Data 4.01-URL Conventions 5.1.1]

The expression language that is used in $filter operators SHALL support references to properties and literals.
The literal values SHALL be strings enclosed in single quotes, numbers, boolean values (true or false), null, datetime values as ISO 8601 time string, duration values or geometry values.
Encoding rules for constants are listed in <<constants_encoding_rules>>
Properties of Entities are addressed by their name.

Note: Adapted from OData 4.01-Protocol 11.2.6.1


.Observations of Datastream 42 that have a result greater than 5.
[source,text]
----
v2.0/Datastreams(42)/Observations?$filter=result gt 5
----

.Locations inside a given area.
[source,text]
----
v2.0/Locations?$filter=st_within(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')
----

Sub-proprties of complex properties are addressed using the complex property name, followed by a `/`, followed by the sub-property name.

.Observations with a valid time that started before the given timestamp.
[source,text]
----
v2.0/Observations?$filter=validTime/start lt 2012-12-03T07:16:23Z
----

Entities can be filtered on properties of related entities by using the navigationProperty, followed by a `/`, followed by a property of the related entity.
This can be used recursively.
For filtering on properties of entities in a related EntitySet see the `any()` function.

.Observations of all Datastreams that are named Temperature.
[source,text]
----
v2.0/Observations?$filter=Datastream/name eq 'Temperature'
----

.Observations of all Things that are named House 1.
[source,text]
----
v2.0/Observations?$filter=Datastream/Thing/name eq 'House 1'
----


[[filter_operations]]
===== Built-in filter operations

The OGC SensorThings API supports a set of built-in filter operations, as described in the following table.
These built-in filter operator usages and definitions follow the [OData Version 4.01. Part 1: Protocol 11.2.6.1.1] and [OData Version 4.01 ABNF].
The operator precedence is described in [OData Version 4.01. Part 2: URL Conventions Section 5.1.1.17].



[#tab-built-in-filter-operators,reftext='{table-caption} {counter:table-num}']
.Built-in Filter Operators
[cols="<15,<25,<60a",options="header"]
|===
|Operator |Description |Example

3+|**Comparison Operators**

|eq
|Equal
|`+/Datastreams?$filter=resultType/type eq 'Quantity'+`

|ne
|Not equal
|`+/Datastreams?$filter=resultType/type ne 'Quantity'+`

|gt
|Greater than
|`+/Observations?$filter=result gt 20.0+`

|ge
|Greater than or equal
|`+/Observations?$filter=result ge 20.0+`

|lt
|Less than
|`+/Observations?$filter=result lt 100+`

|le
|Less than or equal
|`+/Observations?$filter=result le 100+`

|`+in+`
|Containment
|- `+/Things?$filter=properties/type in ('Room','Corridor')+` +
Where `properties/type` is a string.
- `+/Things?$filter='Vehicle' in properties/tags+` +
Where `proprties/tags` is an array of strings.

3+|**Logical Operators**

|and
|Logical and
|`+/Observations?$filter=result le 3.5 and FeatureOfInterest/id eq 1+`

|or
|Logical or
|`+/Observations?$filter=result gt 20 or result le 3.5+`

|not
|Logical negation
|`+/Things?$filter=not startswith(description,'test')+`

3+|**Arithmetic Operators**

|add
|Addition
|
- `+/Observations?$filter=result add 5 gt 10+`
- `+/Observations?$filter=validTime gt now() add duration'PT1H'+`

|sub
|Subtraction
|
- `+/Observations?$filter=result sub 5 gt 10+` +
- `+/Observations?$filter=phenomenonTime gt now() sub duration'P1D'+`

|mul
|Multiplication
|`+/Observations?$filter=result mul 2 gt 2000+`

|div
|Division
|`+/Observations?$filter=result div 2 gt 4+`

|mod
|Modulo
|`+/Observations?$filter=result mod 2 eq 0+`

3+|**Grouping Operators**

|( )
|Precedence grouping
|`+/Observations?$filter=(result sub 5) mul 2 gt 10+`
|===


[[query_functions]]
===== Built-in query functions

The OGC SensorThings API supports a set of functions that can be used with the $filter or $orderby query operations.
The following table lists the available functions and they follows the OData Canonical function definitions listed in link:https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_CanonicalFunctions[OData Version 4.01 Part 2: URL Conventions, Section 5.1.1.4].

In order to support spatial relationship functions, SensorThings API defines nine additional geospatial functions based on the spatial relationship between two geometry objects.
The spatial relationship functions are defined in the OGC Simple Feature Access specification [OGC 06-104r4 part 1, clause 6.1.2.3]. The names of these nine functions start with a prefix st_ following the OGC Simple Feature Access specification [OGC 06-104r4].
In addition, the Well-Known Text (WKT) format is the default input geometry for these nine functions.

In some cases the service may not have enough information to deduce the types of parameters used in functions.
This may, for instance, happen when combining two values from json objects, or attributes of type `ANY`.
In such cases, the `cast` function can be used.


[#tab-built-in-query-functions,reftext='{table-caption} {counter:table-num}']
.Built-in Query Functions
[cols="<30a,<60a",options="header"]
|===
|Function |Example

2+|**String Functions**

|`+bool substringof(string p0, string p1)+`
|`+substringof('Sensor Things',description)+`

|`+bool endswith(string p0, string p1)+`
|`+endswith(description,'Things')+`

|`+bool startswith(string p0, string p1)+`
|`+startswith(description,'Sensor')+`

|`+int length(string p0)+`
|`+length(description) eq 13+`

|`+int indexof(string p0, string p1)+`
|`+indexof(description,'Sensor') eq 1+`

|
- `+string substring(string p0, int p1)+`
- `+string substring(string p0, int p1, int p2)+`

|
- `+substring(description,1) eq 'ensor Things'+`
- `+substring(description,2,4) eq 'nsor'+`

|`+string tolower(string p0)+`
|`+tolower(description) eq 'sensor things'+`

|`+string toupper(string p0)+`
|`+toupper(description) eq 'SENSOR THINGS'+`

|`+string trim(string p0)+`
|`+trim(description) eq 'Sensor Things'+`

|`+string concat(string p0, string p1)+`
|`+concat(concat(unitOfMeasurement/symbol,', '), unitOfMeasurement/name) eq 'degree, Celsius'+`

2+|**Date Functions**

|`+int year+`
|`+year(resultTime) eq 2015+`

|`+int month+`
|`+month(resultTime) eq 12+`

|`+int day+`
|`+day(resultTime) eq 8+`

|`+int hour+`
|`+hour(resultTime) eq 1+`

|`+int minute+`
|`+minute(resultTime) eq 0+`

|`+int second+`
|`+second(resultTime) eq 0+`

|`+int fractionalseconds+`
|`+second(resultTime) eq 0+`

|`+int date+`
|`+date(resultTime) ne date(validTime)+`

|`+time+`
|`+time(resultTime) le validTime+`

|`+int totaloffsetminutes+`
|`+totaloffsetminutes(resultTime) eq 60+`

|`+now+`
|`+resultTime ge now()+`

|`+mindatetime+`
|`+resultTime eq mindatetime()+`

|`+maxdatetime+`
|`+resultTime eq maxdatetime()+`

2+|**Math Functions**

|`+round+`
|`+round(result) eq 32+`

|`+floor+`
|`+floor(result) eq 32+`

|`+ceiling+`
|`+ceiling(result) eq 33+`

2+|**Geospatial Functions**

|`+double geo.distance(Point p0, Point p1)+`
|`+geo.distance(location, geography'POINT (30 10)')+`

|`+double geo.length(LineString p0)+`
|`+geo.length(geography'LINESTRING (30 10, 10 30, 40 40)')+`

|`+bool geo.intersects(Point p0, Polygon p1)+`
|`+geo.intersects(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')+`

2+|**Spatial Relationship Functions**

|`+bool st_equals+`
|`+st_equals(location, geography'POINT (30 10)')+`

|`+bool st_disjoint+`
|`+st_disjoint(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')+`

|`+bool st_touches+`
|`+st_touches(location, geography'LINESTRING (30 10, 10 30, 40 40)')+`

|`+bool st_within+`
|`+st_within(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')+`

|`+bool st_overlaps+`
|`+st_overlaps(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))')+`

|`+bool st_crosses+`
|`+st_crosses(location, geography'LINESTRING (30 10, 10 30, 40 40)')+`

|`+bool st_intersects+`
|`+st_intersects(location, geography'LINESTRING (30 10, 10 30, 40 40)')+`

|`+bool st_contains+`
|`+st_contains(location, geography'POINT (30 10)')+`

|`+bool st_relate+`
|`+st_relate(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))', 'T********')+`

2+|**Collection Functions**

|`+bool any()+`
|`+Observations/any(o: o/result gt 5 and o/phenomenonTime gt 2024-01-01T00:00:00Z)+`

2+|**Type Functions**

|`+type cast(expression,type)+`
|`+cast(result,Edm.Decimal) gt cast(Datastream/properties/threshold,Edm.Decimal)+`
|===


[[any]]
===== Any

The `any()` operator applies a boolean expression to each member of a collection and returns true if the expression returns true for any member of the collection.
The any operator can be used by adding a slash and the `any` keyword after a filter path ending in an EntitySet.
The argument of the any operator is a case-sensitive, alphanumeric lamda variable name, followed by a colon (`:`), followed by a boolean expression that can use the defined variable to access properties of the entities in the collection.

Path expressions not prefixed by the lambda variable are evaluated in the context of the collection that is the target of the `$filter` containing the any operator.

.Request for all Datastreams that have at least one Observation that has both a result greater than the threshold custom property in the containing Datastream, and a phenomenonTime after 2024-01-01 00:00:00Z
[source,text]
----
Datastreams?$filter=Observations/any(o: o/result gt properties/threshold and o/phenomenonTime gt 2024-01-01T00:00:00Z)
----

In the example above, the `properties/threshold` path is evaluated in the context of the Datastreams collection being filtered.

.Request for all Things that both have a Datastream measuring NO2 and a Datastream measuring O3
[source,text]
----
Things?$filter=Datastreams/any(d1: d1/ObservedProperty/name eq 'NO2') and Datastreams/any(d2: d2/ObservedProperty/name eq 'O3')
----


[EDITOR]
====
    - time interval functions?
    - ...
====


[[param_format]]
==== $format

The format of the data returned by read request can be controlled with the `$format` query option.
The default value for the `$format` option is `application/json`.

[[format_json]]
===== application/json

$format=application/json;metadata=full


[[server_driven_pagination]]
==== Server driven pagination

Responses that include only a partial set of the items identified by the request URL SHALL contain a link that allows retrieving the next partial set of items.
This link is called a nextLink; its representation is format-specific.
The final partial set of items (the last page) SHALL NOT contain a nextLink.

The nextLink annotation indicates that a response is only a subset of the requested collection of entities or collection of entity references.
It contains a URL that allows retrieving the next subset of the requested collection.

SensorThings clients SHALL treat the URL of the nextLink as opaque, and SHALL NOT append system query options to the URL of a next link.
Services may disallow a change of format on requests for subsequent pages using the next link.

Note: Adapted from OData 4.01-Protocol 11.2.6.7

