== HTTP Interface Bindings

The HTTP Bindings specify how access the SensorThings API using the HTTP protocol.

The actions that can be executed on resources, as defined in the <<abstract_api>> are mapped to HTTP Methods as defined in table <<http-method-mapping>>.

[#http-method-mapping,reftext='{table-caption} {counter:table-num}']
.Mapping of abstract request types to HTTP Methods.
[width="80%",cols="<,<",options="header"]
|====
| *Request type*
| *HTTP Method*

| Read
| GET

| Create
| POST

| Update
| PATCH

| Replace
| PUT

| Delete
| DELETE

| Execute
| POST
|====

Content for Create, Update, Replace or Execute requests is passed in the body of the HTTP request.

Request parameters (such as `prefer`, `content-type` and `location`)  are passed as Headers.

HTTP HEAD and OPTIONS requests are treated as normal GET requests, but don't return data.
If a GET request with the same URL and headers would return an error, the HEAD or OPTION requests also returns this error.

EDITOR: point to W3 standards


=== Cross Origin Resource Sharing

=== Authentication & Authorization

