=== Modifying Data

==== Introduction

This section describes how to create, update and delete Entities.
Details on how to send create, update and delete requests and how responses are received are described in the protocol bindings sections.

The content type of data sent to a service must be `application/json`, unless otherwise specified.


[requirements_class]
.Modifying Data
====
[%metadata]
identifier:: {identifier}/req-class/api/cud
obligation:: requirement
subject:: Interface Binding
requirement:: {identifier}/req/api/cud/advertisement
requirement:: {identifier}/req/api/cud/create
requirement:: {identifier}/req/api/cud/deep_insert
requirement:: {identifier}/req/api/cud/update
requirement:: {identifier}/req/api/cud/replace
requirement:: {identifier}/req/api/cud/deep_update
requirement:: {identifier}/req/api/cud/json_patch
requirement:: {identifier}/req/api/cud/return_value
requirement:: {identifier}/req/api/cud/update_relations
requirement:: {identifier}/req/api/cud/delete
requirement:: {identifier}/req/api/cud/filtered_delete
====


[requirement]
.Create, Update, Delete
====
[%metadata]
identifier:: {identifier}/req/api/cud/advertisement

A service that supports data modification SHALL advertise the requirements class `{identifier}/req-class/api/cud` in its service document. 
====


[[cud_create]]
==== Creating Entities

Entities can be created with a create request to an URI pattern that addresses an entity set (<<pattern_entityset>> or <<pattern_entityset_related>>).
The content of the "create" request is the JSON encoded representation of the entity to be created.

If the inline representation contains a value for a computed attribute (i.e., `id`), the service ignores that value when creating the entity.

When the URI pattern is of the related entity set type (<<pattern_entityset_related>>), the created entity is automatically linked to the parent entity of the entity set the create request is sent to.

Relations to existing entities can be created by providing the entity-id (selfLink) of the existing entities.
If a conflicting value for a relation exists in the URI and the content of the request, the value from the URI takes priority.


.Sending a create request to `v2.0/Things(5)/Datastreams` with the given content will create a Datastream, linked to Thing 5, Sensor 2 and the ObservedProperty that matches the definition in the resultType.
[source,json]
----
{
  "name": "Oven temperature",
  "description": "This is a datastream measuring the air temperature in an oven.",
  "resultType": {
    "type": "Quantity",
    "label": "Oven temperature",
    "definition": "ObservedProperties(1)",
    "uom": { "code": "Cel", "label": "degree Celsius", "symbol": "°C" }
  },
  "Sensor": {"@id": "Sensors(2)"}
}
----


[requirement]
.Creating Entities
====
[%metadata]
identifier:: {identifier}/req/api/cud/create

A service that supports data modification SHALL support creating entities as described in section <<cud_create>>.
====


[[cud_deep_insert]]
==== Deep Insert

A "create" request can have related entities embedded in-line, to be created alongside the main entity.
Such a "create" request is referred to as a "deep insert".

On success, the service creates all entities and relates them.
On failure, the service does not create any of the entities.

.Sending a "create" request to `v2.0/Things` with the given content will create a Thing with its Location and a Datastream with an associated Sensor. The Datastream will automatically be linked to the ObservedProperty that matches the definition in the resultType. 
[source,json]
----
{
  "description": "This an oven with a temperature datastream.",
  "name": "oven",
  "Locations": [
    {
      "name": "CCIT",
      "description": "Calgary Centre for Innovative Technologies",
      "encodingType": "application/geo+json",
      "location": {
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [10,10]
        }
      }
    }
  ],
  "Datastreams": [
    {
      "name": "oven temperature",
      "description": "This is a datastream for an oven’s internal temperature.",
      "resultType": {
        "type": "Quantity",
        "label": "Oven temperature",
        "definition": "ObservedProperties(1)",
        "uom": { "code": "Cel", "label": "degree Celsius", "symbol": "°C" }
      },
      "Sensor": {
        "name": "DS18B20",
        "description": "DS18B20 is an air temperature sensor…",
        "encodingType": "application/pdf",
        "metadata": "http://datasheets.maxim-ic.com/en/ds/DS18B20.pdf"
      }
    }
  ]
}
----


[requirement]
.Deep Insert
====
[%metadata]
identifier:: {identifier}/req/api/cud/deep_insert

A service that supports data modification SHALL support creating entities as described in section <<cud_deep_insert>>.
====


[[cud_updating_entities]]
==== Updating Entities

Entities can be updated with an update request to an URI pattern that addresses a single entity (<<pattern_entity>> or <<pattern_entity_related>>).

An update request must contain only those updatable attributes of the entity that are to be changed.
Attributes that are not present in the update request are not changed, though server-generated attributes may be updated by the server as a result of the change request.

For even finer grained update control, or updates that are safe from concurrent modification by other users, see <<cud_json_patch>>.


.Sending an update request to `v2.0/Things(1)` with the given content will update the name of Thing 1,  and leave all other fields unchanged.
[source,json]
----
{
  "name": "My Updated Oven"
}
----


[requirement]
.Updating Entities
====
[%metadata]
identifier:: {identifier}/req/api/cud/update

A service that supports data modification SHALL support updating entities as described in section <<cud_updating_entities>>.
====



[[cud_replacing_entities]]
==== Replacing Entities

Entities can be replaced with a replace request to an URI pattern that addresses a single entity (<<pattern_entity>> or <<pattern_entity_related>>).

A "replace" request must contain as content the complete entity to be replaced.
Entity attributes that are not present in the replace request are removed from the entity.
Navigation attributes are not affected.


.Sending a replace request to `v2.0/Things(1)` with the given content will update the name of Thing 1,  and remove all other fields.
[source,json]
----
{
  "name": "My Updated Oven"
}
----


[requirement]
.Replacing Entities
====
[%metadata]
identifier:: {identifier}/req/api/cud/replace

If a service advertises this requirement in the service document then the service SHALL support replacing entities as described in section <<cud_replacing_entities>>.
====


[[cud_deep_update]]
==== Deep Update

The content of an update request may contain nested entities to be updated or created and entity references to be linked, that specify the full set of entities to be linked.

On success, the server makes all the changes. On failure, the server makes none of the changes.

The server must ensure data integrity and return an error if the update breaks integrity.
For example, an update request that specifies fewer Datastreams on a Thing than the Thing currently has cannot be valid.
This update would remove Datastreams from the Thing, but a Datastream MUST have a Thing.
To remove a Datastream from a Thing, either the Datastream must be explicitly deleted, or linked to a different Thing.


.Sending an update request to `v2.0/Things(1)` with the given content will update the name of Thing 1, create a new Location, and set the Locations of the Thing to the newly created Location and existing Location 1, removing any old Location(s).
[source,json]
----
{
  "name": "My Updated Oven",
  "Locations": [
    {
      "name": "New Location of my Oven",
      "description": "It fits much better here",
      "encodingType": "application/geo+json",
      "location": {
        "type": "Point",
        "coordinates": [-114.061,51.051]
      }
    },
    {
      "@id": "Locations(1)"
    }
  ]
}
----


[requirement]
.Deep Update
====
[%metadata]
identifier:: {identifier}/req/api/cud/deep_update

If a service advertises this requirement in the service document then the service SHALL support the deep updating of entities as described in section <<cud_deep_update>>.
====


[[cud_json_patch]]
==== JSON-Patch

Services MAY additionally support JSON PATCH format <<RFC6902>> to express a sequence of operations to apply to an entity.

Entities can be updated with a json-patch  request to an URI pattern that addresses a single entity (<<pattern_entity>> or <<pattern_entity_related>>).

The content-type of the data in a json-patch request is `application/json-patch+json`.

The paths in the json-patch request must not contain navigation attributes.

.Sending a json-patch request to `v2.0/Things(1)` with the given content will set the value of `properties/status` to `active` only if the current value of `properties/status` to `inactive` and return a `Conflict` error otherwise.
[source,json]
----
[
  { "op": "test", "path": "/properties/status", "value": "inactive" },
  { "op": "replace", "path": "/properties/status", "value": "active" }
]
----


[requirement]
.JSON-Patch
====
[%metadata]
identifier:: {identifier}/req/api/cud/json_patch

If a service advertises this requirement in the service document then the service SHALL support the updating of entities with JSON-Patch requests as described in section <<cud_json_patch>>.
====


[[cud_return_value]]
==== Return Value

The returned value for an entity modification request depends on the `prefer` request parameter, with the possible values `return=minimal` (default) and `return=representation`.

If the `prefer` request parameter is not present, or does not contain a value for `return`, or has `return=minimal` then, for create requests, the entity-id (selfLink) of the created entity is returned as a value, and no content is returned.
For update requests no content is returned.

If the `prefer` request parameter has `return=representation`, then the created or updated resource is returned, optionally taking `$expand`, `$select` and `$format` query options into account.


[requirement]
.Return Value
====
[%metadata]
identifier:: {identifier}/req/api/cud/return_value

A service that supports data modification SHALL return data to modification requests as described in section <<cud_return_value>>.
====


[[cud_edit_relations]]
==== Modifying Relations

Single-valued navigation attributes (<<pattern_entity_related>>) can be updated by sending a replace request to the association link (<<pattern_relation>>).
The "replace" request must contain an entity reference to the single entity that should be the new target of the navigation attribute.


.Example of a request setting the UltimateFeatureOfInterest of `Datastream 1` to `Feature 2`.
[source,text]
----
replace http://host/service/Datastreams(1)/UltimateFeatureOfInterest/$ref
  {"@id": "Features(2)"}
----


Single-valued navigation attributes can be un-linked by sending a delete request to the association link.
This will not remove the entities, only remove the link between the entities.

.Example of a request removing the UltimateFeatureOfInterest from `Datastream 1`.
[source,text]
----
delete http://host/service/Datastreams(1)/UltimateFeatureOfInterest/$ref 
----


EntitySet navigation attributes (<<pattern_entityset_related>>) can be extended with a new link to an existing entity by sending a create request to the association link of the navigation attribute.
The "create" request contains an entity reference to the single entity to be added to the set of related entities.
If the two entities are already related, the operation has no effect and returns a succes.

.Example of a request adding `FeatureType 3` as FeatureType of `Feature 1`.
[source,text]
----
create http://host/service/Feature(1)/FeatureTypes/$ref
  {"@id": "FeatureTypes(3)"}
----


The complete list of relations in an EntitySet-type navigation attribute can be replaced by sending a replace request to the association link of the navigation attribute.
The replace request must contain a list of entity references, like the one returned by a read request to the association link of the navigation attribute.

.Example changing the set of `FeatureTypes` of `Feature 1` to contain exactly `FeatureType 1` and `FeatureType 2`.
[source,text]
----
replace http://host/service/Feature(1)/FeatureTypes/$ref
  {"value": [
    {"@id": "FeatureTypes(1)"},
    {"@id": "FeatureTypes(2)"}
  ]}
----

A single relation can be removed from an EntitySet-type navigation attribute by either sending a delete request to the association link of the relation, or by sending a delete request to the association link of the navigation attribute, with an `$id` parameter specifying the self-link (absolute or relative) of the target Entity.

.Examples of the two ways to remove `FeatureType 2` from an EntitySet-typed navigation attribute `FeatureTypes` of `Feature 1`.
[source,text]
----
delete http://host/service/Feature(1)/FeatureTypes(2)/$ref
delete http://host/service/Feature(1)/FeatureTypes/$ref?$id=../../FeatureTypes(2)
----


All relations can be removed from an EntitySet-type navigation attribute by sending a delete request to the association link of the navigation attribute.

.Example removing all `FeatureTypes` from `Feature 1`.
[source,text]
----
delete http://host/service/Feature(1)/FeatureTypes/$ref
----

For any change of relations data integrity MUST be maintained.
If a request breaks data integrity, then an INVALID REQUEST error is returned.
On a successful change, the server returns an empty response.


[requirement]
.Modifying Relations
====
[%metadata]
identifier:: {identifier}/req/api/cud/update_relations

A service that supports data modification SHALL support relation-modification requests as described in section <<cud_edit_relations>>.
====


[[cud_deleting_entities]]
==== Deleting Entities

Entities can be removed from a service by sending a delete request to an URI pattern that addresses a single entity (<<pattern_entity>> or <<pattern_entity_related>>).

Services SHALL implicitly remove relations to and from an entity when deleting it; clients need not delete the relations explicitly.

The server must ensure data integrity and delete any entities that depend on the entity being deleted.
For example, deleting a Thing would also delete the HistoricalLocations and Datastreams that depend on it, and the Observations in those Datastreams, but not the Locations of the Thing, since Locations can exist without a relation to a Thing.


[requirement]
.Deleting Entitites
====
[%metadata]
identifier:: {identifier}/req/api/cud/delete

A service that supports data modification SHALL support delete requests as described in section <<cud_deleting_entities>>.
====


[[cud_deleting_entities_filtered]]
==== Deleting Entities by Filter

Sending individual delete requests for each entity to be deleted is very inefficient when many entities need to be deleted.
For example for maintenance, when all Observations older than a certain date need to be deleted, a client would first have to send a read request to find all entities older than the threshold data, and then sent a delete request for each of the returned entities.
To make deleting a large number of entities more efficient, a server may implement filtered-delete capability.

When filtered-delete is supported, a client can send a delete request to an URI pattern that addresses an entity set (<<pattern_entityset>> or <<pattern_entityset_related>>) with the $filter option (<<read_options_filter>>).
The server will delete all entities from the set that match the filter.


[requirement]
.Deleting Entities by Filter
====
[%metadata]
identifier:: {identifier}/req/api/cud/filtered_delete

If a service advertises this requirement in the service document then the service SHALL support the mass-deleting of entities as described in section <<cud_deleting_entities_filtered>>.
====


