[[OData-Entity-Model]]
=== OData Entity Model

Every OData service utilizes an entity model which MAY be distributed over several schemas.
The service describes this model through a metadata document accessible by a simple HTTP _GET_ request to the <serviceRoot>/$metadata path.
This chapter describes an overview of the types of entities in the metadata document that will be used to describe the SensorThings API data model and its data model extensions.
The entities listed below are also used to describe the REST and MQTT bindings of the SensorThings API service.

* https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_DataModel 
* https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_EntityModel


The data model consists of the following elements:

* `Entity Type`: named, structured, keyed element that defines the properties and relations of Entities.
  The key of an Entity Type consists of one or more primitive properties of the Entity Type.
* `Entity`: instance of an `Entity Type`.
  An Entity can have only one Entity Type.
* `Primitive Type`: unnamed, unstructured type, such as String, Integer or DateTime.
  https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_PrimitiveTypes
* `Complex Type`: named, structured, keyless, element consisting of a set of named properties.
  Instances of Complex Types can not be accessed outside of the Entity they are contained in.
  A property with a Primitive Type is called a primitive property.
* `Relation`: named connections between Entities.
  Relations defined as `navigation properties` in Entity Types.
  Relations have a cardinality.
* `Properties`: named elements that are part of structured types (Entity Types and Complex Types).
  Properties can be Primitive-, Complex- or Navigation properties.
  Properties defined as part of a structured type (Entity/Complex Type) are `declared properties`.
  A structured type can allow properties that are added dynamically, as long as these `dynamic properties` do not have the same name as a declared property.
  Structured types that allow dynamic properties are called `Open Types`.
* `Entity Set`: a named collection of Entities of the same `Entity Type`.
  Each Entity is uniquely identified among other Entities in the same Entity Set, by its key.
  Entity Sets are the entry points into the data model.
* `Annotation`: additional information attached to model or instance elements.
  annotations can be identified by the `@` character.
  If the annotation starts with the `@` character, then the annotation pertains to the object containing the annotation.
  If the annotation has a property name before the `@` charater, then the annotation pertains the property with that name.
  Annotations are server-generated additional information that a client can use when processing the data.
  A client can ignore any annotations it does not understand.
  The default annotations can be found in <<tab-common-control-annotations>>.
  Additional annotations may be defined in the service metadata.
* `EntityId`: a globally unique identifier for an Entity.
  If present in Entity representations, the EntityId is specified in the `@id` annotation.

Each Entity has a primary key that is composed of one or more of the `declared properties` of the entity type.
Which properties of the Entity Type make up the primary key of the Entity Type is specified in the service metadata document.
For the data models specified in this document the primary key is always the field `id`, though the data type of the field may vary between services.
In most cases the primary key field will be server generated at the time an Entity is created, but a service may allow for client-specified primary key fields.



EDITOR: Say something about absolute / relative URLs.
Relative to what, and how is this done in MQTT? See https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_RelativeURLs


[[tab-common-control-annotations]]
.Common control annotations
[cols="2a,7a,1a"]
|===
|Name
|Definition
|Data Type

|@context
|The context url contains the metadata document that describes the context of a payload. See <<OData-CSDL>>
|URL

|@id
|The annotation `@id` is the absolute or relative URL of an entity that uniquely resolves to this entity.
|URL

|linkName@navigationLink
|Annotations of the form `linkName@navigationLink` are the relative or absolute URL that retrieves the related entity or entities for the navigation property `linkName`.
|URL
|===


[[OData-CSDL]]
=== OData Common Schema Definition Language

The data model is specified in the metadata document that can be retrieved from the context url.
It is described in a machine-readable way using the OData Common Schema Definition Language.
See https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html

An example can be found in ...



NOTE: Add example.




