== Terms and definitions

=== Party

The entity in the data model that represents a user. A party can be associated to other entities of the data model to express ownership.

=== License

The entity in the data model that represents a well-defined license. Associating a license with a `Multi/Datastream` entity expresses re-use conditions for all observations associated with that `Multi/Datastream` entity.

=== Group

The entity in the data model that allows creation a collection of observations for a particular purpose.

=== Relation

The entity in the data model that allows expressing relationships between two observations or an observation and an external object.

=== Project

The entity in the data model that allows merging `Multi/Datastream` entities together that are required to achieve the objective represented by the project.

=== Ownership

The `Party` entity in the data model allows expressing the right of possession over entity instances. This is the requirement to operate STAplus with multi-user CRUD access. 

=== Abbreviations

API:: Application Programming Interface
CC:: Creative Commons
CRUD:: Create Read Update Delete
DID:: Decentralized Identifier
GDPR:: European General Data Protection Regulation
MQTT:: Message Queuing Telemetry Transport
STA:: Sensor Things API
STAplus:: Sensor Things API "plus" extension