[bibliography]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

* [[[OGC18-088,OGC SensorThings API Part 1: Sensing Version 1.1]]], OGC, _OGC SensorThings API Part 1: Sensing Version 1.1_, OGC (2021), https://docs.ogc.org/is/18-088/18-088.html
* [[[OGC20-040r3,OGC Abstract Specification Topic 21: Discrete Global Grid Systems]]], OGC, _OGC Abstract Specification Topic 21: Discrete Global Grid Systems — Part 1 Core Reference system and Operations and Equal Area Earth Reference System_, OGC (2021), https://docs.ogc.org/as/20-040r3/20-040r3.html
* [[[OGC22-022r2,OGC SensorThings API Extension: STAplus 1.0.1 corrigendum]]], OGC, _OGC SensorThings API Extension: STAplus 1.0.1 corrigendum_, OGC (2026)

<<OGC22-022r2>> applies to an implementation that claims the <<conformance_class_staplus>> Conformance Class. It replaces STAplus 1.0 (OGC 22-022r1). The Party Requirements Class inherited by this Standard is `{identifier-staplus}/req-class/party`.
