.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium SHALL not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

The SensorThings API Extension: WebSub Asynchronous Messaging Standard (STA-WebSub) defines an additional SensorThings API v1.1 capability to subscribe to any SensorThings API endpoint with a request URL for receiving notifications when the result of the query changes (commonly because new data has been received). STA-WebSub is based on the W3C WebSub Recommendation (see <<W3CWebSub>>). 

The STA-WebSub Standard defines how to discover a request URL that can be subscribed to, how to subscribe using the URL, and how notifications will be received. This Standard requires that a Webhook is implemented by consumers. This is required as the way to receive the notifications of the SensorThings API instance.

The use of STA-WebSub improves the flexible use of SensorThings API services for building asynchronous workflows. The ability to define trigger conditions and to specify the event data structure that is pushed to a Webhook over HTTP(S) POST enables a fit-for-purpose processing of events using workflows. For example, used in combination with a WebHub and WebSockets, this Standard supports Web-Applications running in any modern Web Browser to subscribe and receive observations and measurement updates anywhere HTTP(S) is allowed. There is no need for any browser extensions. As an example, in an air quality scenario, it is possible to build a JavaScript application that alerts the subscribed population of abnormal levels of pollutants in their area in real time on their mobile phones. Another example in the weather domain is to trigger a process, associated to the Webhook that recalculates a weather forecast as soon as enough new data is received via an update.

STA-WebSub introduces two advantages. Firstly, a subscriber can first fetch data from a SensorThings API service (see <<OGC18088>>) and then use the same identical URL to subscribe for updates. This avoids the need for any subscriber to poll a SensorThings API service. Instead, any updates - according to the URL used - get submitted to the subscriber's Webhook when the update event is triggered. Secondly, the SensorThings API MQTT protocol does not need to be exposed to 3rd parties for receiving updates. With STA-WebSub, the MQTT protocol can remain internal (hidden) between the SensorThings API service and the associated STA-WebSub Hub(s).

To leverage all capabilities of the STA-WebSub Standard, a SensorThings API service is required to extend the MQTT topic pattern to include `$filter` and `$expand` capabilities via Open Data Protocol (ODATA) query parameters: Subscribing for updates by defining actual triggering conditions is supported via `$filter`. Also using the ODATA query parameter `$select` and `$expand` in addition also supports a subscriber to get exactly the data and structure as needed (fit for purpose).

For controlling subscriptions based on business or governance policies, authentication and access control may be implemented in the discovery functionality.

Building trust into the received updates can be established via the W3C WebSub's HMAC option as the HMAC option provides a way for a subscriber to verify that a content distribution from a hub is authentic and has not been tampered with.

== Security considerations
Any event processing system is susceptible to denial of service attacks. This can happen when too many clients subscribe to topics with high frequency updates (`chatty topics`) or too many updates are received. For example, subscription to the MQTT topic `v1.1/Observations` brings the danger that the SensorThings API service cannot deliver all events to all subscribed clients when the update frequency gets too high. Additionally, the subscriber may get flooded with event data sent by the Hub. 

Any implementation that supports the use of ODATA query parameters is particularly susceptible to denial of service due to the complexity of an ODATA query. An attacker could achieve a denial of service attack by subscribing using a very complex topic URL including an ODATA query. To mitigate such an attack, an implementation should carefully analyze the query parameters of a topic URL before accepting the subscription request.

Any SensorThings API service should deny MQTT update subscriptions that do not origin from an associated Hub. This guarantees that an attacker cannot simply bypass the Hub and swamp the SensorThings API service directly with bogus update subscriptions.

The proper network separation of SensorThings API service and the Hub, such as in a fast private network, enables establishing a clever load distribution between a SensorThings API service and as many Hubs as needed. This self-adaptivity to scaling mitigates the likelihood for denial of service attacks even with many subscribed clients and complex topics.

In any case, the Hub must validate a subscription with the STA-WebSub Service. This can be achieved via the regular discovery request (HTTP Head request with the topic URL).

To prevent bogus subscriptions, a Hub may require authentication for the subscription management.

The W3C WebSub recommends that the subscriber's callback URL is 'not easily guessable' and that the callback URL is refreshed whenever a subscription is renewed. Following this recommendation makes the use of other authentication mechanisms, such as the use of an API key, unnecessary. An API key is a unique identifier that authenticates a user or application to an API instance. However, for computing environments where it is not possible or too difficult to follow this recommendation, the use of `API-Key` or `X-API-Key` HTTP header can protect a static callback endpoint URL. Likewise, when refreshing the callback URL, the subscriber updating the API key value with a strong random value each time a subscription is renewed is strongly recommended. 

Leveraging an API key over HTTPS callback URLs may be preferred over the use of `X-Hub-Signature` when the notification data size is large. The clear advantage is that neither the Hub nor the Subscriber must calculate a hash over the notification data. Also, the use of API key over HTTPS is equivalent to HMAC. Different API keys for subscriptions identifies the Hub, thereby providing authenticity. The use of HTTPS ensures content integrity.

== Submitters

All questions regarding this submission should be directed to the editors or the submitters:

[%autowidth,cols="3*"]
|===
|Name |Representing |OGC Member

|Andreas Matheus
|Secure Dimensions GmbH
|Yes

|Joan Maso
|Centre de Recerca Ecològica i Aplicacions Forestals (CREAF)
|Yes

|Hylke van der Schaaf
|Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.
|Yes

|===