.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.



[abstract]
== Abstract

The OGC SensorThings API provides an open, geospatial-enabled and unified way to interconnect Internet of Things (IoT) devices, data, and applications over the Internet.
It contains a core data model, an abstract REST API for accessing data, and bindings for this API for HTTP and MQTT.

The data model is an implementation of the core concepts of the Observations, Measurements and Samples OGC/ISO specification.
The API allows for creating, reading, updating and deleting all parts of the data model.
It also features extensive filtering and response-customisation capabilities.

Even though the SensorThings API was initially designed for IoT, the previous versions have shown to be wel suited for any use case involving time-series data.

