[[meta-data-model]]
== Meta Data Model

This chapter describes the SensorThings API meta model that is used to describe the SensorThings API data model and its data model extensions.
The meta model is also used to specify the rest and pub-sub apis.
It is based on the ODATA Meta Model 

* https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_DataModel 
* https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_EntityModel


The meta model consists of the following elements:

* `Entity Type`: named, structured, keyed element that defines the properties and relations of Entities.
  The key of an Entity Type consists of one or more primitive properties of the Entity Type. 
* `Entity`: instance of an `Entity Type`. An Entity can have only one Entity Type.
* `Primitive Type`: unnamed, unstructured type, such as String, Integer or DateTime.
  https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_PrimitiveTypes
* `Complex Type`: named, structured, keyless, element consisting of a set of named properties. Instances of Complex Types can not be accessed outside of the Entity they are contained in.
  A property with a Primitive Type is called a primitive property.
* `Relation`: named connections between Entities. Relations defined as `navigation properties` in Entity Types. Relations have a cardinality.
* `Properties`: named elements that are part of structured types (Entity Types and Complex Types).
  Properties can be Primitive-, Complex- or navigation properties.
  Properties defined as part of a structured type (Entity/Complex Type) are `declared properties`.
  A structured type can allow properties that are added dynamically, as long as these `dynamic properties` do not have the same name as a declared property.
  Structured types that allow dynamic properties are called `Open Types`.
* `Entity Set`: a named collection of Entities of the same `Entity Type`.
  Each Entity is uniquely identified among other Entities in the same Entity Set, by its key.
  Entity Sets are the entry points into the data model.
* `Annotation`: additional information attached to model or instance elements.
  annotations can be identified by the `@` character.
  If the annotation starts with `@` the annotation pertains the object containing the annotation.
  If the annotation has a property name before the (`@`) the annotation pertains the property with that name.
  Annotations are server-generated additional information that a client can use when processing the data.
  A client can ignore any annotations it does not understand.
  The default annotations can be found in <<tab-common-control-annotations>>.
  Additional annotations may be defined in the service metadata.
* `EntityId`: a globally unique identifier for an Entity.
  If present in Entity representations, the EntityId is specified in the `@id` annotation.


EDITOR: Say something about `id`, primary keys, extensions and server-generated/user-supplied.

EDITOR: Say something about absolute / relative URLs. Relative to what, and how is this done in MQTT? See https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_RelativeURLs


[[tab-common-control-annotations]]
.Common control annotations
[cols="2a,7a,1a"]
|===
|Name |Definition |Data Type

|@context
|The context url contains the metadata document that describes the context of a payload. 
|URL

|@id
|The annotation `@id` is the absolute or relative URL of an entity that uniquely resolves to this entity.
|URL

|linkName@navigationLink
|Annotations of the form `linkName@navigationLink` are the relative or absolute URL that retrieves content of related entities for the navigation property `linkName`.
|URL
|===


[[OData-CSDL]]
=== OData Common Schema Definition Language

The data model is described in a machine-readable way using the OData Common Schema Definition Language.
https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html
The data model is specified in the metadata document that can be retrieved from the context url.



