[[OData-Entity-Model]]
=== OData Entity Model

Every OData service utilizes an entity model which MAY be distributed over several schemas.
The service describes this model through a metadata document accessible by a simple HTTP _GET_ request to the `<serviceRoot>/$metadata` path.
This chapter describes an overview of the types of entities in the metadata document that will be used to describe the SensorThings API data model and its data model extensions.
The entities listed below are also used to describe the REST and MQTT bindings of the SensorThings API service.

This section is base on:

* https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_DataModel 
* https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_EntityModel


The entity model consists of the following elements:

* `Entity Type`: named, structured, keyed element that defines the properties and relations of Entities.
  The key of an Entity Type consists of one or more primitive properties of the Entity Type.
* `Entity`: instance of an `Entity Type`.
  An Entity can have only one Entity Type.
* `Primitive Type`: unnamed, unstructured type, such as String, Integer or DateTime. The full list can be found at:
  https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_PrimitiveTypes
* `Complex Type`: named, structured, keyless, element consisting of a set of named properties.
  Instances of Complex Types can not be accessed outside of the Entity they are contained in.
  A property with a Primitive Type is called a primitive property.
* `Relation`: named connections between Entities.
  Relations defined as `navigation properties` in Entity Types.
  Relations have a cardinality.
* `Properties`: named elements that are part of structured types (Entity Types and Complex Types).
  Properties can be Primitive-, Complex- or Navigation properties.
  Properties defined as part of a structured type (Entity/Complex Type) are `declared properties`.
  A structured type can allow properties that are added dynamically, as long as these `dynamic properties` do not have the same name as a declared property.
  Structured types that allow dynamic properties are called `Open Types`.
* `Entity Set`: a named collection of Entities of the same `Entity Type`.
  Each Entity is uniquely identified among other Entities in the same Entity Set, by its key.
  Entity Sets are the entry points into the data model.
* `Annotation`: additional information attached to model or instance elements.
  annotations can be identified by the `@` character.
  If the annotation starts with the `@` character, then the annotation pertains to the object containing the annotation.
  If the annotation has a property name before the `@` charater, then the annotation pertains the property with that name.
  Annotations are server-generated additional information that a client can use when processing the data.
  A client can ignore any annotations it does not understand.
  The default annotations can be found in <<tab-common-control-annotations>>.
  Additional annotations may be defined in the service metadata.
* `EntityId`: a globally unique identifier for an Entity.
  If present in Entity representations, the EntityId is specified in the `@id` annotation.

Each Entity has a primary key that is composed of one or more of the `declared properties` of the entity type.
Which properties of the Entity Type make up the primary key of the Entity Type is specified in the service metadata document.
For the data models specified in this document the primary key is always the field `id`, though the data type of the field may vary between services.
In most cases the primary key field will be server generated at the time an Entity is created, but a service may allow for client-specified primary key fields.


URLs in documents may be absolute or relative.
Relative URLs are relative to the context URL in the document, or if there is no context url, relative to the request URL.
See https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_RelativeURLs.


[#tab-common-control-annotations,reftext='{table-caption} {counter:table-num}']
.Common control annotations
[width="100%",cols="2a,7a,1a",options="header"]
|===
|Name
|Definition
|Data Type

|@context
|The context url contains the metadata document that describes the context of a payload. See <<OData-CSDL>>
|URL

|@id
|The annotation `@id` is the absolute or relative URL of an entity that uniquely resolves to this entity.
|URL

|linkName@navigationLink
|Annotations of the form `linkName@navigationLink` are the relative or absolute URL that retrieves the related entity or entities for the navigation property `linkName`.
|URL
|===


[[OData-CSDL]]
=== OData Common Schema Definition Language

The data model is specified in the metadata document that can be retrieved from the context url.
It is described in a machine-readable way using the OData Common Schema Definition Language.
See https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html

An example CSDL document describing a service hosting a SensorThings API v2.0 core data model can be found in <<sta-core-csdl-example>>.
A shortened example with comments can be found below.

[[csdl-example-short]]
.A shortened example CSDL definition with only (incomplete) Datastreams and Observations.
[source,json]
----
{
    "$Version": "4.01",  // OData version
    "$EntityContainer": "org.OGC.SensorThingsV2",  // Namespace + . + container name
    "org.OGC": {         // Namespace
        "Datastream": {  // EntityType name
            "$Kind": "EntityType",  // Object is an EntityType
            "$Key": [    // Primary key of the EntityType
                "id"     // Primary key consists of the id field
            ],
            "id": {                   // id field, structural properties have no $Kind
                "$Type": "Edm.Int64"  // Type of the id field
            },                        // Not nullable, but PrimaryKeys are auto generated
            "name": {},   // name field, Default $Type=Edm.String, not nullable
            "properties": {                 // Property properties
                "$Type": "org.OGC.Object",  // custom type defined in org.OGC namespace
                "$Nullable": true           // Nullable, thus Optional
            },
            "phenomenonTime": {               // Property phenomenonTime
                "$Type": "org.OGC.TM_Period", // custom type defined in org.OGC namespace
                "$Nullable": true             // Nullable, thus Optional
            },
            "Observations": {                   // Property Observations
                "$Kind": "NavigationProperty",  // NavigationProperty
                "$Collection": true,            // links to a Set of Entities
                "$Partner": "Datastream",       // inverse link is called Datastream
                "$Type": "org.OGC.Observation", // Target is of type Observation
                "$Nullable": true               // can be an empty set
            }
        },
        "Observation": {            // EntityType name
            "$Kind": "EntityType",  // Object is an EntityType
            "$Key": [               // Primary key of the EntityType
                "id"                // Primary key consists of the id field
            ],
            "id": {                   // id field, structural properties have no $Kind
                "$Type": "Edm.Int64"  // Type of the id field
            },                        // Not nullable, but PrimaryKeys are auto generated
            "result": {
                "$Type": "Edm.Untyped"  // Untyped=can be anything
            },
            "Datastream": {                    // Property Datastream linking to a single Entity
                "$Kind": "NavigationProperty", // is a NavigationProperty
                "$Partner": "Observations",    // inverse relation is called Observations
                "$Type": "org.OGC.Datastream"  //  links to a Datastream
            }                                  // No $Nullable, thus mandatory!
        },
        "Object": {                 // Custom type Object
            "$Kind": "ComplexType", // is a complex type
            "$OpenType": true       // Open, thus can hold user-defined properties
        },
        "TM_Period": {                         // Custom type TM_Period
            "$Kind": "ComplexType",            // is a complex type
            "start": {                         // Has a structural property named start
                "$Type": "Edm.DateTimeOffset"  // that is of type DataTimeOffset
            },                                 // No $Nullable, thus mandatory!
            "end": {                           // Has a structural property named end
                "$Type": "Edm.DateTimeOffset"  // that is of type DataTimeOffset
            }
        },
        "SensorThingsV2": {             // The entity container defining the base entity sets
            "$Kind": "EntityContainer",
            "Datastreams": {                     // The v2.0/Datastreams entitySet
                "$Collection": true,             // is an entity set
                "$Type": "org.OGC.Datastream",   // containing Datastreams
                "$NavigationPropertyBinding": {  // The navigationProperties link to other top-level sets
                    "Observations": "Observations"  // v2.0/Datastreams(x)/Observations are also in v2.0/Observations
                }
            },
            "Observations": {                    // The v2.0/Observations entitySet
                "$Collection": true,             // is an entity set
                "$Type": "org.OGC.Observation",  // containing Observations
                "$NavigationPropertyBinding": {
                    "Datastream": "Datastreams"  // v2.0/Observations(x)/Datastream is also in v2.0/Datastreams
                }
            }
        }
    }
}
----



