=== Modifying Data

This section describes how to create, update and delete Entities.
Deltails on how to send create, update and delete requests and how responses are received are described in the protocol bindings sections.

The content type of data sent to a service must be `application/json`, unless otherwise specified.

==== Creating Entities (EntitySet)

Entities can be created with a create request to an URI pattern that addresses an entity set (<<pattern_entityset>> or <<pattern_entityset_related>>).
The content of the create request is the JSON encoded representation of the entity to be created.

If the inline representation contains a value for a computed property (i.e., `id`), the service ignores that value when creating the entity.

When the URI pattern is of the related entity set type (<<pattern_entityset_related>>), the created entity is automatically linked to the parent entity of the entity set the create request is sent to.

Relations to existing entities can be created by providing the entity-id (selfLink) of the existing entities.
If a conflicting value for a relation exists in the URI and the content of the request, the value from the URI takes priority.


.Sending a create request to `v2.0/Things(5)/Datastreams` with the given content will create a Datastream, linked to Thing 5, Sensor 2 and the ObservedProperty that matches the definition in the resultType.
[source,json]
----
{
  "name": "Oven temperature",
  "description": "This is a datastream measuring the air temperature in an oven.",
  "resultType": {
    "type": "Quantity",
    "label": "Oven temperature",
    "definition": "http://mmisw.org/ont/cf/parameter/air_temperature",
    "uom": { "code": "Cel", "label": "degree Celsius", "symbol": "°C" }
  },
  "Sensor": {"@id": "Sensors(2)"}
}
----


==== Deep Insert

A create request can have related entities embedded in-line, to be created alongside the main entity.
Such a create request is referred to as a "deep insert".

On success, the service creates all entities and relates them.
On failure, the service does not create any of the entities.

.Sending a create request to `v2.0/Things` with the given content will create a Thing with its Location and a Datastream with an associated Sensor. The Datastream will automatically be linked to the ObservedProperty that matches the definition in the resultType. 
[source,json]
----
{
  "description": "This an oven with a temperature datastream.",
  "name": "oven",
  "Locations": [
    {
      "name": "CCIT",
      "description": "Calgary Centre for Innovative Technologies",
      "encodingType": "application/geo+json",
      "location": {
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [10,10]
        }
      }
    }
  ],
  "Datastreams": [
    {
      "name": "oven temperature",
      "description": "This is a datastream for an oven’s internal temperature.",
      "resultType": {
        "type": "Quantity",
        "label": "Oven temperature",
        "definition": "http://mmisw.org/ont/cf/parameter/air_temperature",
        "uom": { "code": "Cel", "label": "degree Celsius", "symbol": "°C" }
      },
      "Sensor": {
        "name": "DS18B20",
        "description": "DS18B20 is an air temperature sensor…",
        "encodingType": "application/pdf",
        "metadata": "http://datasheets.maxim-ic.com/en/ds/DS18B20.pdf"
      }
    }
  ]
}
----



==== Updating Entities (Single Entity)

Entities can be updated with a patch or replace request to an URI pattern that addresses a single entity (<<pattern_entity>> or <<pattern_entity_related>>).
Services MUST support patch requests and MAY support replace requests.

A patch request must contain as content only those updatable attributes of the entity that are to be changed.
Attributes that are not present in the patch request are not changed, though server-generated attributes may be updated by the server as a result of the change request.

A replace request must contain as content the complete entity to be replaced.
Attributes that are not present in the replace request are removed from the entity.

For even finer grained update control, or updates that are safe from concurrent modification by other users, see <<json-patch>>.


.Sending a patch request to `v2.0/Things(1)` with the given content will update the name of Thing 1,  and leave all other fields unchanged.
[source,json]
----
{
  "name": "My Updated Oven"
}
----



[[deep-update]]
==== Deep Update (optional)

The content of a patch request may contain nested entites to be updated or created and entity references to be linked, that specify the full set of entities to be linked.

On succes, the server makes all the changes. On failure, te server makes none of the changes.

The server must ensure data integrity and return an error if the patch would break integrity.
For example, a patch request that specifies fewer Datastreams on a Thing than the Thing currently has can not be valid, since a Datastream MUST have a Thing.
To remove a Datastream from a Thing, either the Datastream must be explicitly deleted, or linked to a different Thing.


.Sending a patch request to `v2.0/Things(1)` with the given content will update the name of Thing 1, create a new Location, and set the Locations of the Thing to the newly created Location, removing any old Location(s).
[source,json]
----
{
  "name": "My Updated Oven",
  "Locations": [
    {
      "name": "New Location of my Oven",
      "description": "It fits much better here",
      "encodingType": "application/geo+json",
      "location": {
        "type": "Point",
        "coordinates": [-114.061,51.051]
      }
    }
  ]
}
----

[EDITOR]
----
Do we want delta payloads? 
  - https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_UpdateRelatedEntitiesWhenUpdatinganE
  - https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#_Toc38457777
----


[[json-patch]]
==== JSON-Patch

Services MAY additionally support JSON PATCH format <<RFC6902>> to express a sequence of operations to apply to a SensorThings entity.

Entities can be updated with a json-patch  request to an URI pattern that addresses a single entity (<<pattern_entity>> or <<pattern_entity_related>>).

The content-type of the data in a json-patch request is `application/json-patch+json`.

The paths in the json-patch request must not contain navigation links.

.Sending a json-patch request to `v2.0/Things(1)` with the given content will set the value of `properties/status` to `active` only if the current value of `properties/status` to `inactive` and return a `Conflict` error otherwise.
[source,json]
----
[
  { "op": "test", "path": "/properties/status", "value": "inactive" },
  { "op": "replace", "path": "/properties/status", "value": "active" }
]
----



[EDITOR]
----
https://datatracker.ietf.org/doc/html/rfc6902/
----


[[return-value]]
==== Return Value

The returned value for a, entity modification request depends on the `prefer` option, with the possible values `return=minimal` (default) and `return=representation`.

If the `prefer` option is not present, or does not contain a value for `return`, or has `return=minimal` then, for create requests, the entity-id (selfLink) of the created entity is returned as a header, and no content is returned.
For update requests no content is returned.

If the `prefer` option has `return=representation`, then the created resource is returned, optionally taking `$expand`, `$select` and `$format` query options into account.


==== Modifying Relations


==== Removing Entities

Entities can be removed from a service by sending a delete request to an URI pattern that addresses a single entity (<<pattern_entity>> or <<pattern_entity_related>>).

Services SHALL implicitly remove relations to and from an entity when deleting it; clients need not delete the relations explicitly.

The server must ensure data integrity, and delete any entities that depend on the entity being deleted.
For example, deleting a Thing would also delete the HistoricalLocations and Datastreams that depend on it, and the Observations in those Datastreams, but not the Locations of the Thing, since Locations can exist without a relation to a Thing.


=== Authentication & Authorization
