[[OData-Entity-Model]]
=== OData Entity Model

Every OData service utilizes an entity model which MAY be distributed over several schemas.
The service describes this model through a metadata document accessible by a simple HTTP _GET_ request to the `<serviceRoot>/$metadata` path.
This chapter describes an overview of the types of entities in the metadata document that will be used to describe the SensorThings API data model and its data model extensions.
The entities listed below are also used to describe the REST and MQTT bindings of the SensorThings API service.

This section is base on:

* https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_DataModel 
* https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_EntityModel

NOTE: The OData specification uses the term "property". To avoid confusion with "ObservedProperty" and the "properties" attribute in almost every Entity Type, this document uses the terms "attribute" where OData uses the term "property".

The entity model consists of the following elements:

* `Entity Type`: named, structured, keyed element that defines the attributes and relations of Entities.
  The key of an Entity Type consists of one or more primitive attributes of the Entity Type.
* `Entity`: instance of an `Entity Type`.
  An Entity can have only one Entity Type.
* `Primitive Type`: unnamed, unstructured type, such as String, Integer or DateTime. The full list can be found at:
  https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#sec_PrimitiveTypes
  A attribute with a Primitive Type is called a primitive attribute.
* `Complex Type`: named, structured, keyless, element consisting of a set of named attributes.
  Instances of Complex Types can not be accessed outside of the Entity they are contained in.
  A attribute with a Complex Type is called a complex attribute.
  Examples of complex types / complex attributes are:
  ** TM_Interval (Observation/validTime): The complex type TM_Interval has mandatory declared attributes `start` and `end`.
  ** TM_Object (Observation/resultTime): The complex type TM_Interval has mandatory declared attribute `start` and optional declared attribute `end`.
  ** JSON_Object (properties): The complex type JSON_Object is an open type with no declared attributes.
    That means users can add any attributes they see fit.
* `Relation`: named connections between Entities.
  Relations defined as `navigation attributes` in Entity Types.
  Relations have a cardinality.
* `Attributes`: named elements that are part of structured types (Entity Types and Complex Types).
  Attributes can be Primitive-, Complex- or Navigation attributes.
  Attributes defined as part of a structured type (Entity/Complex Type) are `declared attributes`.
  A structured type can allow attributes that are added dynamically, as long as these `dynamic attributes` do not have the same name as a declared attribute.
  Structured types that allow dynamic attributes are called `Open Types`.
* `Entity Set`: a named collection of Entities of the same `Entity Type`.
  Each Entity is uniquely identified among other Entities in the same Entity Set, by its key.
  Entity Sets are the entry points into the data model.
* `Annotation`: additional information attached to model or instance elements.
  annotations can be identified by the `@` character.
  If the annotation starts with the `@` character, then the annotation pertains to the object containing the annotation.
  If the annotation has a attribute name before the `@` charater, then the annotation pertains the attribute with that name.
  Annotations are server-generated additional information that a client can use when processing the data.
  A client can ignore any annotations it does not understand.
  The default annotations can be found in <<tab-common-control-annotations>>.
  Additional annotations may be defined in the service metadata.
* `EntityId`: a globally unique identifier for an Entity.
  If present in Entity representations, the EntityId is specified in the `@id` annotation.

Each Entity has a primary key that is composed of one or more of the `declared attributes` of the entity type.
Which attributes of the Entity Type make up the primary key of the Entity Type is specified in the service metadata document.
For the data models specified in this document the primary key is always the field `id`, though the data type of the field may vary between services.
In most cases the primary key field will be server generated at the time an Entity is created, but a service may allow for client-specified primary key fields.


URLs in documents may be absolute or relative.
Relative URLs are relative to the context URL in the document, or if there is no context url, relative to the request URL.
See https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_RelativeURLs.


[#tab-common-control-annotations,reftext='{table-caption} {counter:table-num}']
.Common control annotations
[width="100%",cols="2a,7a,1a",options="header"]
|===
|Name
|Definition
|Data Type

|@context
|The context url contains the metadata document that describes the context of a payload. See <<OData-CSDL>>
|URL

|@id
|The annotation `@id` is the `entity-id`, an absolute or relative URL of an entity that uniquely resolves to this entity.
This is was known as the `@selfLink` in SensorThings version 1.
|URL

|linkName@navigationLink
|Annotations of the form `linkName@navigationLink` are the relative or absolute URL that retrieves the related entity or entities for the navigation attribute `linkName`.
|URL
|===


[[type_mapping]]
=== Type Mappings

==== Simple Types

<<table_type_mapping>> lists the mapping of types used in the SensorThings API core data model to OData primitive types.

[#table_type_mapping,reftext='{table-caption} {counter:table-num}']
.mapping of types used in the SensorThings API core data model to OData primitive types
[%autowidth,cols="<a,<a,<a",options="header"]
|====
| STA Type | OData type | Description

| ANY
| Edm.Untyped
| Any primitive or complex type

| String
| Edm.String
| A character string

| URI
| Edm.String
| A character string that must be a valid URI

| Geometry
| EDM.Geometry
| A geometry type

| TM_Instant
| Edm.DateTimeOffset
| A time instant, with timezone information
|====


The SensorThings API core data model contains several complex types.
They are `TM_Interval`, `TM_Object` and `JSON Object`.


[[tm_interval]]
==== Complex Type TM_Interval

TM_Interval is a time interval with a mandatory start and end time.
The interval end is "open" meaning that the end-time is not part of the interval.

[#tm_interval-attributes,reftext='{table-caption} {counter:table-num}']
.Attributes of a TM_Interval complex type
[%autowidth,cols="<a,<~a,<a,<a",options="header"]
|====
| Name
| Description
| Data Type
| Multiplicity

| `start`
| The starting time (inclusive) of the time interval.
| TM_Instant
| 1

| `end`
| The end time (exclusive) of the time interval.
| TM_Instant
| 1
|====

Attributes of the type TM_Interval can be directly compared to other time-related attributes and constants.


[[tm_object]]
==== Complex Type TM_Object

TM_Object, used in `Observation/phenomenonTime`, is either a time instant or a time interval.
This is modelled as a time interval with a mandatory start and an optional end time.
If the end time is not present, the TM_Object is a time instant.
If the end time is present, the TM_Object is a time interval with an "open" end, meaning that the end-time is not part of the interval.

[#tm_object-attributes,reftext='{table-caption} {counter:table-num}']
.Attributes of a TM_Object complex type
[width="100%",cols="<a,<~a,<a,<a",options="header"]
|====
| Name
| Description
| Data Type
| Multiplicity

| `start`
| The time instant of the time object, or the starting time (inclusive) of the time interval.
| TM_Instant
| 1

| `end`
| The end time (exclusive) of the time interval.
| TM_Instant
| 0..1
|====

Filter operators and functions that accept times can work directly on TM_Interval and TM_Object types and will use the `start` or `end` time as appropriate.
For instance, finding all Observations with a phenomenonTime before 2025-01-01T00:00:00Z can be done using: `phenomenonTime lt 2025-01-01T00:00:00Z`
For phenomenonTimes that are an interval, this will ensure the end of the interval is before the threshold.
Users can also filter specifically on the start or end by directly referencing these attributes.


[[json_object]]
==== Complex Type JSON_Object

JSON_Object is an open, complex type with no declared attributes.
This means users can store any attributes in instances of this type that they see fit.


[[OData-CSDL]]
=== OData Common Schema Definition Language

The data model is specified in the metadata document that can be retrieved from the context url.
It is described in a machine-readable way using the OData Common Schema Definition Language.
See https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html

An example CSDL document describing a service hosting a SensorThings API v2.0 core data model can be found in <<sta-core-csdl-example>>.
A shortened example with comments can be found in <<csdl-example-short>>.


=== Encoding rules for constants

Encoding rules for constants in resource paths and query options are listed in <<constants_encoding_rules>>

[#constants_encoding_rules,reftext='{table-caption} {counter:table-num}']
.Encoding rules for constants in requests
[width="100%",cols="<3a,<20a,<20a",options="header"]
|====
| *Type*
| *Description*
| *Example*

| String
| Quoted using single-quotes (`'`). Single quotes in a string are doubled.
| `'degree Celsius'` +
`'Abby''s Car'`

| Number
| Numbers are not quoted, use a decimal point (`.`), no thousands separator.
| `0.31415926535897931e1` +
`-42`

| Datetime
| Not quoted ISO8601 time with timezone. Special characters (`+`) must be URL-Encoded.
| `2012-12-03T07:16:23Z` +
`2012-12-03T07:16:23%2B08:00`

| Boolean
| Literal value `true` or `false`
| `true` +
`false`

| Null
| Literal value `null`
| `null`

| Time Duration
| the keyword `duration` followed by an ISO8601 Druation in single quotes.
| `duration'P1DT30M'`

| Geometry
| the keyword `geometry` followed by WKT in single quotes.
| `geometry'POINT(-122 43)'`

| Geography
| the keyword `geography` followed by WKT in single quotes.
| `geography'POINT(-122 43)'`
|====

