[[staplus-business-logic]]
== STAplus Busienss Logic Requirements


=== Overview
The STAplus extension is defined based on requirements from Citizen Science. One major requirement from Citizen Science is that an implementation of STAplus can be used by many users simulaniously to create, update and delete observations. To ensure integrity of the entities and to prevent inconsitencies in the data, it is important that an implementation is not only compliant with this standard but has also functionality that ensures entity consistency. 

Even though the business logic can be very complex and most likely depend on very many factors, it should be possible to hint developers and guide end users of the implementation in case a request results in an unexpected response.

As a machine readable and understandable description of the implemented business logic is preferred, the idea of the business logic requirements class defined here is to describe the business logic in English text.

[[business-logic]]
=== Business Logic

[cols="25a,75a"]
|===
2+|Requirements Class

2+|\http://www.opengis.net/spec/iot_sensing/1.1/extension/staplus/req/staplus-business-logic

|Target Type
|Web Service

|Requirement
|\http://www.opengis.net/spec/iot_sensing/1.1/extension/staplus/req/<<requirement-business-logic>>

|===

[[req-usiness-logic,{counter:req}]]
[cols="a"]
|===
|[[rrequirement-business-logic,business-logic]]
Req <<req-business-logic>>: <<requirement-business-logic>>

|The implementation's business logic shall be described in English text.

|\http://www.opengis.net/spec/iot_sensing/1.1/extension/staplus/req/<<requirement-business-logic>>
|===
