[[staplus-auth]]
== STAplus Authentication Requirements


=== Overview
To regulate access to entities using CRUD operations, implementations may wish to use information from user / client application authentication to make access control decisions. 

In addition, some implementations may wish to link the authentication identifier (e.g. `REMOTE_USER`) with the `Party.authId`. Therefore, the STAplus authentication must provide deployment-wide unique user identifiers.

[[auth]]
=== Requirements Class *Authentication*

[requirements_class]
.Authentication

====
[%metadata]
identifier:: /req-class/authentication
obligation:: requirement
subject:: Target Type: Web Service
inherit:: /req-class/party
requirement:: /req/authentication/id
requirement:: /req/authentication/anon-personal-data-crud
requirement:: /req/authentication/own-personal-data-r
requirement:: /req/authentication/own-personal-data-cud
requirement:: /req/authentication/other-personal-data-r
requirement:: /req/authentication/other-personal-data-cud
====

[requirement]
====
[%metadata]
identifier:: /req/authentication/id

The STAplus authentication SHALL provide a user identifier permanent for same user but different for each user.
====

[requirement]
====
[%metadata]
identifier:: /req/authentication/anon-personal-data-crud

The STAplus implementation SHALL prevent any anonymous user access (read, create, update, and delete) to personal data stored in `Party.personalData`.
====

[requirement]
====
[%metadata]
identifier:: /req/authentication/own-personal-data-r

The STAplus implementation SHALL entitle a user to read their own personal data via a HTTP GET request to their own `Party` entity.
====

[requirement]
====
[%metadata]
identifier:: /req/authentication/own-personal-data-cud

The STAplus implementation SHALL entitle a user to create, update or delete their own personal data via a HTTP POST, PATCH, and DELETE request to their own `Party` entity.
====

[requirement]
====
[%metadata]
identifier:: /req/authentication/other-personal-data-r

The STAplus implementation SHALL prevent that a user can read personal data of other users via a HTTP GET request to `Party` entites of other users.
====


[requirement]
====
[%metadata]
identifier:: /req/authentication/other-personal-data-cud

The STAplus implementation SHALL prevent that a user can create, update or delete personal data of other users via a HTTP POST, PATCH, and DELETE request to `Party` entities of other users.
====
