[obligation=informative]
== Introduction

The STAplus 1.0 Standard defines an extension to the OGC SensorThings API named STAplus. This extension originally started with motivations and requirements from the Citizen Science community. However, the STAplus extension has wider applicability than just Citizen Science.

STAplus is a 100% backwards compatible extension to the STA V1.1 data model and as such can be added to existing STA deployments.

In addition to the data model extension, this Standard defines different concepts that support operating an implementation in a multi-user CRUD deployment.


===	Concept of Ownership
In Citizen Science, users participate in projects or campaigns, offered by different Citizen Science portals. These portals, typically operated by different entities, have one feature in common: Contributions, uploaded by users are associated with the user and the ownership does not change. There is an explicit relationship between the observation (contribution) and the user. Expressed as ownership, users can undertake certain actions on their resources.

With the SensorThings API (STA), observations are linked to a data stream that is linked to a sensor which belongs to a thing.The data model does not provide a class that supports explicitly linking a user (party) to an observation. This limits the use of the STA data model (and API) to a simple use case: One operator can create data objects and all other users have read-only access. This limits the options for applications to interact with the API.

Even though the STA v1.1 data model offers the generic use of “properties”, expressing ownership (user association) buried in properties is not wise. This also makes compliance with the European General Data Protection Regulation (GDPR) difficult for applications using STA. This is because it is unclear if properties store personal data and therefore fall under GDPR. This  decreases interoperability tremendously as an application developer would need to know which attribute expresses ownership. Also, querying observations based on unstructured properties is extremely complex and difficult.

Therefore, the STAplus extension defines the class Party for expressing the association from a (Multi)Datastream to a user. All observations, generated by a Datastream instance belong to the associated party.

===	Improving F A I R
In general, there are many aspects when it comes to ensure reusability of (existing) data. Not only in the context of Citizen Science, one fundamental aspect is the licensing aspect. Very many users contribute to Citizen Science with the motivation to do meaningful things for the common good. At the same time, users like to be credited when it comes to re-use of their contribution(s). Therefore, most contributions in Citizen Science are freely accessible (open access) but the re-use is not simply “open”. In order to get credited, users might associate a license like CC-BY (Creative Commons Attribution License). Even though the data is still freely accessible, there is a condition that must be followed as expressed in the license.

===	Creating Observation Bags
When contributing to Citizen Science, the actual observation is often a set or bag of individual observations that belong together - in other words belong to the same observation event. For example, a camera trap event consists of a picture, a textual observation expanding the likelihood of species prediction and sensor readings for environmental context (temperature, humidity, luminance, air pressure, GPS location). All of these (individual) observations were created at the same time/location and could therefore be grouped.

Another use case for applying grouping to existing observations is to create a package of observations for the purpose of building the fundamentals for research or to be used in workflows. For researching and later evaluation of a particular phenomenon, the same bag (or set) of observations can be exchanged via the grouping concept.

Also, over time a user community might link other observations and even provide cross links to other databases such as the Global Biodiversity Information Facility (GBIF)footnote:[https://www.gbif.org/]. These can be semantically tagged with the `Relation` entity which is described later in this document.

The STAplus extension defines a flexible grouping concept by adding the `Group` entity to the STA data model.

===	Expressing Relations 
For Citizen Science expressing relations between observations explicitly to support search based on these relations is important. The SensorThings data model does not support to express relationships. 

Therefore, the STAplus extension introduces the `Relation` entity that supports creating generic “from – to” relations. The “to” can point to another observation or to an external object. This allows the generic expression of meaning, leveraging existing semantic concepts that exist elsewhere, for example Dublin or Darwin Core. This helps to reason how observations are related even if they were not observed in a same observation event, but instead were linked later to a particular community process (as linking to other databases).

The use of Relations as defined in STAplus can be applied to already existing SensorThings deployments to enrich the data towards semantics. 
 
=== Data Model Extension
The STAplus data model extension allows expressing the following additional characteristics:

- People: The `Party` entity supports linking a user to a `Datastream` or `Group`
- License: The `License` entity supports expressing reuse conditions by linking a `License` to a `Datastream` and / or to a `Group`. A `License` on a `Datastream` has the result that all `Observation` entities of that `Datastream` (as well as entities of the `Thing`, `Sensor` and `ObservedProperty`) have the associated license. A `License` on a `Group` gives the bag or set of `Observations` (represented by the `Group`) a license for reuse. Note that still the license for each `Observation` must still be followed.
- Union: The `Group` entity supports packaging individual `Observations` as a bag or set either as deep copy or via linking
- Semantics: The `Relation` entity supports expressing relationships between `Observation` entities using the “from-to” type. It is also possible to create relations between `Observation` entities and external objects using the URI scheme. This allows in particular to express a relation to any entity of the database (via their external URI). `Relation` entities can exist on its own or be included into a Group to enrich a bag or set of `Observation` entities.
- Project: The `Project` entity is a container of `Datastream` and `MultiDatastream` entities that supports organizing a campaign or project and to provides metadata as well as legal information such as terms of use and a privacy statement, in case it is relevant.


