== Conformance

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

=== Introduction

The STAplus 1.0 standard defines an extension to the OGC Standards <<OGC15-078r6>> (SensorThings API v1.0) and <<OGC18-088>> (SensorThings API v1.1) by adding additional entity types to the data model. Access to the STAplus entities via HTTP is defined in the Read, Update and Delete Requirements Classes. The use of MQTT for STAplus entities is defined in the MQTT Requirements Class. A default storage-CRS is defined via the Default-CRS Requirements Class and additional geometry encodings are defined in the Geometry FG and Geometry WKT Requirements Class. The Authentication Requirements Class supports the unique identification of acting users. The Business Logic Requirements Class supports the textual description of the implemented business logic. An example of such a Business Logic is described in the <<OGC21-068>>.

=== STAplus 1.0 Conformance Classes
This OGC Standard defines one mandatory and several optional conformance classes.

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC Standard, a software implementation shall choose to implement:

* The one mandatory conformance class.
* Any one of the optional conformance classes.
* Pass all applicable tests as defined in Annex A (normative)

In order to conform to this OGC Standard, a software implementation SHALL implement the mandatory conformance class specified:

* *Core* (mandatory): This Conformance Class incorporates the capabilities to support the Read of STAplus entities via HTTP. It also includes the Storage-CRS Requirements Class to ensure interoperability with geometry encodings in the `feature` and `location` properties.

* *Create* (optional): This Conformance Class supports to create STAplus entities via HTTP.

* *Update* (optional): This Conformance Class supports to update STAplus entities via HTTP.

* *Delete* (optional): This Conformance Class supports to delete STAplus entities via HTTP.

* *Authentication* (optional): This Conformance Class supports user authentication and their unique identification.

* *Geometry-FG* (optional): This Conformance Class supports the alternative geometry encoding for the `feature` and `location` properties based on Features and their Geometries.

NOTE: This Conformance Class remains informative until <<FG>> is an adopted OGC Standard.

* *Geometry-WKT* (optional): This Conformance Class supports the alternative geometry encoding for the `feature` and `location` properties based on Well Known Text (WKT) as defined in <<ISO19125-1>>.

* *MQTT Subscribe STA v1.0* (optional): This Conformance Class supports a client to receive STAplus entity changes via MQTT as defined in <<OGC15-078r6>>.

* *MQTT Subscribe STA v1.1* (optional): This Conformance Class supports a client to receive STAplus entity changes via MQTT as defined in <<OGC18-088>>.

* *Business Logic* (optional): This Conformance Class supports that the implementation business logic is described in English text to help developers understand the details of CRUD access.

==== Conformance Class *Core*
The `Core` Conformance Class is defined as follows:
[conformance_class]
.Core
====
[%metadata]
identifier:: {identifier}/conf/core
target:: {identifier}/req-class/entity-control-information
target:: {identifier}/req-class/party
target:: {identifier}/req-class/license
target:: {identifier}/req-class/group
target:: {identifier}/req-class/relation
target:: {identifier}/req-class/campaign
target:: {identifier}/req-class/read
target:: {identifier}/req-class/storage-crs

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/core/common-control-information
conformance-test:: {identifier}/conf/core/entities
conformance-test:: {identifier}/conf/core/read
conformance-test:: {identifier}/conf/core/storage-crs/crs-definition
conformance-test:: {identifier}/conf/core/storage-crs/axis-order
conformance-test:: {identifier}/conf/core/storage-crs/media-type
conformance-test:: {identifier}/conf/core/storage-crs/processing
====

==== Conformance Class *Create*
The `Create` Conformance Class is defined as follows:
[conformance_class]
.Create
====
[%metadata]
identifier:: {identifier}/conf/create
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/create

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/create/http
====

==== Conformance Class *Update*
The `Update` Conformance Class is defined as follows:
[conformance_class]
.Update
====
[%metadata]
identifier:: {identifier}/conf/update
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/update

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/update/put
conformance-test:: {identifier}/conf/update/patch
====

==== Conformance Class *Delete*
The `Delete` Conformance Class is defined as follows:
[conformance_class]
.Delete
====
[%metadata]
identifier:: {identifier}/conf/delete
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/delete

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/delete/entity
====

==== Conformance Class *Authentication*
The `Authentication` Conformance Class is defined as follows:
[conformance_class]
.Authentication
====
[%metadata]
identifier:: {identifier}/conf/authentication
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/authentication

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/authentication/id
conformance-test:: {identifier}/conf/authentication/id-create
conformance-test:: {identifier}/conf/authentication/id-read
conformance-test:: {identifier}/conf/authentication/id-update
conformance-test:: {identifier}/conf/authentication/id-delete
====

==== Conformance Class *Geometry FG*

NOTE: This Conformance Class remains informative until <<FG>> is an adopted OGC Standard.

The `Geometry FG` Conformance Class is defined as follows:
[conformance_class]
.Geometry FG
====
[%metadata]
identifier:: {identifier}/conf/geometry-fg
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/geometry-fg

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/geometry-fg//media-type
conformance-test:: {identifier}/conf/geometry-fg/default-crs
conformance-test:: {identifier}/conf/geometry-fg/supported-crs
conformance-test:: {identifier}/conf/geometry-fg/crs-error
conformance-test:: {identifier}/conf/geometry-fg/processing
conformance-test:: {identifier}/conf/geometry-fg/out
====

==== Conformance Class *Geometry WKT*
The `Geometry WKT` Conformance Class is defined as follows:
[conformance_class]
.Geometry WKT
====
[%metadata]
identifier:: {identifier}/conf/geometry-wkt
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/geometry-wkt

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/geometry-wkt/media-type
conformance-test:: {identifier}/conf/geometry-wkt/crs-definition
conformance-test:: {identifier}/conf/geometry-wkt/default-crs
conformance-test:: {identifier}/conf/geometry-wkt/supported-crs
conformance-test:: {identifier}/conf/geometry-wkt/crs-error
conformance-test:: {identifier}/conf/geometry-wkt/value
conformance-test:: {identifier}/conf/geometry-wkt/processing
conformance-test:: {identifier}/conf/geometry-wkt/out
====

==== Conformance Class *MQTT Subscribe* STA v1.0
The `MQTT Subscribe` STA v1.0 Conformance Class is defined as follows:
[conformance_class]
.MQTT Subscribe STA v1.0
====
[%metadata]
identifier:: {identifier}/conf/mqtt-subscribe-sta-10
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/mqtt-subscribe-sta-10

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/mqtt-subscribe-sta-10/definition
conformance-test:: {identifier}/conf/mqtt-subscribe-sta-10
====

==== Conformance Class *MQTT Subscribe* STA v1.1
The `MQTT Subscribe` STA v1.1 Conformance Class is defined as follows:
[conformance_class]
.MQTT Subscribe STA v1.1
====
[%metadata]
identifier:: {identifier}/conf/mqtt-subscribe-sta-11
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/mqtt-subscribe-sta-11

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/mqtt-subscribe-sta-11/definition
conformance-test:: {identifier}/conf/mqtt-subscribe-sta-11
====

==== Conformance Class *Business Logic*
The `Business Logic` Conformance Class is defined as follows:
[conformance_class]
.Business Logic
====
[%metadata]
identifier:: {identifier}/conf/business-logic
inherit:: {identifier}/conf/core
target:: {identifier}/req-class/business-logic

classification:: Target Type: Implementation
conformance-test:: {identifier}/conf/business-logic/definition
conformance-test:: {identifier}/conf/business-logic/location
====