== Scope
While the OGC SensorThings API provides an open Standard-based and geospatial-enabled framework to interconnect the Internet of Things, OGC STAplus extends the scope of SensorThings API to use cases where sensors are deployed by different actors structured in one or more campaigns. The STAplus Standard also allows for relating observations to other internal or external observations and group observations. The open STAplus Standard is backwards-compatible with SensorThings API and uses the same web API and MQTT mechanisms. The grouping and relations can be used for linking sensor data beyond the original link to semantic definitions in ObservedProperty and unitOfMeasurement, and includes terms of use and licenses. Both additions improve the reusability aspect of the FAIR principles. This Standard also emphasizes on how to use an implementation in multi-user environments.

=== Security Considerations
A STAplus service implementation that supports the Create, Update or Delete of entities should also implement authentication and a "fit-for-purpose" business logic that enforces the required access conditions to ensure ownership of all entities, including SensorThings core entities.

The Business Logic makes the full power of STAplus useful! For example, sealed (closed) ObservationGroups - aka a group of observations that may include relations - could be used for interdisciplinary research by simply exchanging the group's URL. But, it is essential to trust such a group which requires a verifiable group author and the business logic to support integrity of such a closed group. 

As each business logic flow may be different from service to service deployment, the operator of the service should describe the business logic and make it available to developers that intend to use the STAplus service. The specification of a conformance class `Business Logic`, reflecting the semantics of the logic in a standardized and machine readable fashion, is out of scope for this Standard but could be defined in an extension to STAplus.

Without an appropriate business logic, enforcing ownership and ensuring integrity in a multi-user scenario, it is possible that "junk" or "spam" is associated to a party without their knowledge. In such a multi-user CRUD access scenario, it would also be possible to "steal" an entire `Datastream` entity by simply updating the associated `Party` entity. Further, observations could be modified or even deleted without the owning user's approval. While not specific to STAplus, these Business Logic considerations and concerns should be identical for any deployed SensorThings API service. 

The STAplus data model does not support the recording of provenance. If the business logic allows the update or even deletion of entities, there is no history of who did what and when. The data served from a service implementation is a snapshot in time which may cause pagination to produce non deterministic results.

For implementations of the `Create`, `Update` and `Delete` conformance class it is paramount to check all user uploads for malicious content. Typical SQL injection checks are mandatory but also JavaScript code injection must be tackled. For example, it is likely that the value of an observation will be displayed on some HTML page. To prevent malicious code or virus injection, similar to cross-site-scripting attacks, pattern checking on any uploaded data should be accomplished.

The STAplus data model does *not* support the storage of personal data with a `Party` entity. Neither offers the `Party` entity the usual `properties` property to ensure personal data is not stored there. As a result, any requirement for accessing and sharing of personal data must take place with another system. Such system is likely connected to the same authentication as the STAplus service to ensure alignment between the `authId` within STAplus and the management of personal data stored at _the other system_. As personal data gets associated with STAplus user identifiers, it is recommended to operate _the other system_ controlling the exchange of personal information. Such a system could be designed on an opt-in basis: A user is asking _the other system_ for personal data to be used in a particular context of another user via the identifier. Once the user has approved the use of the personal data for the given context, the data received from STAplus can be linked with the personal data from _the other system_ based on the user's identifier (`authId`). Even though the STAplus data model does not support the direct storage of personal data, it could be possible that in a wider eco-system personal data can be linked with user's identifier from STAplus.

The use of a unique `authId` is mandatory to ensure integrity and confidentiality of data when STAplus is used as a multi-user service. In case that multiple authentication systems are to be supported, the resulting `authId` has to be unique for the service. One possibility would be to require that acceptable authentication systems support the <<W3C-DID>>. The use of W3C DIDs helps by the DID structure that identifiers of each authentication system become globally unique.  

The `authId` or the `displayName` can be used in `$filter` or `$select` to craft STAplus queries on entities that belong to a particular user. However, it is important to recognize that the `authId` for a user will not change but the `displayName` may.

Even though not a direct feature of STAplus, storage of location and time is possible as inherited from STA. An implementation's business logic may obfuscate the location of a sensor or observations based on internal logic. It is also possible that the user's application that uploads the time/location values obfuscates values according to user's discretion. This would ensure disconnect between location of observations and tracking location of people.

The exposure of time/location may become sensitive information in certain cases. The business logic should implement certain conditions that at least ensure compliance with the law. 

The upload of binary data or graphical language must be sanitized in compliance with the law. In particular, ethical aspects must be considered to ensure that observation values are not misused i.e. to result into personal harassment.