.Preface

STAplus - SensorThings API extension PLUS - defines a SensorThings data model extension to improve FAIR principles when exchanging sensor data including licensing and ownership information. 

The STAplus extension is fully backwards compatible to the exsting OGC SensorThings API standard v1.1 and thereby offers existing STA deployments to easily upgrade to STAplus.

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract

This document specifies a backwards-compatible extension to the OGC SensorThings data model.

The motivation for the introduced extension STAplus has been developed during the European Commission H2020 project Cos4Cloud and is based on requirements from Citizen Science. 

Whereas the dominant use of the OGC SensorThings data model (and API) can be coined with the use case “single authority provides sensor readings to consumers”, in Citizen Science there are many contributors (citizens) that – together – create the big “picture” with their observations.

The introduced extension STAplus supports to model that observations are owned by (different) users that may express the license for re-use; we call this part of the contribution the ownership concept. In addition to the ownership and license abilities, the introduced extension allows to express explicit relations between observations and to create group(s) of observations to containerize observations that belong together. Relations can be created among any individual observations or observations of a group to support performant Linked Data extraction and semantic queries, e.g. expressed in SPARQL.

The submitters believe that the introduced extension is an important contribution towards the realization of the FAIR principles as STAplus strengthens the “I” (Interoperability) through a common data model and API as well as the “R” (Re-usability) by allowing to express standards-based queries that may consider licensing conditions, relevant for reuse of other users’ observations. 

The STAplus Data Model and Business Logic also enriches existing deployments as the extension can be seamlessly added and thereby offer new capabilities to create and manage the “big picture” with multi-user capabilities.

Two implementations exist by 52°North and Secure Dimensions.
