== Terms and definitions


=== Annotation

Additional information attached to model or instance elements.
Annotations can be identified by the `@` character.


=== Attribute

Named element that is part of a structured type (Entity Type or Complex Type).


=== Complex Type

Named, structured, keyless, element consisting of a set of named attributes.


=== EntityId

A globally unique identifier for an Entity.
If present in Entity representations, the EntityId is specified in the `@id` annotation.


=== Entity

instance of an `Entity Type`.
An Entity can have only one Entity Type.


=== Entity Set

A named collection of Entities of the same `Entity Type`.
Each Entity is uniquely identified among other Entities in the same Entity Set, by its key.
Entity Sets are the entry points into the data model.


=== Entity Type

Named, structured, keyed element that defines the attributes and relations of Entities.


=== (Internet of) Thing

A thing is an object of the physical world (physical things) or the information world (virtual things) that is capable of being identified and integrated into communication networks.

[.source]
<<ITU-T-Y.2060>>


=== Measurement

A set of operations having the object of determining the value of a quantity.

[.source]
<<OgcOMS>>

[.source]
<<IsoOMS>>


=== Observation

Act of measuring or otherwise determining the value of a property.

[.source]
<<OgcOMS>>

[.source]
<<IsoOMS>>


=== Observation Result

Estimate of the value of a property determined through a known observation procedure.

[.source]
<<OgcOMS>>

[.source]
<<IsoOMS>>


=== Primitive Type

Unnamed, unstructured type, such as String, Integer or DateTime.
An attribute with a Primitive Type is called a primitive attribute.


=== Relation

Named connection between Entities.


=== STA API

The abstract API part of the OGC SensorThings API standard.


=== STA data model

The data model part of the OGC SensorThings API standard.


=== STA endpoint

A point of connection for a client.
For example, the HTTP endpoint of a STA service is available at a given domain and path and can be accessed using the HTTP protocol.


=== STA implementation

A piece of software that implements the OGC SensorThings API standard, as a client or server.


=== STA Service

A deployed STA implementation.
A single service may expose multiple endpoints.


=== STA Standard

The OGC SensorThings API standard (this document).

