[bibliography]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

[NOTE]
====
Insert References here. If there are no references, leave this section empty.

References are to follow the Springer LNCS style, with the exception that optional information may be appended to references: DOIs are added after the date and web resource references may include an access date at the end of the reference in parentheses. See examples from Springer and OGC below.
====

* [[[Smith81,Identification of Common Molecular Subsequences]]],
_Identification of Common Molecular Subsequences_.
Smith, T.F., Waterman, M.S., J. Mol. Biol. 147, 195–197 (1981)

* [[[May06,ZIB Structure Prediction Pipeline]]],
_ZIB Structure Prediction Pipeline: Composing a Complex Biological Workflow through Web Services_.
May, P., Ehrlich, H.C., Steinke, T. In: Nagel, W.E., Walter,
W.V., Lehner, W. (eds.) Euro-Par 2006. LNCS, vol. 4128, pp. 1148–1158. Springer,
Heidelberg (2006)

* [[[Grid,The Grid]]], _The Grid: Blueprint for a New Computing Infrastructure._,
Foster, I., Kesselman, C.. Morgan Kaufmann, San Francisco (1999).

* [[[Czajkowski01,Grid Information Services for Distributed Resource Sharing]]],
_Grid Information Services for Distributed Resource Sharing._
Czajkowski, K., Fitzgerald, S., Foster, I., Kesselman, C. In: 10th IEEE International Symposium on High
Performance Distributed Computing, pp. 181–184. IEEE Press, New York (2001)

* [[[Foster02,The Physiology of the Grid]]],
_The Physiology of the Grid: an Open Grid Services Architecture for Distributed Systems Integration._
Foster, I., Kesselman, C., Nick, J., Tuecke, S. Technical report, Global Grid Forum (2002)

* [[[NCBI,NCBI]]], _National Center for Biotechnology Information_, http://www.ncbi.nlm.nih.gov

* [[[ISO19101-1,ISO 19101-1:2014]]], Geographic information -- Reference model -- Part 1: Fundamentals

* [[[ISO19115-1,ISO 19115-1:2014]]], _Geographic information -- Metadata -- Part 1: Fundamentals_

* [[[ISO19157,ISO 19157:2013]]], _Geographic information -- Data quality_

* [[[ISO19139,ISO 19139:2007]]], _Geographic information -- Metadata -- XML schema implementation_

* [[[ISO19115-3,ISO 19115-3]]], _Geographic information -- Metadata -- Part 3: XML schemas_ (2016)

* [[[OGC15-097,OGC 15-097]]], _OGC Geospatial User Feedback Standard: Conceptual Model_ (2016)

* [[[OGC12-019,OGC 12-019]]], _OGC City Geography Markup Language (CityGML) Encoding Standard_ (2012)

* [[[OGC14-005r3,OGC 14-005r3]]], _OGC IndoorGML_ (2014)

* [[[OGC06121r9,OGC 06-121r9]]], _OGC Web Service Common Implementation Specification_, April 7, 2010. http://portal.opengeospatial.org/files/?artifact_id=38867