== Terms and definitions

This document uses the terms defined in Sub-clause 5.3 of <<OGC06-121r9>>, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== Party

The entity in the data model that represents a user. A party can be associated to other entities of the datamodel to express ownership.

=== License

The entity in the data model that represents a well defined licence. Associating a license with a Multi/Datastream expresses re-use conditions for all observations associated with that Multi/Datastream.

=== Group

The entity in the data model that allows to create a collection of observations for a particular purpose.

=== Relation

The entity in the data model that allows to express relationships between two observations or an observtion and an external object.

=== Project

The entity in the data model that allows to put Multi/Datastream(s) together that are required to achieve the objective represented by the project.

=== Ownership

The Party entitiy in the data model allows to express the right of possession over entity instances. This is the requirement to operate STAplus with multi-user CRUD access. 