
=== URI Patterns

URI Patterns in the SensorThings API consist of three parts: the URI-Root, the resource path and query options.
The URI-Root always ends with the version number of the standard, encoded as: `"v"majorversionnumber + "." + minorversionnumber`.
The resource path consists of zero to many parts separated with by the slash (`/`) character.
Resource paths are case sensitive.
The query options start with a question mark (`?`) character.
At the top level, query options are separated with the ampersant (`&`) character.

.Example {counter:examples}: Complete URI example using HTTP bindings
[source%unnumbered,text]
----
http://example.org/v2.0/Datastreams(5)/Observations?$orderby=ID&$top=10
_______________________/__________________________/___________________/
          |                          |                      |
  service root URI             resource path           query options
----

.Example {counter:examples}: Complete URI example using MQTT bindings
[source%unnumbered,text]
----
base/topic/v2.0/Datastreams(5)/Observations?$orderby=ID&$top=10
_______________/__________________________/___________________/
      |                      |                      |
   root URI            resource path           query options
----


[[pattern_service_document]]
==== Service Document

URI Pattern: `v2.0`

Requests to the URL pattern consisting of just the version number, optionally followed by a slash (`/`) address the service document.


==== Service Metadata Document

URI Pattern: `v2.0/$metadata`

Requests to the URL pattern consisting of the API version number followed by `/$metadata` address the service metadata document that describes the data model that the service exposes.
The service metadata document is described in <<OData-CSDL>>.


[[pattern_entityset]]
==== Entity Set

URI Pattern: `v2.0/EntityTypeName`

Requests to a URL pattern consisting of the API version number followed by `/` and the name of an entity type address the set of all entities of the requested type.

.Example {counter:examples}: Resource pattern for the Datastreams Entity Set
[source%unnumbered,text]
----
v2.0/Datastreams
----


[[pattern_entity]]
==== Entity

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)`

Requests to a URL pattern consisting of the name of an EntitySet URL, followed by, in brackets, a primary key value fitting the entity type of the set, address the single Entity from the set, that has the given primary key.

.Example {counter:examples}: Resource pattern for a specific Datastream, for a service that uses Integers for the id field of Datastreams
[source%unnumbered,text]
----
v2.0/Datastreams(4)
----

.Example {counter:examples}: Resource pattern for a specific Datastream, for a service that uses Strings for the id field of Datastreams
[source%unnumbered,text]
----
v2.0/Datastreams('xz42df')
----


[[pattern_entity_property]]
==== Entity Property

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)/entityProperty`

Requests to a URL pattern consisting of a URL that addresses an Entity (the base entity), followed by an Entity Property, address the value of this Entity Property of the base Entity.
The used URL for the base entity may itself be a related entity URL.

.Example {counter:examples}: Resource pattern for the name of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/name
----

.Example {counter:examples}: Resource pattern for the name of the Thing of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Thing/name
----


[[pattern_entity_property_raw]]
==== Entity Property raw value ($value)

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)/entityProperty/$value`

Requests to a URL pattern consisting of a URL that addresses an Entity (the base entity), followed by an Entity Property, followed by `/$value`, address the raw value of this Entity Property of the base Entity.
The used URL for the base entity may itself be a related entity URL.

.Example {counter:examples}: Resource pattern for the raw name of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/name/$value
----

.Example {counter:examples}: Resource pattern for the raw name of the Thing of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Thing/name/$value
----


[[pattern_entity_related]]
==== Related Entity

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)/EntityNavigationProperty`

Requests to a URL pattern consisting of a URL that return an Entity (the base entity), followed by a navigation property with a cardinality of one, address the related entity of the base entity.
The used URL for the base entity may itself be a related entity URL.


.Example {counter:examples}: Resource pattern for the Thing of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Thing
----

.Example {counter:examples}: Resource pattern for the Thing of the Datastream of a specific Observation
[source%unnumbered,text]
----
v2.0/Observations(42)/Datastream/Thing
----


[[pattern_entityset_related]]
==== Related EntitySet

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)/EntitySetNavigationProperty`

Requests to a URL pattern consisting of a URL that addresses an Entity (the base entity), followed by a navigation property with a cardinality of many, address the related EntitySet of the base entity.
The used URL for the base entity may itself be a related entity URL.

.Example {counter:examples}: Resource pattern for the Observations of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Observations
----

.Example {counter:examples}: Resource pattern for the Locations of the Thing of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Thing/Locations
----


[[pattern_relation]]
==== Association link ($ref)

URI Pattern: `v2.0/EntityTypeName(<primaryKey>)/NavigationProperty/$ref`

Requests to a URL pattern consisting of a URL that addresses an Entity (the base entity), followed by a navigation property, followed by `/$ref`, address the entity-id(s) of the related entity or entities of the given navigation property.
For navigation property with a cardinality of many, the navigation property may be followed by a primary-key in brackets, to address the specific association between the base entity and the related entity.
The association link can be used to modify the relation(s).

.Example {counter:examples}: Resource pattern for the association link of the Thing of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Thing/$ref
----

.Example {counter:examples}: Resource pattern for the association link to the Observations related to a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Observations/$ref
----

.Example {counter:examples}: Resource pattern for the association link between a specific Datastream and a specific Observation
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Observations(1)/$ref
----


==== Encoding rules for constants

Encoding rules for constants in resource paths and query options are listed in <<constants_encoding_rules>>

[#constants_encoding_rules,reftext='{table-caption} {counter:table-num}']
.Encoding rules for constants in requests
[width="100%",cols="<3a,<20a,<20a",options="header"]
|====
| *Type*
| *Description*
| *Example*

| String
| Quoted using single-quotes (`'`). Single quotes in a string are doubled.
| `'degree Celsius'` +
`'Abby''s Car'`

| Number
| Numbers are not quoted, use a decimal point (`.`), no thousands separator.
| `0.31415926535897931e1` +
`-42`

| Datetime
| Not quoted ISO8601 time with timezone. Special characters (`+`) must be URL-Encoded.
| `2012-12-03T07:16:23Z` +
`2012-12-03T07:16:23%2B08:00`

| Boolean
| Literal value `true` or `false`
| `true` +
`false`

| Null
| Literal value `null`
| `null`

| Time Duration
| the keyword `duration` followed by an ISO8601 Druation in single quotes.
| `duration'P1DT30M'`

| Geometry
| the keyword `geography` followed by WKT in single quotes.
| `geography'POINT(-122 43)'`

|====


==== More complex examples

`v2.0/EntityTypeName(<primaryKey>)/EntitySetNavigationProperty(<primaryKey>)`

The pattern <<pattern_entityset_related>> and <<pattern_entity>> can be combined to get a specific entity from a related set.
This will return a `Not Found` error when the requested entity is not actually in the related set.

.Example {counter:examples}: Resource pattern for a specific Observation of a specific Datastream
[source%unnumbered,text]
----
v2.0/Datastreams(4)/Observations(5321)
----

The above example addresses the same entity as `v2.0/Observations(5321)`, except when Observation `5321` is not actually contained in Datastream 4, since in that case any action on the resource would return a `Not Found` error.

