[[staplus-mqtt]]
== STAplus MQTT Extension Requirements

The MQTT capabilities allows that a client to receive changes to STAplus entities via MQTT. 

NOTE: The publishing of observations as defined in <<OGC18-088>> via MQTT does not apply to STAplus entities.

=== Overview

NOTE: In the context of MQTT, all STAplus entities as defined in this Standard are equivalent to the STA entities. Therefore, the implementation of MQTT capabilities must be compliant with the SensorThings API Part 1: Sensing v1.1 Standard.

[[mqtt-subscribe]]
=== Requirements Class *MQTT Subscribe*

[requirements_class]
.MQTT Subscribe


====
[%metadata]
identifier:: /req-class/mqtt-subscribe
obligation:: requirement
subject:: Target Type: Web Service
inherit:: http://www.opengis.net/spec/iot_sensing/1.1/req/receive-updates-via-mqtt
requirement:: /req/mqtt-subscribe
====

[requirement]
====
[%metadata]
identifier:: /req/mqtt-subscribe

A STAplus implementation SHALL support the receiving of STAplus entity updates with MQTT Subscribe as defined in http://www.opengis.net/spec/iot_sensing/1.1/req/receive-updates-via-mqtt.
====
