.Preface

The OGC SensorThings API provides an open, geospatial-enabled and unified way to interconnect sensor-data producing devices, data, and applications over the Internet.
Version 2.0 brings updates to version 1.1, improving the data model, the API and the modularity of the standard itself.

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.



[abstract]
== Abstract

The OGC SensorThings API provides an open, geospatial-enabled and unified way to interconnect sensor-data producing devices, data, and applications over the Internet.
It contains a core data model, an abstract REST API for accessing data, and bindings for this API for HTTP and MQTT.

The data model is an implementation of the core concepts of the Observations, Measurements and Samples OGC/ISO specification.
The API allows for creating, reading, updating and deleting all parts of the data model.
It also features extensive filtering and response-customisation capabilities.

Even though the SensorThings API was initially designed for IoT, the previous versions have shown to be wel suited for any use case involving time-series data.



[[submitters-section]]
== Submitters

All questions regarding this submission should be directed to the editors or the submitters:


- Hylke van der Schaaf _(editor)_ -- Fraunhofer-Gesellschaft
- Steve Liang -- SensorUp Inc.
- Marcus Alzona -- Keys.com
- Kathi Schleidt -- Datacove e.U.
- Andreas Matheus -- Secure Dimensions GmbH
- Humaid Imran Kidwai -- University of Calgary
- Joan Maso Pau -- Universitat Autònoma de Barcelona (CREAF)
- Sylvain Grellet -- BRGM
- Mickael Beaufils -- BRGM



The submitters would like to acknowledge the following organizations and projects as important supporters and contributors to this version of the specification:

- Bureau de Recherches Géologiques et Minières (BRGM)
- Datacove e.U.
- Fraunhofer IOSB
- OGC / WMO Water Quality IE
- OGC GeoTech IE
- OneWater Data French Research project (ANR-22-PEXO-0009)
- Secure Dimensions GmbH
- SensorUP Inc.
- Universitat Autònoma de Barcelona (CREAF)
- University of Calgary
- Water4All Partnership (European Union's Horizon Europe Programme under Grant Agreement 101060874)


include::./security_considerations.adoc[]
