[[staplus-foi-location]]
== STAplus Feature and Location Geometry Encoding Requirements


=== Overview
The `<Location>` and `<FeatureOfInterest>` entities allow to store data objects with unspecified structure. Both entities potentially store geometry information. The STAplus extension supports multi-user interactions including the creation, updating, reading and deletion of information. In Citizen Science for example, one service endpoint could accept that users can upload data using different applications. These applications might be developed by different parties and serve different purposes, and thus use different geometry structures and CRS to encode the coordinates of the geometries. This can result in the situation where the interoperability of uploaded geometry in the `<Location>` and `<FeatureOfInterest>` entities might become an interoperability issue. 

For an implementation of STAplus, this situation becomes complicated when a `$filter` is leveraged that includes spatial conditions like `ST_Within`. The filter expression does not carry any CRS information. So, how to apply a spatial filter to geometries stored in `feature` and `location` properties uploaded by different applications? Because the SensorThings data model does not define how to store CRS information inside the `feature` and `location`, it only recommends to use GeoJSON. To apply the `$filter` with spatial operators introduces two problems: First, the CRS data would need to be stored in a standardized location inside `feature` and `location` properties, and second, the implementation would need to apply coordinate transformation 'on the fly' when processing a spatial filter condition and stored geometries are encoded in different CRS. The first aspect will cause interoperability issues and the later will inevitably cause performance issues.

To get out of this impractical situation, the STAplus Standard defines a default storage-CRS based on WGS84 with axis-order longitude/latitude as defined in <<GeoJSON>>. Any uploaded geometry data encoded in the storage-CRS will be stored as-is. Any uploaded geometry data encoded differently will be transformed into the storage-CRS and then stored.

To indicate that the default storage-CRS and GeoJSON geometry encoding is used, the `encodingType` property of the `FeatureOfInterest` and `Location` entity is to be used with the value `application/geo+json`. 

In addition, the STAplus extension supports other (commonly used) encodings via the `Geometry Encoding` Requirements Class. 



[[CRS]]
=== Storage-CRS Requirements Class

This Requirements Class defines the default CRS with axis-order and its media-type.

[requirements_class]
.Storage-CRS

====
[%metadata]
identifier:: /req-class/storage-crs
obligation:: requirement
subject:: Target Type: Web Service
inherit:: <<GeoJSON>>
requirement:: /req/storage-crs/crs-definition
requirement:: /req/storage-crs/axis-order
requirement:: /req/storage-crs/media-type
requirement:: /req/storage-crs/processing
====


[requirement]
====
[%metadata]
identifier:: /req/storage-crs/crs-definition

The implementation SHALL use the <<GeoJSON>> CRS `{CRS84}` as the storage-CRS.
====

[requirement]
====
[%metadata]
identifier:: /req/storage-crs/axis-order

The implementation SHALL use the <<GeoJSON>> axis-order with the storage-CRS.
====

[requirement]
====
[%metadata]
identifier:: /req/storage-crs/media-type

The implementation SHALL accept the media-type `encodingType=application/geo+json` to indicate that the structuring of the `FeatureOfInterest` and `Location` entities geometry encoding is compliant with the RFC <<GeoJSON>>.
====


[requirement]
====
[%metadata]
identifier:: /req/storage-crs/processing

The implementation SHALL enforce the `storage-CRS` to any geometry data contained in the `FeatureOfInterest` and `Location` entity. The implementation SHALL store geometry encoded in the `default-CRS` without further processing.
====


[[GeometryJG]]
=== Geometry-FG Requirements Class

This Requirements Class defines the use of geometry encoding compliant with the OGC Draft Standard _OGC Features and Geometries JSON - Part 1: Core_ footnote:[draft OGC Standard at the time of writing: https://docs.ogc.org/DRAFTS/21-045.html]

[requirements_class]
.Geometry-FG

====
[%metadata]
identifier:: /req-class/geometry-fg
obligation:: requirement
subject:: Target Type: Web Service
inherit:: <<FG>>
requirement:: /req/geometry-fg/media-type
requirement:: /req/geometry-fg/default-crs
requirement:: /req/geometry-fg/supported-crs
requirement:: /req/geometry-fg/crs-error
requirement:: /req/geometry-fg/processing
requirement:: /req/geometry-fg/out
====


[requirement]
====
[%metadata]
identifier:: /req/geometry-fg/media-type

The implementation SHALL accept the media-type `application/vnd.ogc.fg+json` as value to the `encodingType` property of the `FeatureOfInterest` and `Location` entities to indicate that the structuring of the geometry is be compliant with the OGC Draft Standard _OGC Features and Geometries JSON - Part 1: Core_ footnote:[draft OGC Standard at the time of writing: https://docs.ogc.org/DRAFTS/21-045.html].
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-fg/default-crs

The implementation SHALL advertize the default CRS on the conformance page.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-fg/supported-crs

The implementation SHALL advertize the list of the supported CRS on the conformance page.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-fg/crs-error

The implementation SHALL return an error if the geometry data inside `feature` or `location` properties is encoded in an unsupported CRS.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-fg/processing

The implementation SHALL apply CRS transformation to the `default-CRS` if necessary before further processing or storing the geometry data.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-fg/out

The implementation SHALL use the storage-CRS to encode the `feature` and `location` geometries in a response.
====


[[GeometryWKT]]
=== Geometry WKT Requirements Class

This Requirements Class defines the use of geometry encoding compliant with Well-Known-Text.

[requirements_class]
.Geometry WKT

====
[%metadata]
identifier:: /req-class/geometry-wkt
obligation:: requirement
subject:: Target Type: Web Service
inherit:: <<ISO19125-1>>
requirement:: /req/geometry-wkt/media-type
requirement:: /req/geometry-wkt/crs-defintion
requirement:: /req/geometry-wkt/default-crs
requirement:: /req/geometry-wkt/supported-crs
requirement:: /req/geometry-wkt/crs-error
requirement:: /req/geometry-wkt/value
requirement:: /req/geometry-wkt/processing
requirement:: /req/geometry-wkt/out
====


[requirement]
====
[%metadata]
identifier:: /req/geometry-wkt/media-type

The implementation SHALL accept the media-type `wkt` as value to the `encodingType` property of the `FeatureOfInterest` and `Location` entities.
====


[requirement]
====
[%metadata]
identifier:: /req/geometry-wkt/crs-definition

If a non-default CRS is used then either the CRS identifier shall be put into a property `crs`, or the CRS identifier (number) SHALL be put into a property `srid` of the `properties` property of the `FeatureOfInterest` or `Location` entity.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-wkt/default-crs

The implementation SHALL advertize the default CRS on the conformance page.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-wkt/supported-crs

The implementation SHALL advertize the list of the supported CRS on the conformance page.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-wkt/crs-error

The implementation SHALL return an error if the geometry data inside the `FeatureOfInterest` or `Location`  is encoded in an unsupported CRS.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-wkt/value

The WKT encoded geometry SHALL be the value of the `feature` or `location` property (the type Any is a String).
====


[requirement]
====
[%metadata]
identifier:: /req/geometry-wkt/processing

The implementation SHALL apply CRS transformation to the `storage-CRS` if necessary before further processing or storing the geometry data.
====

[requirement]
====
[%metadata]
identifier:: /req/geometry-wkt/out

The implementation SHALL use the storage-CRS to encode the `feature` and `location` geometries in a response.
====
