[[req_dggs_advertisement]]
[requirement]
.Advertisement of the DGGS obfuscation
====
[%metadata]
identifier:: http://www.opengis.net/spec/sensorthings-staplus-gdpr/1.0/req/dggs/advertisement
part:: The `conformance` array of the `serverSettings` object on the service root URI SHALL contain `http://www.opengis.net/spec/sensorthings-staplus-gdpr/1.0/conf/dggs`.
part:: The member `locationGeneralization` of the JSON object named `http://www.opengis.net/spec/sensorthings-staplus-gdpr/1.0/conf/gdpr` in `serverSettings` SHALL be present and SHALL contain the member `method` with the value `dggs` and the member `zoneLevel` (Integer), the public zone level. The public zone level SHALL NOT be smaller than the `coarsestZoneLevel` and SHALL NOT be larger than the `finestZoneLevel` advertised in the JSON object named `http://www.opengis.net/spec/sensorthings-dggs/1.0/req/grid-system`.
part:: The grid system used for obfuscation SHALL be the `gridSystem` advertised according to `http://www.opengis.net/spec/sensorthings-dggs/1.0/req/grid-system`.
part:: If the implementation claims the conformance class `http://www.opengis.net/spec/sensorthings-dggs/1.0/conf/aggregation`, the JSON object named `http://www.opengis.net/spec/sensorthings-staplus-gdpr/1.0/conf/gdpr` SHALL contain the member `minimumContributors` (Integer, not smaller than 2).
====
