[[ats_sta_websub_discovery_link_help]]
[abstract_test]
====
[%metadata]
label:: /conf/discovery/api-sta-websub-link-header-help
identifier:: /conf/discovery/api-sta-websub-link-header-help
target:: /req/req-class-discovery/req-link-help
subject:: /req/req-class/discovery/req-discovery-help
test-purpose:: Validate that the WebSub discovery returns the link headers `hub` and `help` for a topic URL **not allowed** for subscription.

[.component,class=test method]
=====
[.component,class=step]
--
Construct a topic URL that is **not allowed** for subscription. 
--

[NOTE]
To determine which topic URLs **are not allowed**, examine the root page. The cause for 'not allowed' SHALL be based on `topics_denied` or `odata_denied`.

[.component,class=step]
--
Issue a HTTP HEAD and GET request on that topic URL.
--

[.component,class=step]
--
Validate that the response includes the Link header `hub` and `help`. In particular validate that the Link header `self` is not present!
--
=====
====

==== Example for topics and ODATA restrictions

[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": ["v1.1/Observations"],
            "odata_denied": ["$expand"]
        }
    }
}
----

==== Example HTTP request and response for a URL including the denied topic `v1.1/Observations`

[source,text]
----
GET /sta/v1.1/Observations HTTP/1.1
Host: sta-websub.secd.eu

HTTP/1.1 200 Ok
Content-type: application/json
Link: <http://hub.sta-websub.secd.eu>; rel="hub"
Link: <http://sta-websub.secd.eu/sta/v1.1/help#topic_denied>; rel="help"
----

==== Example HTTP request and response for a URL including the denied ODATA option `$expand`

[source,text]
----
GET /sta/v1.1/Things?$expand=Locations HTTP/1.1
Host: sta-websub.secd.eu

HTTP/1.1 200 Ok
Content-type: application/json
Link: <http://hub.sta-websub.secd.eu>; rel="hub"
Link: <http://sta-websub.secd.eu/sta/v1.1/help#odata_option_denied>; rel="help"
----