[[ats_sta_websub_odata_discovery]]
[abstract_test]
====
[%metadata]
label:: /conf/discovery/api-sta-websub-odata
identifier:: /conf/discovery/api-sta-websub-odata-discovery
target:: /req/req-class-discovery/req-odata-discovery
subject:: /req/req-class/discovery
test-purpose:: Validate that the disallowed ODATA options are advertised on the root page.

[.component,class=test method]
=====
[.component,class=step]
--
Construct a URL to the root page.
--

[.component,class=step]
--
Issue a HTTP HEAD and GET request on that URL.
--

[.component,class=step]
--
Validate the contents of the returned document to include the implemented Conformance Class(es) in the `conformance` section of the root page:

`http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery`
--



[.component,class=step]
--
Validate the contents of the returned document to include the JSON object `http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery` in the `serverSettings` including the key `odata_denied`. 
--

[.component,class=step]
--
Validate that the value of the key `odata_denied` is a JSON array that is either empty ("[]") or contains a list of denied ODATA options.
--

=====
====

==== Example root page snippet advertising no denied ODATA options

[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": [],
            "odata_denied": []
        }
    }
}
----

==== Example root page snippet advertising `$expand` as a denied ODATA option
[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": [],
            "odata_denied": ["$expand"]
        }
    }
}
----