[[ats_sta_websub_landingpage_odata]]
[abstract_test]
====
[%metadata]
label:: /conf/discovery/api-sta-websub-landing-page
subject:: /req/req-class/landing-page-odata
test-purpose:: Validate that the denied ODATA commands are advertised on the Landing Page.

[.component,class=test method]
=====
[.component,class=step]
--
Construct a URL to the Landing Page.
--

[.component,class=step]
--
Issue a HTTP GET request on that URL.
--

[.component,class=step]
--
Validate the contents of the returned document to include the implemented Conformance Class(es):

`http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery`
--

[.component,class=step]
--
Validate the contents of the returned document to include the JSON object `http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery` including the key `odata_denied`. 
--

[.component,class=step]
--
Validate that the value of the key `odata_denied` is a JSON array that is either empty ("[]") or contains a list of denied ODATA commands.
--

=====
====

==== Example Landing Page snippet advertising no denied ODATA commands

```JSON
{
    "serverSettings": {
        "conformance": {
            "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "odata_denied": []
        }
    }
}
```

==== Example Landing Page snippet advertising `$expand` as a denied ODATA command

```JSON
{
    "serverSettings": {
        "conformance": {
            "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "odata_denied": ["$expand"]
        }
    }
}
```