[[ats_sta_websub_odata_no_blacklisting]]
[abstract_test]
====
[%metadata]
label:: /conf/discovery/api-sta-websub-odata-no-blacklisting
identifier:: /conf/discovery/api-sta-websub-odata-no-blacklisting
target:: /req/req-class-discovery/req-odata-blacklisting
subject:: /req/req-class-discovery/req-odata-blacklisting
test-purpose:: Validate that the allowed ODATA options do return the HTTP link header `rel="self"`.

[.component,class=test method]
=====
[.component,class=step]
--
Construct multiple SensorThings URLs each including a supported ODATA option that is not listed under the `odata_denied`.
--

[.component,class=step]
--
Issue HTTP HEAD and GET requests on each URL.
--

[.component,class=step]
--
Validate the contents of the returned HTTP header to include the link header `rel="self"` that includes the issued URL.
--

=====
====

==== Example root page with denied ODATA option `$expand`

[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": [],
            "odata_denied": ["$expand"]
        }
    }
}
----

==== Example HTTP response for a URL not including the denied ODATA option

[source,text]
----
GET /sta/v1.1/Things?$select=name HTTP/1.1
Host: localhost

HTTP/1.1 200 Ok
Content-type: application/json
Link: <http://hub.localhost>; rel="hub"
Link: <http://localhost/sta/v1.1/Things?%24select%3Dname>; rel="self"
----