[[ats_sta_websub_landing_page_topics_discovery]]
[abstract_test]
====
[%metadata]
label:: /conf/discovery/api-sta-websub-landing-page-topics
identifier:: /conf/discovery/api-sta-websub-landing-page-topics
target:: /req/req-class-discovery/req-landing-page-topics
subject:: /req/req-class-discovery/req-landing-page-topics
test-purpose:: Validate that the denied root topics are advertised on the Root Page.

[.component,class=test method]
=====
[.component,class=step]
--
Construct a URL to the Root Page.
--

[.component,class=step]
--
Issue a HTTP HEAD and GET request on that URL.
--

[.component,class=step]
--
Validate the contents of the returned document to include the implemented Conformance Class(es):

`https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery`
--

[.component,class=step]
--
Validate the contents of the returned document to include the JSON object `https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery` including the key `topics_denied`. 
--

[.component,class=step]
--
Validate that the value of the key `topics_denied` is a JSON array that it is either empty ("[]") or contains a list of denied root topics.
--

[.component,class=step]
--
Validate that each value of the key `topics_denied` is compliant to `SERVICE_VERSION/RESOURCE_PATH_TO_AN_ENTITY`.
--

NOTE: A root topic starts with `SERVICE_VERSION/RESOURCE_PATH_TO_AN_ENTITY` as defined in https://docs.ogc.org/is/18-088/18-088.html#mqtt-entity-updates[14.2.2]
=====
====

==== Example Root Page snippet advertising no denied root topics

[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": []
        }
    }
}
----

==== Example Root Page snippet advertising `v1.1/Observations` as a denied root topic

[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": ["v1.1/Observations"]
        }
    }
}
----