[[ats_sta_websub_odata_blacklisting]]
[abstract_test]
====
[%metadata]
label:: /conf/discovery/api-sta-websub-odata-blacklisting
identifier:: /conf/discovery/api-sta-websub-odata-blacklisting
target:: /req/req-class-discovery/req-odata-blacklisting
subject:: /req/req-class-discovery/req-odata-blacklisting
test-purpose:: Validate that the disallowed ODATA options do not return the HTTP link header `rel="self"`.

[.component,class=test method]
=====
[.component,class=step]
--
Construct multiple SensorThings URLs each including a supported ODATA option that is listed under the `odata_denied`.
--

[.component,class=step]
--
Issue HTTP HEAD and GET requests on each URL.
--

[.component,class=step]
--
Validate the contents of the returned HTTP header to not include the link header `rel="self"` but the link header `rel="help"`.
--

[.component,class=step]
--
Validate the contents of the returned HTTP header to include the link header `rel="hub"`.
--

=====
====

==== Example root page with denied ODATA option `$expand`

[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "https://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": [],
            "odata_denied": ["$expand"]
        }
    }
}
----

==== Example HTTP response for a URL including the denied ODATA option `$expand`

[source,text]
----
GET /sta/v1.1/Things?$expand=Locations HTTP/1.1
Host: localhost

HTTP/1.1 200 Ok
Content-type: application/json
Link: <http://hub.localhost>; rel="hub"
Link: <http://localhost/sta/v1.1/help#odata_option_denied>; rel="help"
----