[[ats_sta_websub_landing_page_discovery]]
[abstract_test]
====
[%metadata]
label:: /conf/discovery/api-sta-websub-landing-page-discovery
identifier:: /conf/discovery/api-sta-websub-topics-discovery
subject:: /req/req-class-discovery/req-discovery
target:: /req/req-class-discovery/req-topics-discovery
test-purpose:: Validate that the implemented STA-WebSub Conformance Class `Discovery` is listed on the root page.

[.component,class=test method]
=====
[.component,class=step]
--
Construct a URL to the root page.
--

[.component,class=step]
--
Issue a HTTP GET request on that URL.
--

[.component,class=step]
--
Validate the contents of the returned document to include the implemented Conformance Class(es) in the `conformance` section of the root page:

`http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery`
--



[.component,class=step]
--
Validate the contents of the returned document to include the JSON object `http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery` in the `serverSettings` including the key `topics_denied`. 
--

[.component,class=step]
--
Validate that the value of the key `topics_denied` is a JSON array that is either empty ("[]") or contains a list of denied topics.
--

=====
====

==== Example root page snippet advertising no denied ODATA options

[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": [],
            "odata_denied": []
        }
    }
}
----

==== Example root page snippet advertising `v1.1/Observations` as a denied topic

[source,json]
----
{
    "serverSettings": {
        "conformance": {
            "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery"
        },
        "http://www.opengis.net/spec/sensorthings-websub/1.0/conf/discovery": {
            "topics_denied": ["v1.1/Observations"],
            "odata_denied": []
        }
    }
}
----