[conformance_class]
====
[%metadata]
identifier:: {identifier}/conf-class/binding/http
target:: {identifier}/req-class/binding/http
classification:: Target Type:Web API
inherit:: {identifier}/conf-class/datamodel/core
conformance-test:: {identifier}/conf/binding/http/advertisement
conformance-test:: {identifier}/conf/binding/http/request_response
====



[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/binding/http/advertisement
target:: {identifier}/req/binding/http/advertisement
test-purpose:: Validate the binding advertisement in the service document.
test-method::
For each request_response binding:
. Construct a path for the service document.

. Issue a Read request on that path.

. Validate that the http binding is advertised, and endpoints are set.
====



[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/binding/http/request_response
target:: {identifier}/req/binding/http/request_response
inherit:: {identifier}/conf-class/api/abstract
test-purpose:: Validate that the request types defined in the abstract API are mapped to the correct HTTP methods.
test-method::
. Execute a GET request on the URL for the service document.
. Validate that a service document is returned.

====
