[conformance_class]
====
[%metadata]
identifier:: {identifier}/conf-class/api/read
target:: {identifier}/req-class/api/read
conformance-test:: {identifier}/conf/api/read/paths
conformance-test:: {identifier}/conf/api/read/options/precedence
conformance-test:: {identifier}/conf/api/read/options/select
conformance-test:: {identifier}/conf/api/read/options/select_distinct
conformance-test:: {identifier}/conf/api/read/options/expand
conformance-test:: {identifier}/conf/api/read/options/top
conformance-test:: {identifier}/conf/api/read/options/skip
conformance-test:: {identifier}/conf/api/read/options/count
conformance-test:: {identifier}/conf/api/read/options/orderby
conformance-test:: {identifier}/conf/api/read/options/filter
conformance-test:: {identifier}/conf/api/read/options/format
conformance-test:: {identifier}/conf/api/read/options/pagination
====



[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/paths
target:: {identifier}/req/api/read/paths
test-purpose:: Validate that all the specified paths can be read, for the implemented data model.
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/precedence
target:: {identifier}/req/api/read/options/precedence
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/select
target:: {identifier}/req/api/read/options/select
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/select_distinct
target:: {identifier}/req/api/read/options/select_distinct
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/expand
target:: {identifier}/req/api/read/options/expand
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/top
target:: {identifier}/req/api/read/options/top
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/skip
target:: {identifier}/req/api/read/options/skip
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/count
target:: {identifier}/req/api/read/options/count
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/orderby
target:: {identifier}/req/api/read/options/orderby
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/filter
target:: {identifier}/req/api/read/options/filter
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/format
target:: {identifier}/req/api/read/options/format
test-purpose:: Validate that ...
test-method::
. See if ...

====


[abstract_test]
====
[%metadata]
identifier:: {identifier}/conf/api/read/options/pagination
target:: {identifier}/req/api/read/options/pagination
test-purpose:: Validate that ...
test-method::
. See if ...

====
