#!/usr/bin/ruby
require 'asciidoctor'

doc = Asciidoctor.load_file(ARGV[0], to_file: false, safe: :unsafe, catalog_assets: true)

print "// DO NOT EDIT THIS AUTOGENERATED FILE.\n\n"
print "[preface]\n== Table of Figures\n\n"

figs = doc.references[:ids].keys.find_all { |x| x.start_with? "fig-" }
figs.each do |fig|
    print "* <<" + fig + ">> - " + doc.references[:ids][fig] + "\n"
end
print "\n\n"

print "[preface]\n== Table of Tables\n\n"

figs = doc.references[:ids].keys.find_all { |x| x.start_with? "tab-" }
figs.each do |fig|
    print "* <<" + fig + ">> - " + doc.references[:ids][fig] + "\n"
end
print "\n\n"

print "[preface]\n== Table of Requirements\n\n"

figs = doc.references[:ids].keys.find_all { |x| x.start_with? "req-" }
figs.each do |fig|
    print "* Requirement <<" + fig + ">> - <<requirement-" + fig[4 .. -1] + ">>\n"
end
print "\n\n"
