[[references]]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

* ISO 8601:2004 Data elements and interchange formats – Information interchange - Representation of dates and times.
* OGC 10-004r3 and ISO 19156:2011(E), OGC Abstract Specification Topic 20: Geographic information — Observations and Measurements
* OASIS OData Version 4.0 Part 1: Protocol Plus Errata 02
* OASIS OData Version 4.0 Part 2: URL Conventions Plus Errata 02
* OASIS OData JSON Format Version 4.0 Plus Errata 02
* OASIS OData ABNF Construction Rules Errata 02
* RFC 2046, Multipurpose Internet Mail Extensions (MIME) Part Two: Media Types
* RFC 2616, Hypertext Transfer Protocol -- HTTP/1.1
* RFC 4627, the application/json Media Type for Javascript Object Notation (JSON), July 2006
* Unified Code for Units of Measure (UCUM) – Version 1.9, April 2015
