[appendix]
== Conformance Class Abstract Test Suite (Normative)

=== SensorThings Read (Core) Tests

This section contains the conformance classes for the SensorThings API Read (Core). The SensorThings API service needs to pass all the conformance tests defined in this section.

[%autowidth,cols="a,a"]
|===
2+|A.1.1 Conformance class: SensorThings API Entity Control Information

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information

2+|**Test: Common Control Information**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information/common-control-information


|Requirements
|<<req-aa>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-aa>>

|Test purpose
|Check if each entity has the common control information as defined in the requirement \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-aa>>.

|Test method
|Inspect the full JSON object of the entity sets (__i.e.__, without $select) to identify, if each entity has the common control information defined in the above requirement and the service sends appropriate responses as defined in this specification.
|===




[%autowidth,cols="a,a"]
|===
2+|A.1.2 Conformance class: SensorThings API Thing Entity

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/thing

2+|**Test: Thing Entity**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/thing/thing-valid

|Requirements
|<<req-ab>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ab>> +
<<req-ac>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ac>>

|Test purpose
|Check if each Thing entity has the mandatory properties and mandatory relations as defined in this specification.

|Test method
|Inspect the full JSON object of the Thing entity sets (__i.e.__, without $select) to identify, if each entity has the mandatory properties defined in the corresponding requirement.

Inspect the full JSON object of each Thing entity set (__i.e.__, without using the $select query option) to identify, if each entity has the mandatory relations (__i.e.__, @iot.navigationLink) defined in the corresponding requirement.
|===




[%autowidth,cols="a,a"]
|===
2+|A.1.3 Conformance class: SensorThings API Location Entity

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/location

2+|**Test: Location Entity**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/location/location-valid

|Requirements
|<<req-ad>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ad>> +
<<req-ae>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ae>>

|Test purpose
|Check if each Location entity has the mandatory properties and mandatory relations as defined in this specification.

|Test method
|Inspect the full JSON object of the Location entity sets (__i.e.__, without $select) to identify, if each entity has the mandatory properties defined in the corresponding requirement.

Inspect the full JSON object of each Location entity set (__i.e.__, without using the $select query option) to identify, if each entity has the mandatory relations (__i.e.__, @iot.navigationLink) defined in the corresponding requirement.
|===




[%autowidth,cols="a,a"]
|===
2+|A.1.4 Conformance class: SensorThings API HistoricalLocation Entity

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location

2+|**Test: Historicalocation Entity**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location/historical-location-valid

|Requirements
|<<req-af>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-af>> +
<<req-ag>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ag>>

|Test purpose
|Check if each Historicalocation entity has the mandatory properties and mandatory relations as defined in this specification.

|Test method
|Inspect the full JSON object of the Historicalocation entity sets (__i.e.__, without $select) to identify, if each entity has the mandatory properties defined in the corresponding requirement.

Inspect the full JSON object of each Historicalocation entity set (__i.e.__, without using the $select query option) to identify, if each entity has the mandatory relations (__i.e.__, @iot.navigationLink) defined in the corresponding requirement.
|===


[%autowidth,cols="a,a"]
|===
2+|A.1.5 Conformance class: SensorThings API Datastream Entity

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream

2+|**Test: Datastream Entity**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream/datastream-valid

|Requirements
|<<req-ai>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ai>> +
<<req-aj>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-aj>>

|Test purpose
|Check if each Datastream entity has the mandatory properties and mandatory relations as defined in this specification.

|Test method
|Inspect the full JSON object of the Datastream entity sets (__i.e.__, without $select) to identify, if each entity has the mandatory properties defined in the corresponding requirement.

Inspect the full JSON object of each Datastream entity set (__i.e.__, without using the $select query option) to identify, if each entity has the mandatory relations (__i.e.__, @iot.navigationLink) defined in the corresponding requirement.
|===




[%autowidth,cols="a,a"]
|===
2+|A.1.6 Conformance class: SensorThings API Sensor Entity

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor

2+|**Test: Sensor Entity**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor/sensor-valid

|Requirements
|<<req-ak>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ak>> +
<<req-al>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-al>>

|Test purpose
|Check if each Sensor entity has the mandatory properties and mandatory relations as defined in this specification.

|Test method
|Inspect the full JSON object of the Sensor entity sets (__i.e.__, without $select) to identify, if each entity has the mandatory properties defined in the corresponding requirement.

Inspect the full JSON object of each Sensor entity set (__i.e.__, without using the $select query option) to identify, if each entity has the mandatory relations (__i.e.__, @iot.navigationLink) defined in the corresponding requirement.
|===




[%autowidth,cols="a,a"]
|===
2+|A.1.7 Conformance class: SensorThings API ObservedProperty Entity

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property

2+|**Test: ObservedProperty Entity**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property/observed-property-valid

|Requirements
|<<req-am>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-am>> +
<<req-an>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-an>>

|Test purpose
|Check if each ObservedProperty entity has the mandatory properties and mandatory relations as defined in this specification.

|Test method
|Inspect the full JSON object of the ObservedProperty entity sets (__i.e.__, without $select) to identify, if each entity has the mandatory properties defined in the corresponding requirement.

Inspect the full JSON object of each ObservedProperty entity set (__i.e.__, without using the $select query option) to identify, if each entity has the mandatory relations (__i.e.__, @iot.navigationLink) defined in the corresponding requirement.
|===




[%autowidth,cols="a,a"]
|===
2+|A.1.8 Conformance class: SensorThings API Observation Entity

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/observation

2+|**Test: Observation Entity**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/observation/observation-valid

|Requirements
|<<req-ao>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ao>> +
<<req-ap>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ap>>

|Test purpose
|Check if each Observation entity has the mandatory properties and mandatory relations as defined in this specification.

|Test method
|Inspect the full JSON object of the Observation entity sets (__i.e.__, without $select) to identify, if each entity has the mandatory properties defined in the corresponding requirement.

Inspect the full JSON object of each Observation entity set (__i.e.__, without using the $select query option) to identify, if each entity has the mandatory relations (__i.e.__, @iot.navigationLink) defined in the corresponding requirement.
|===




[%autowidth,cols="a,a"]
|===
2+|A.1.9 Conformance class: SensorThings API FeatureOfInterest Entity

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest

2+|**Test: FeatureOfInterest Entity**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest/feature-of-interest-valid

|Requirements
|<<req-aq>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-aq>> +
<<req-ar>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ar>>

|Test purpose
|Check if each FeatureOfInterest entity has the mandatory properties and mandatory relations as defined in this specification.

|Test method
|Inspect the full JSON object of the FeatureOfInterest entity sets (__i.e.__, without $select) to identify, if each entity has the mandatory properties defined in the corresponding requirement.

Inspect the full JSON object of each FeatureOfInterest entity set (__i.e.__, without using the $select query option) to identify, if each entity has the mandatory relations (__i.e.__, @iot.navigationLink) defined in the corresponding requirement.
|===




[%autowidth,cols="a,a"]
|===
2+|A.1.10   Conformance class: SensorThings API Resource Path

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path

2+|**Test: Resource Path**

|Test id
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path/resource-path-to-entities

|Requirements
|<<req-as>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-as>>

|Test purpose
|Check if the service supports all the resource path usages as defined in the requirement \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-as>>.

|Test method
|Inspect the service to identify, if each resource path usage has been implemented property.
|===


=== SensorThings API Filtering Extension Tests

This section contains the conformance classes for the SensorThings API filtering extension. That means a SensorThings API service that allows clients to further filter data with query options needs to pass the conformance tests defined in this section.


[%autowidth,cols="a,a"]
|===
2+|A.2.1  Conformance class: SensorThings API Request Data with Filters

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/request-data

2+|**Dependencies:**

. \http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/thing
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/location
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/observation
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest
. \http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path


[%autowidth,cols="a,a"]
!===
2+!A.2.1.1 Test: Query Option Order
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/request-data/order

!Requirements
!<<req-av>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-av>>

!Test purpose
!Check if the results of the service requests are as if the system query options were evaluated in the order as defined in this specification.

!Test method
!Send a query includes the query options listed in requirement \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-av>>, and check if the results are evaluated according to the order defined in this specification.

!===




[%autowidth,cols="a,a"]
!===
2+!A.2.1.2 Test: Request Data with $expand and $select
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/request-data/expand-and-select

!Requirements
!<<req-aw>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-aw>> +
<<req-ax>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ax>>

!Test purpose
!Check if the service supports $expand and $select as defined in this specification.

!Test method
!Send requests with $expand following the different usages as defined in the requirement \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-aw>>, check if the server returns appropriate result as defined in this specification.

Send requests with the $select option following the different usages as defined in the requirement \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ax>>, check if the server returns appropriate result as defined in this specification.
!===




[%autowidth,cols="a,a"]
!===
2+!A.2.1.3 Test: Query Option Response Code
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/request-data/status-codes

!Requirements
!<<req-at>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-at>> +
<<req-au>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-au>>

!Test purpose
!Check when a client requests an entity that is not available in the service, if the service responds with 404 Not Found or 410 Gone as defined in the requirement \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-at>>

Check when a client use a query option that doesn't support by the service, if the service fails the request and responds with 501 NOT Implemented as defined in the requirement \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-au>>.

!Test method
!Send a HTTP request for an entity that is not available in the service, check if the server returns 404 Not Found or 410 Gone.


(If applicable) Send a query with a query option that is not supported by the service, check if the server returns 501 Not Implemented.

!===




[%autowidth,cols="a,a"]
!===
2+!A.2.1.4 Test: Sorting Query Option
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/request-data/sorting

!Requirements
!<<req-ay>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ay>>

!Test purpose
!Check if the service supports the $orderby query option as defined in this specification.

!Test method
!Send a query with the $orderby query option, check if the server returns appropriate result as defined in this specification.

!===




[%autowidth,cols="a,a"]
!===
2+!A.2.1.5 Test: Client-driven Pagination Query Option
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/request-data/client-driven-pagination

!Requirements
!<<req-az>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-az>>
<<req-ba>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ba>>
<<req-bb>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bb>>

!Test purpose
!Check if the service supports the $top, $skip and $count query option as defined in this specification.

!Test method
!Send a query with the $top query option, check if the server returns appropriate result as defined in this specification.

Send a query with the $skip query option, check if the server returns appropriate result as defined in this specification.

Send a query with the $count query option, check if the server returns appropriate result as defined in this specification.
!===




[%autowidth,cols="a,a"]
!===
2+!A.2.1.6 Test: Filter Query Option
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/request-data/filter-query-options

!Requirements
!<<req-bc>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bc>>
<<req-bd>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bd>>
<<req-be>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-be>>

!Test purpose
!Check if the service supports the $filter query option and the built-in filter operators and built-in filter functions as defined in this specification.

!Test method
!Send a query with the $filter query option, check if the server returns appropriate result as defined in this specification.

Send a query with the $filter query option for each built-in filter operator, check if the server returns appropriate result as defined in this specification.

Send a query with the $filter query option for each built-in filter function, check if the server returns appropriate result as defined in this specification.
!===




[%autowidth,cols="a,a"]
!===
2+!A.2.1.7 Test: Server-driven Pagination
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/request-data/server-driven-pagination

!Requirements
!<<req-bf>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bf>>

!Test purpose
!Check if the service supports the server-driven pagination as defined in the requirement \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bf>>.

!Test method
!Send a query to list all entities of an entity set, check if the server returns a subset of the requested entities as defined in this specification.
!===

|===


=== SensorThings API Create-Update-Delete Extension Tests

This section contains the conformance classes for the SensorThings API create-update-delete extension. That means a SensorThings API service that allows clients to create/update/delete entities needs to pass the conformance tests defined in this section.




[%autowidth,cols="a,a"]
|===
2+|A.3.1  Conformance class: SensorThings API Create-Update-Delete

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/create-update-delete

2+|**Dependencies:**

. http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information
. http://www.opengis.net/spec/iot_sensing/1.0/conf/thing
. http://www.opengis.net/spec/iot_sensing/1.0/conf/location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream
. http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observation
. http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest
. http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path


[%autowidth,cols="a,a"]
!===
2+!A.3.1.1 Test: Sensing Entity Creation
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/create-update-delete/sensing-entity-creation

!Requirements
!<<req-bg>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bg>>


<<req-bh>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bh>>


<<req-bi>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bi>>


<<req-bj>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bj>>


<<req-ah>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-ah>>

!Test purpose
!Check if the service supports the creation of entities as defined in this specification.

!Test method
!For each SensorThings entity type creates an entity instance by following the integrity constraints of Table 24 and creating the related entities with a single request (__i.e.__, deep insert), check if the entity instance is successfully created and the server responds as defined in this specification.

Create an entity instance and its related entities with a deep insert request that does not conform to the specification (e.g., missing a mandatory property), check if the service fails the request without creating any entity within the deep insert request and responds the appropriate HTTP status code.


For each SensorThings entity type issue an entity creation request that does not follow the integrity constraints of Table 24 with deep insert, check if the service fails the request without creating any entity within the deep insert request and responds the appropriate HTTP status code.


For each SensorThings entity type creates an entity instance by linking to existing entities with a single request, check if the server responds as defined in this specification.


For each SensorThings entity type creates an entity instance that does not follow the integrity constraints of Table 24 by linking to existing entities with a single request, check if the server responds as defined in this specification.


Create an Observation entity for a Datastream without any Observations and the Observation creation request does not create a new or linking to an existing FeatureOfInterest, check if the service creates a new FeatureOfInterest for the created Observation with the location property of the Thing’s Location entity.


Create an Observation entity for a Datastream that already has Observations and the Observation creation request does not create a new or linking to an existing FeatureOfInterest, check if the service automatically links the newly created Observation with an existing FeatureOfInterest whose location property is from the Thing’s Location entity.


Create an Observation entity and the Observation creation request does not include resultTime, check if the resultTime property is created with a null value.


Create a Location for a Thing entity, check if the Thing has a HistoricalLocation created by the service according to the Location entity.
!===




[%autowidth,cols="a,a"]
!===
2+!A.3.1.2 Test: Sensing Entity Update
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/create-update-delete/update-entity

!Requirements
!<<req-bk>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bk>>

!Test purpose
!Check if the service supports the update of entities as defined in this specification.

!Test method
!For each SensorThings entity type send an update request with PATCH, check (1) if the properties provided in the payload corresponding to updatable properties replace the value of the corresponding property in the entity and (2) if the missing properties of the containing entity or complex property are not directly altered.

(Where applicable) For each SensorThings entity type send an update request with PUT, check if the service responds as defined in <<update-entity>>.

For each SensorThings entity type send an update request with PATCH that contains related entities as inline content, check if the service fails the request and returns appropriate HTTP status code.

For each SensorThings entity type send an update request with PATCH that contains binding information for navigation properties, check if the service updates the navigationLink accordingly.
!===




[%autowidth,cols="a,a"]
!===
2+!A.3.1.3 Test: Sensing Entity Deletion
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/create-update-delete/sensing-entity-deletion

!Requirements
!<<req-bl>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bl>>

!Test purpose
!Check if the service supports the deletion of entities as defined in <<delete-entity>>.

!Test method
!Delete an entity instance, and check if the service responds as defined in <<delete-entity>>.
!===

|===


=== SensorThings API Batch Request Extension Tests

This section contains the conformance classes for the SensorThings API batch request extension. That means a SensorThings API service that allows clients to send a single HTTP request that groups multiple requests needs to pass the conformance tests defined in this section.




[%autowidth,cols="a,a"]
|===
2+|A.4.1 Conformance class: SensorThings API Batch Request

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/batch-request

2+|**Dependencies:**

. http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information
. http://www.opengis.net/spec/iot_sensing/1.0/conf/thing
. http://www.opengis.net/spec/iot_sensing/1.0/conf/location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream
. http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observation
. http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest
. http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path


[%autowidth,cols="a,a"]
!===
2+!A.4.1.1 Test: Batch Request
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/batch-request/batch-request

!Requirements
!<<req-bm>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bm>>

!Test purpose
!Check if the service supports the batch request as defined in <<batch-requests>>.

!Test method
!Submit batch requests according to the examples listed in <<batch-requests>>, check if the service responds as defined in this specification.
!===

|===


=== SensorThings API MultipleDatastream Tests


This section contains the conformance classes for the SensorThings API MultiDatastream extension. That means a SensorThings API service that allows clients to group a collection of observations’ results into an array (__i.e.__, a complex result type) needs to pass the conformance tests defined in this section.




[%autowidth,cols="a,a"]
|===
2+|A.5.1   Conformance class: SensorThings API MultiDatastream

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/multi-datastream

2+|**Dependencies:**

. http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information
. http://www.opengis.net/spec/iot_sensing/1.0/conf/thing
. http://www.opengis.net/spec/iot_sensing/1.0/conf/location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream
. http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observation
. http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest
. http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path


[%autowidth,cols="a,a"]
!===
2+!A.5.1.1 Test: SensorThings API MultiDatastream
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/multi-datastream/multi-datastream-valid

!Requirements
!<<req-bn>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bn>>


<<req-bo>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bo>>


<<req-bp>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bp>>

!Test purpose
!Check if the service's MultiDatastream entity has the mandatory properties and relations as defined in this specification.

!Test method
!Inspect the full JSON object of a MultiDatastream entity (__i.e.__, without $select)
to identify, if each entity has the mandatory properties and relations, and fulfill the constraints defined in the corresponding requirements.

!===

|===


=== SensorThings API Data Array Extension

This section contains the conformance classe for the SensorThings API data array extension. That means a SensorThings API service that allows clients to request the compact data array encoding defined in this specification needs to pass the conformance tests defined in this section.




[%autowidth,cols="a,a"]
|===
2+|A.6.1  Conformance class: SensorThings API Data Array

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/data-array

2+|**Dependencies:**

. http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information
. http://www.opengis.net/spec/iot_sensing/1.0/conf/thing
. http://www.opengis.net/spec/iot_sensing/1.0/conf/location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream
. http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observation
. http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest
. http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path


[%autowidth,cols="a,a"]
!===
2+!A.6.1.1 Test: SensorThings API Sensing Data Array
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/data-array/data-array-valid

!Requirements
!<<req-bq>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bq>>

!Test purpose
!Check if the service supports the data array extension as defined in <<data-array-extension>>.

!Test method
!Issue a GET request for Datastreams (and MultiDatastreams if applicable) that includes the query option "$resultFormat=dataArray", and then inspect the returned JSON to identify if it fulfills the data array format as defined in <<data-array-extension>>.

Create at least two Datastreams by using the data array format as defined in <<data-array-extension>>. Inspect the response code and returned JSON to identify if it fulfills the response as defined in <<data-array-extension>>.

!===

|===


=== SensorThings API Observation Creation via MQTT Extension Tests

This section contains the conformance class for the SensorThings API Observation creation extension. That means a SensorThings API service that allows clients to create Observations via MQTT needs to pass the conformance tests defined in this section.




[%autowidth,cols="a,a"]
|===
2+|A.7.1  Conformance class: SensorThings API Observation Creation via MQTT

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/create-observations-via-mqtt

2+|**Dependencies:**

. http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information
. http://www.opengis.net/spec/iot_sensing/1.0/conf/thing
. http://www.opengis.net/spec/iot_sensing/1.0/conf/location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream
. http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observation
. http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest
. http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path
. http://www.opengis.net/spec/iot_sensing/1.0/conf/create-update-delete


[%autowidth,cols="a,a"]
!===
2+!A.7.1.1 Test: SensorThings API Observation Creation via MQTT
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/create-observations-via-mqtt/observation-creation

!Requirements
!<<req-br>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-br>>

!Test purpose
!Check if the service supports the creation and update of entities via MQTT as defined in <<create-mqtt-publish>>.

!Test method
!Create an Observation entity instance containing binding information for navigation properties using MQTT Publish, check if the server responds as defined in <<create-mqtt-publish>>.

!===

|===


=== SensorThings API Receiving Updates via MQTT Extension Tests

This section contains the conformance class for the SensorThings API receiving updates extension. That means a SensorThings API service that allows clients to receive notifications regarding updates of entities via MQTT needs to pass the conformance tests defined in this section.




[%autowidth,cols="a,a"]
|===
2+|A.8.1   Conformance class: SensorThings API Receiving Updates via MQTT

|**Conformance class id:**
|\http://www.opengis.net/spec/iot_sensing/1.0/conf/receive-updates-via-mqtt

2+|**Dependencies:**

. http://www.opengis.net/spec/iot_sensing/1.0/conf/entity-control-information
. http://www.opengis.net/spec/iot_sensing/1.0/conf/thing
. http://www.opengis.net/spec/iot_sensing/1.0/conf/location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/historical-location
. http://www.opengis.net/spec/iot_sensing/1.0/conf/datastream
. http://www.opengis.net/spec/iot_sensing/1.0/conf/sensor
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observed-property
. http://www.opengis.net/spec/iot_sensing/1.0/conf/observation
. http://www.opengis.net/spec/iot_sensing/1.0/conf/feature-of-interest
. http://www.opengis.net/spec/iot_sensing/1.0/conf/resource-path
. http://www.opengis.net/spec/iot_sensing/1.0/conf/create-update-delete


[%autowidth,cols="a,a"]
!===
2+!A.8.1.1 Test: SensorThings API Receiving Updates via MQTT
!Test id
!http://www.opengis.net/spec/iot_sensing/1.0/conf/receive-updates-via-mqtt/receive-updates

!Requirements
!<<req-bs>>. \http://www.opengis.net/spec/iot_sensing/1.0/req/<<requirement-bs>>

!Test purpose
!Check if a client can receive notifications for the updates of a SensorThings entity set or an individual entity with MQTT.

!Test method
!Subscribe to an entity set with MQTT Subscribe. Then create a new entity of the subscribed entity set. Check if a complete JSON representation of the newly created entity through MQTT is received.

Subscribe to an entity set with MQTT Subscribe. Then update an existing entity of the subscribed entity set. Check if a complete JSON representation of the updated entity through MQTT is received.

Subscribe to an entity’s property with MQTT Subscribe. Then update the property with PATCH. Check if the JSON object of the updated property is received.

Subscribe to multiple properties of an entity set with MQTT Subscribe. Then create a new entity of the entity set.  Check if a JSON object of the subscribed properties is received.

Subscribe to multiple properties of an entity set with MQTT Subscribe. Then update an existing entity of the entity set with PATCH. Check if a JSON object of the subscribed properties is received.

!===

|===

